var APP_VERSION = '1.0.1';

// ════════════════════════════════════════════════
// RADICAUX — lookup table caractère → [symbole, signification fr]
// ════════════════════════════════════════════════
var RADICALS = {
  // ── Pronoms & particules ──────────────────────
  '你':['亻','personne'],  '我':['戈','lance'],    '他':['亻','personne'],
  '她':['女','femme'],     '们':['亻','personne'], '您':['心','cœur'],
  '这':['辶','chemin'],    '那':['阝','colline'],  '什':['亻','personne'],
  '么':['乙','crochet'],   '的':['白','blanc'],    '了':['乙','crochet'],
  '不':['一','un'],        '是':['日','soleil'],   '有':['月','lune'],
  '在':['土','terre'],     '和':['口','bouche'],   '也':['乙','crochet'],
  '都':['阝','colline'],   '很':['彳','pas'],      '吗':['口','bouche'],
  '呢':['口','bouche'],    '啊':['口','bouche'],   '吧':['口','bouche'],
  '没':['氵','eau'],       '可':['口','bouche'],   '以':['人','personne'],
  '能':['厶','privé'],     '会':['人','personne'], '要':['西','ouest'],
  '就':['尢','estropié'],  '还':['辶','chemin'],   '再':['冂','enclos'],
  '又':['又','main'],      '只':['口','bouche'],   '已':['己','soi'],
  '但':['亻','personne'],  '比':['比','comparer'], '最':['日','soleil'],
  '太':['大','grand'],     '真':['目','œil'],      '对':['又','main'],
  '错':['钅','métal'],     '好':['女','femme'],    '行':['行','aller'],
  '因':['囗','enclos'],    '为':['力','force'],    '所':['户','porte'],
  '如':['女','femme'],     '果':['木','bois'],     '虽':['虫','insecte'],
  '然':['灬','feu'],       '经':['纟','fil'],      '特':['牛','bœuf'],
  '别':['刂','couteau'],   '更':['曰','dire'],

  // ── Famille ───────────────────────────────────
  '爸':['父','père'],      '妈':['女','femme'],    '哥':['口','bouche'],
  '姐':['女','femme'],     '弟':['弓','arc'],      '妹':['女','femme'],
  '家':['宀','maison'],    '父':['父','père'],      '母':['毋','mère'],
  '祖':['礻','montrer'],   '奶':['女','femme'],    '爷':['父','père'],
  '兄':['儿','enfant'],    '夫':['大','grand'],    '妻':['女','femme'],
  '儿':['儿','enfant'],    '女':['女','femme'],    '子':['子','enfant'],
  '孩':['子','enfant'],

  // ── Corps humain ─────────────────────────────
  '头':['大','grand'],     '手':['手','main'],     '眼':['目','œil'],
  '耳':['耳','oreille'],   '嘴':['口','bouche'],   '脸':['月','lune'],
  '身':['身','corps'],     '脚':['月','lune'],     '鼻':['鼻','nez'],
  '心':['心','cœur'],      '背':['月','lune'],     '腿':['月','lune'],
  '脖':['月','lune'],      '肩':['月','lune'],     '肚':['月','lune'],
  '牙':['牙','dent'],      '发':['又','main'],     '皮':['皮','peau'],

  // ── Nourriture & boissons ─────────────────────
  '饭':['饣','aliment'],   '面':['面','farine'],   '米':['米','riz'],
  '肉':['肉','viande'],    '鱼':['鱼','poisson'],  '蛋':['虫','insecte'],
  '奶':['女','femme'],     '茶':['艹','plante'],   '水':['水','eau'],
  '汤':['氵','eau'],       '菜':['艹','plante'],   '苹':['艹','plante'],
  '香':['禾','céréale'],   '蕉':['艹','plante'],   '橙':['木','bois'],
  '梨':['木','bois'],      '桃':['木','bois'],     '瓜':['瓜','courge'],
  '豆':['豆','haricot'],   '糖':['米','riz'],      '包':['勹','envelopper'],
  '饺':['饣','aliment'],   '饼':['饣','aliment'],  '饮':['饣','aliment'],
  '料':['斗','boisseau'],  '酒':['氵','eau'],      '咖':['口','bouche'],
  '啡':['口','bouche'],    '汁':['氵','eau'],      '牛':['牛','bœuf'],
  '鸡':['鸟','oiseau'],    '猪':['犭','animal'],   '羊':['羊','mouton'],
  '虾':['虫','insecte'],   '葡':['艹','plante'],   '萄':['艹','plante'],
  '西':['西','ouest'],     '冰':['冫','glace'],    '啤':['口','bouche'],
  '酸':['酉','alcool'],    '辣':['辛','âcre'],     '甜':['甘','doux'],
  '苦':['艹','plante'],    '咸':['戊','armure'],

  // ── Nature ───────────────────────────────────
  '山':['山','montagne'],  '河':['氵','eau'],      '海':['氵','eau'],
  '天':['大','grand'],     '地':['土','terre'],    '风':['风','vent'],
  '雨':['雨','pluie'],     '雪':['雨','pluie'],    '云':['二','deux'],
  '花':['艹','plante'],    '草':['艹','plante'],   '树':['木','bois'],
  '叶':['口','bouche'],    '石':['石','pierre'],   '火':['火','feu'],
  '月':['月','lune'],      '星':['日','soleil'],   '阳':['阝','colline'],
  '阴':['阝','colline'],   '湖':['氵','eau'],      '江':['氵','eau'],
  '池':['氵','eau'],       '岸':['山','montagne'], '森':['木','bois'],
  '林':['木','bois'],      '田':['田','champ'],    '土':['土','terre'],
  '日':['日','soleil'],    '光':['儿','enfant'],   '热':['灬','feu'],

  // ── Objets quotidiens ────────────────────────
  '书':['乙','crochet'],   '本':['木','bois'],     '笔':['⺮','bambou'],
  '纸':['纟','fil'],       '桌':['木','bois'],     '椅':['木','bois'],
  '床':['广','toit'],      '门':['门','porte'],    '窗':['穴','caverne'],
  '灯':['火','feu'],       '话':['讠','parole'],   '视':['礻','montrer'],
  '脑':['月','lune'],      '机':['木','bois'],     '车':['车','voiture'],
  '船':['舟','bateau'],    '钱':['钅','métal'],    '票':['示','montrer'],
  '衣':['衣','vêtement'],  '服':['月','lune'],     '裤':['衤','vêtement'],
  '裙':['衤','vêtement'],  '鞋':['革','cuir'],     '帽':['巾','tissu'],
  '钟':['钅','métal'],     '表':['衣','vêtement'], '镜':['钅','métal'],
  '杯':['木','bois'],      '碗':['石','pierre'],   '盘':['皿','récipient'],
  '刀':['刀','couteau'],   '锅':['钅','métal'],    '药':['艹','plante'],
  '球':['王','roi'],       '伞':['人','personne'], '袋':['衣','vêtement'],
  '柜':['木','bois'],      '箱':['⺮','bambou'],   '瓶':['瓦','tuile'],
  '盒':['皿','récipient'], '钥':['钅','métal'],    '匙':['匕','cuillère'],
  '扇':['户','porte'],     '墙':['土','terre'],    '地':['土','terre'],
  '板':['木','bois'],      '梯':['木','bois'],

  // ── Lieux ────────────────────────────────────
  '国':['囗','enclos'],    '城':['土','terre'],    '市':['巾','tissu'],
  '区':['匸','cache'],     '路':['⻊','pied'],     '街':['行','aller'],
  '楼':['木','bois'],      '站':['立','debout'],   '园':['囗','enclos'],
  '公':['八','huit'],      '里':['里','village'],  '外':['夕','soir'],
  '店':['广','toit'],      '馆':['饣','aliment'],  '场':['土','terre'],
  '校':['木','bois'],      '室':['宀','maison'],   '房':['户','porte'],
  '间':['门','porte'],     '院':['阝','colline'],  '医':['匸','cache'],
  '图':['囗','enclos'],    '书':['乙','crochet'],  '超':['走','marcher'],
  '市':['巾','tissu'],     '餐':['食','nourriture'],'厅':['广','toit'],
  '厨':['广','toit'],      '卧':['臣','ministre'], '客':['宀','maison'],
  '厕':['广','toit'],      '所':['户','porte'],    '银':['钅','métal'],
  '行':['行','aller'],     '邮':['阝','colline'],  '局':['尸','corps'],
  '港':['氵','eau'],       '机':['木','bois'],

  // ── Temps ────────────────────────────────────
  '年':['干','sec'],       '月':['月','lune'],     '日':['日','soleil'],
  '时':['日','soleil'],    '分':['刀','couteau'],  '秒':['禾','céréale'],
  '今':['人','personne'],  '昨':['日','soleil'],   '明':['日','soleil'],
  '早':['日','soleil'],    '晚':['日','soleil'],   '午':['十','dix'],
  '前':['刂','couteau'],   '后':['口','bouche'],   '周':['口','bouche'],
  '期':['月','lune'],      '春':['日','soleil'],   '夏':['夊','pied'],
  '秋':['禾','céréale'],   '冬':['夂','pied'],     '刻':['刂','couteau'],
  '假':['亻','personne'],  '节':['⺮','bambou'],   '号':['口','bouche'],

  // ── Verbes courants ───────────────────────────
  '来':['木','bois'],      '去':['厶','privé'],    '说':['讠','parole'],
  '看':['目','œil'],       '听':['口','bouche'],   '吃':['口','bouche'],
  '喝':['口','bouche'],    '写':['冖','couvercle'],'读':['讠','parole'],
  '学':['子','enfant'],    '买':['乙','crochet'],  '卖':['十','dix'],
  '打':['扌','main'],      '走':['走','marcher'],  '跑':['⻊','pied'],
  '坐':['土','terre'],     '睡':['目','œil'],      '起':['走','marcher'],
  '想':['心','cœur'],      '知':['矢','flèche'],   '道':['辶','chemin'],
  '觉':['见','voir'],      '叫':['口','bouche'],   '问':['门','porte'],
  '答':['⺮','bambou'],    '请':['讠','parole'],   '谢':['讠','parole'],
  '认':['讠','parole'],    '识':['讠','parole'],   '做':['亻','personne'],
  '住':['亻','personne'],  '到':['刂','couteau'],  '让':['讠','parole'],
  '给':['纟','fil'],       '用':['用','utiliser'], '把':['扌','main'],
  '玩':['王','roi'],       '唱':['口','bouche'],   '画':['田','champ'],
  '找':['扌','main'],      '帮':['巾','tissu'],    '带':['巾','tissu'],
  '教':['攴','frapper'],   '等':['⺮','bambou'],   '拿':['手','main'],
  '放':['攴','frapper'],   '换':['扌','main'],     '洗':['氵','eau'],
  '游':['氵','eau'],       '飞':['飞','voler'],    '骑':['马','cheval'],
  '开':['廾','deux mains'],'关':['关','fermer'],  '回':['囗','enclos'],
  '进':['辶','chemin'],    '出':['凵','récipient'],'送':['辶','chemin'],
  '跟':['⻊','pied'],      '借':['亻','personne'], '喜':['口','bouche'],
  '欢':['欠','manquer'],   '爱':['爪','griffe'],   '恨':['忄','cœur'],
  '哭':['口','bouche'],    '笑':['⺮','bambou'],   '说':['讠','parole'],
  '告':['口','bouche'],    '诉':['讠','parole'],   '问':['门','porte'],
  '回':['囗','enclos'],    '答':['⺮','bambou'],   '选':['辶','chemin'],
  '择':['扌','main'],      '决':['冫','glace'],    '定':['宀','maison'],
  '解':['角','corne'],     '决':['冫','glace'],    '帮':['巾','tissu'],
  '忘':['心','cœur'],      '记':['讠','parole'],   '练':['纟','fil'],
  '习':['羽','plume'],     '复':['彳','pas'],      '预':['页','page'],
  '准':['冫','glace'],     '备':['人','personne'], '参':['厶','privé'],
  '加':['力','force'],     '参':['厶','privé'],    '加':['力','force'],
  '休':['亻','personne'],  '息':['心','cœur'],     '睡':['目','œil'],
  '觉':['见','voir'],      '起':['走','marcher'],  '床':['广','toit'],

  // ── Adjectifs ────────────────────────────────
  '大':['大','grand'],     '小':['小','petit'],    '多':['夕','soir'],
  '少':['小','petit'],     '长':['长','long'],     '短':['矢','flèche'],
  '高':['高','haut'],      '低':['亻','personne'], '新':['斤','hache'],
  '旧':['臼','mortier'],   '快':['忄','cœur'],     '慢':['忄','cœur'],
  '冷':['冫','glace'],     '美':['羊','mouton'],   '贵':['贝','coquillage'],
  '难':['又','main'],      '容':['宀','maison'],   '易':['日','soleil'],
  '忙':['忄','cœur'],      '闲':['门','porte'],    '累':['糸','fil'],
  '渴':['氵','eau'],       '饿':['饣','aliment'],  '胖':['月','lune'],
  '瘦':['疒','maladie'],   '矮':['矢','flèche'],   '帅':['巾','tissu'],
  '漂':['氵','eau'],       '亮':['亠','couvercle'],'干':['干','sec'],
  '净':['氵','eau'],       '脏':['月','lune'],     '重':['里','village'],
  '轻':['车','voiture'],   '满':['氵','eau'],      '空':['穴','caverne'],
  '安':['宀','maison'],    '静':['青','bleu'],     '乱':['乙','crochet'],
  '苦':['艹','plante'],    '甜':['甘','doux'],     '辣':['辛','âcre'],
  '鲜':['鱼','poisson'],   '香':['禾','céréale'],  '臭':['自','soi'],
  '软':['车','voiture'],   '硬':['石','pierre'],   '圆':['囗','enclos'],
  '方':['方','carré'],     '平':['干','sec'],      '直':['目','œil'],
  '弯':['弓','arc'],       '厚':['厂','falaise'],  '薄':['艹','plante'],

  // ── Couleurs ─────────────────────────────────
  '红':['纟','fil'],       '绿':['纟','fil'],      '蓝':['艹','plante'],
  '黄':['黄','jaune'],     '白':['白','blanc'],    '黑':['黑','noir'],
  '灰':['火','feu'],       '粉':['米','riz'],      '紫':['糸','fil'],
  '棕':['木','bois'],

  // ── Nombres & mesures ────────────────────────
  '一':['一','un'],        '二':['二','deux'],     '三':['一','un'],
  '四':['囗','enclos'],    '五':['二','deux'],     '六':['八','huit'],
  '七':['一','un'],        '八':['八','huit'],     '九':['乙','crochet'],
  '十':['十','dix'],       '百':['白','blanc'],    '千':['十','dix'],
  '万':['一','un'],        '零':['雨','pluie'],    '两':['入','entrer'],
  '半':['十','dix'],       '第':['⺮','bambou'],   '次':['欠','manquer'],
  '些':['二','deux'],      '每':['毋','mère'],     '各':['口','bouche'],

  // ── École & apprentissage ─────────────────────
  '语':['讠','parole'],    '文':['文','écriture'],  '数':['攴','frapper'],
  '英':['艹','plante'],    '汉':['氵','eau'],      '字':['宀','maison'],
  '词':['讠','parole'],    '句':['口','bouche'],   '课':['讠','parole'],
  '题':['页','page'],      '试':['讠','parole'],   '考':['老','vieux'],
  '作':['亻','personne'],  '业':['一','un'],       '练':['纟','fil'],
  '老':['老','vieux'],     '师':['巾','tissu'],    '生':['生','naître'],
  '同':['囗','enclos'],    '班':['刂','couteau'],  '级':['纟','fil'],
  '成':['戈','lance'],     '绩':['纟','fil'],      '分':['刀','couteau'],
  '数':['攴','frapper'],   '学':['子','enfant'],   '校':['木','bois'],

  // ── Sports & loisirs ─────────────────────────
  '球':['王','roi'],       '足':['⻊','pied'],     '篮':['⺮','bambou'],
  '网':['网','filet'],     '跳':['⻊','pied'],     '舞':['舛','erreur'],
  '音':['音','son'],       '乐':['木','bois'],     '钢':['钅','métal'],
  '琴':['王','roi'],       '影':['彡','poils'],    '戏':['戈','lance'],
  '画':['田','champ'],     '跑':['⻊','pied'],     '游':['氵','eau'],
  '泳':['氵','eau'],       '步':['止','arrêter'],  '拍':['扌','main'],
  '照':['日','soleil'],    '片':['片','planche'],  '旅':['方','carré'],
  '行':['行','aller'],     '游':['氵','eau'],      '览':['见','voir'],

  // ── Transports ───────────────────────────────
  '车':['车','voiture'],   '公':['八','huit'],     '共':['八','huit'],
  '汽':['氵','eau'],       '出':['凵','récipient'],'租':['禾','céréale'],
  '地':['土','terre'],     '铁':['钅','métal'],    '火':['火','feu'],
  '路':['⻊','pied'],      '飞':['飞','voler'],    '机':['木','bois'],
  '船':['舟','bateau'],    '骑':['马','cheval'],   '自':['自','soi'],
  '行':['行','aller'],     '摩':['手','main'],     '托':['扌','main'],

  // ── Santé ────────────────────────────────────
  '病':['疒','maladie'],   '医':['匸','cache'],    '院':['阝','colline'],
  '头':['大','grand'],     '疼':['疒','maladie'],  '痛':['疒','maladie'],
  '感':['心','cœur'],      '冒':['日','soleil'],   '发':['又','main'],
  '烧':['火','feu'],       '咳':['口','bouche'],   '嗽':['口','bouche'],
  '药':['艹','plante'],    '打':['扌','main'],     '针':['钅','métal'],
  '健':['亻','personne'],  '康':['广','toit'],     '身':['身','corps'],
  '体':['亻','personne'],  '重':['里','village'],
};

// ════════════════════════════════════════════════
// EXEMPLES — phrases d'exemple par mot (hanzi → {zh, py, fr})
// ════════════════════════════════════════════════
var EXAMPLES = {
  // ── Salutations ──────────────────────────────
  "你好":  {zh:"你好，认识你很高兴！",       py:"Nǐ hǎo, rèn shi nǐ hěn gāo xìng!",    fr:"Bonjour, ravi de te connaître !"},
  "谢谢":  {zh:"谢谢你帮助我。",             py:"Xiè xie nǐ bāng zhù wǒ.",              fr:"Merci de m'avoir aidé."},
  "再见":  {zh:"再见，明天见！",             py:"Zài jiàn, míng tiān jiàn!",            fr:"Au revoir, à demain !"},
  "对不起":{zh:"对不起，我迟到了。",          py:"Duì bu qǐ, wǒ chí dào le.",            fr:"Désolé, je suis en retard."},
  "不客气":{zh:"不客气，这是我应该做的。",    py:"Bù kè qi, zhè shì wǒ yīng gāi zuò de.",fr:"De rien, c'est normal."},
  "没关系":{zh:"没关系，不要担心。",          py:"Méi guān xi, bù yào dān xīn.",         fr:"Ce n'est pas grave, ne t'inquiète pas."},
  // ── Pronoms ──────────────────────────────────
  "我":    {zh:"我是法国人，我学中文。",       py:"Wǒ shì Fǎ guó rén, wǒ xué Zhōng wén.",fr:"Je suis Français, j'apprends le chinois."},
  "你":    {zh:"你叫什么名字？",             py:"Nǐ jiào shén me míng zi?",             fr:"Comment tu t'appelles ?"},
  "他":    {zh:"他是我的好朋友。",            py:"Tā shì wǒ de hǎo péng you.",           fr:"Il est mon bon ami."},
  "她":    {zh:"她是我的老师。",             py:"Tā shì wǒ de lǎo shī.",               fr:"Elle est mon professeur."},
  "我们":  {zh:"我们一起去学校。",            py:"Wǒ men yī qǐ qù xué xiào.",           fr:"Nous allons ensemble à l'école."},
  "你们":  {zh:"你们吃饭了吗？",             py:"Nǐ men chī fàn le ma?",               fr:"Avez-vous mangé ?"},
  "他们":  {zh:"他们都是我的同学。",          py:"Tā men dōu shì wǒ de tóng xué.",      fr:"Ils sont tous mes camarades de classe."},
  // ── Famille ──────────────────────────────────
  "爸爸":  {zh:"我爸爸是医生。",             py:"Wǒ bà ba shì yī shēng.",              fr:"Mon papa est médecin."},
  "妈妈":  {zh:"妈妈在家做饭。",             py:"Mā ma zài jiā zuò fàn.",              fr:"Maman cuisine à la maison."},
  "哥哥":  {zh:"我哥哥比我高。",             py:"Wǒ gē ge bǐ wǒ gāo.",                fr:"Mon grand frère est plus grand que moi."},
  "姐姐":  {zh:"姐姐喜欢唱歌。",             py:"Jiě jie xǐ huān chàng gē.",           fr:"Ma grande sœur aime chanter."},
  "弟弟":  {zh:"弟弟今年六岁。",             py:"Dì di jīn nián liù suì.",             fr:"Mon petit frère a six ans cette année."},
  "妹妹":  {zh:"妹妹很可爱。",               py:"Mèi mei hěn kě ài.",                  fr:"Ma petite sœur est très mignonne."},
  // ── Personnes ────────────────────────────────
  "老师":  {zh:"老师教我们中文。",            py:"Lǎo shī jiāo wǒ men Zhōng wén.",      fr:"Le professeur nous enseigne le chinois."},
  "同学":  {zh:"他是我的同学，也是朋友。",    py:"Tā shì wǒ de tóng xué, yě shì péng you.",fr:"Il est mon camarade de classe et aussi mon ami."},
  "朋友":  {zh:"她是我最好的朋友。",          py:"Tā shì wǒ zuì hǎo de péng you.",      fr:"Elle est ma meilleure amie."},
  // ── Animaux ──────────────────────────────────
  "猫":    {zh:"这只猫很可爱。",             py:"Zhè zhī māo hěn kě ài.",              fr:"Ce chat est très mignon."},
  "狗":    {zh:"我家有一只大狗。",            py:"Wǒ jiā yǒu yī zhī dà gǒu.",          fr:"J'ai un grand chien à la maison."},
  "鱼":    {zh:"水里有很多鱼。",             py:"Shuǐ lǐ yǒu hěn duō yú.",            fr:"Il y a beaucoup de poissons dans l'eau."},
  "马":    {zh:"那匹马跑得很快。",            py:"Nà pǐ mǎ pǎo de hěn kuài.",          fr:"Ce cheval court très vite."},
  // ── Nourriture ───────────────────────────────
  "苹果":  {zh:"我每天吃一个苹果。",          py:"Wǒ měi tiān chī yī gè píng guǒ.",    fr:"Je mange une pomme chaque jour."},
  "水":    {zh:"请给我一杯水。",             py:"Qǐng gěi wǒ yī bēi shuǐ.",           fr:"Donnez-moi un verre d'eau, s'il vous plaît."},
  "米饭":  {zh:"中国人每天吃米饭。",          py:"Zhōng guó rén měi tiān chī mǐ fàn.",  fr:"Les Chinois mangent du riz tous les jours."},
  "面条":  {zh:"我喜欢吃面条。",             py:"Wǒ xǐ huān chī miàn tiáo.",          fr:"J'aime manger des nouilles."},
  "好吃":  {zh:"这个菜很好吃！",             py:"Zhè gè cài hěn hǎo chī!",            fr:"Ce plat est délicieux !"},
  // ── Adjectifs ────────────────────────────────
  "大":    {zh:"北京是一个很大的城市。",      py:"Běi jīng shì yī gè hěn dà de chéng shì.",fr:"Pékin est une très grande ville."},
  "小":    {zh:"这个盒子太小了。",            py:"Zhè gè hé zi tài xiǎo le.",          fr:"Cette boîte est trop petite."},
  "好":    {zh:"你好吗？我很好，谢谢！",      py:"Nǐ hǎo ma? Wǒ hěn hǎo, xiè xie!",   fr:"Comment vas-tu ? Je vais très bien, merci !"},
  "多":    {zh:"今天来了很多人。",            py:"Jīn tiān lái le hěn duō rén.",       fr:"Beaucoup de gens sont venus aujourd'hui."},
  "高兴":  {zh:"我很高兴见到你们。",          py:"Wǒ hěn gāo xìng jiàn dào nǐ men.",  fr:"Je suis content de vous voir."},
  "漂亮":  {zh:"她的裙子很漂亮。",            py:"Tā de qún zi hěn piào liang.",       fr:"Sa robe est très jolie."},
  "高":    {zh:"这栋楼很高。",               py:"Zhè dòng lóu hěn gāo.",              fr:"Cet immeuble est très haut."},
  // ── Temps ────────────────────────────────────
  "今天":  {zh:"今天天气很好，我们去公园吧。",py:"Jīn tiān tiān qì hěn hǎo, wǒ men qù gōng yuán ba.",fr:"Il fait beau aujourd'hui, allons au parc."},
  "明天":  {zh:"明天我有考试。",             py:"Míng tiān wǒ yǒu kǎo shì.",          fr:"Demain j'ai un examen."},
  "昨天":  {zh:"昨天我们去看电影了。",        py:"Zuó tiān wǒ men qù kàn diàn yǐng le.",fr:"Hier nous sommes allés voir un film."},
  "年":    {zh:"今年是哪一年？",             py:"Jīn nián shì nǎ yī nián?",           fr:"Quelle année sommes-nous ?"},
  "月":    {zh:"这个月有三十天。",            py:"Zhè gè yuè yǒu sān shí tiān.",       fr:"Ce mois a trente jours."},
  "星期":  {zh:"一个星期有七天。",            py:"Yī gè xīng qī yǒu qī tiān.",        fr:"Une semaine a sept jours."},
  // ── Verbes ───────────────────────────────────
  "去":    {zh:"我们去学校上课。",            py:"Wǒ men qù xué xiào shàng kè.",       fr:"Nous allons à l'école en cours."},
  "来":    {zh:"他从中国来。",               py:"Tā cóng Zhōng guó lái.",             fr:"Il vient de Chine."},
  "看":    {zh:"我喜欢看书。",               py:"Wǒ xǐ huān kàn shū.",               fr:"J'aime lire des livres."},
  "吃":    {zh:"你喜欢吃什么？",             py:"Nǐ xǐ huān chī shén me?",           fr:"Qu'est-ce que tu aimes manger ?"},
  "喝":    {zh:"天热，多喝水。",             py:"Tiān rè, duō hē shuǐ.",              fr:"Il fait chaud, bois beaucoup d'eau."},
  "说":    {zh:"他能说三种语言。",            py:"Tā néng shuō sān zhǒng yǔ yán.",    fr:"Il peut parler trois langues."},
  "叫":    {zh:"我叫李明，你呢？",            py:"Wǒ jiào Lǐ Míng, nǐ ne?",           fr:"Je m'appelle Li Ming, et toi ?"},
  "有":    {zh:"我有两个弟弟。",             py:"Wǒ yǒu liǎng gè dì di.",            fr:"J'ai deux petits frères."},
  "没有":  {zh:"我没有手机。",               py:"Wǒ méi yǒu shǒu jī.",               fr:"Je n'ai pas de téléphone portable."},
  "是":    {zh:"这是我的书包。",             py:"Zhè shì wǒ de shū bāo.",            fr:"C'est mon cartable."},
  "在":    {zh:"我在图书馆学习。",            py:"Wǒ zài tú shū guǎn xué xí.",        fr:"J'étudie à la bibliothèque."},
  "学":    {zh:"我们每天学新汉字。",          py:"Wǒ men měi tiān xué xīn Hàn zì.",   fr:"Nous apprenons de nouveaux caractères chaque jour."},
  // ── Questions ────────────────────────────────
  "什么":  {zh:"这是什么动物？",             py:"Zhè shì shén me dòng wù?",          fr:"Quel est cet animal ?"},
  "谁":    {zh:"那个人是谁？",               py:"Nà gè rén shì shéi?",               fr:"Qui est cette personne ?"},
  "多少":  {zh:"这个多少钱？",               py:"Zhè gè duō shao qián?",             fr:"Combien ça coûte ?"},
  // ── Démonstratifs ────────────────────────────
  "这":    {zh:"这是我的家。",               py:"Zhè shì wǒ de jiā.",                fr:"Voici ma maison."},
  "那":    {zh:"那个人是我的老师。",          py:"Nà gè rén shì wǒ de lǎo shī.",     fr:"Cette personne est mon professeur."},
  // ── Lieu ─────────────────────────────────────
  "学校":  {zh:"我们的学校很大，有很多学生。",py:"Wǒ men de xué xiào hěn dà, yǒu hěn duō xué shēng.",fr:"Notre école est grande et accueille beaucoup d'élèves."},
  "家":    {zh:"放学后我回家。",             py:"Fàng xué hòu wǒ huí jiā.",          fr:"Je rentre à la maison après l'école."},
  "中国":  {zh:"中国有很多名胜古迹。",        py:"Zhōng guó yǒu hěn duō míng shèng gǔ jì.",fr:"La Chine a de nombreux sites historiques."},
  // ── Divers ───────────────────────────────────
  "喜欢":  {zh:"我喜欢学中文，也喜欢吃中国菜。",py:"Wǒ xǐ huān xué Zhōng wén, yě xǐ huān chī Zhōng guó cài.",fr:"J'aime apprendre le chinois et manger de la cuisine chinoise."},
  "汉语":  {zh:"我在学校学汉语。",            py:"Wǒ zài xué xiào xué Hàn yǔ.",      fr:"J'apprends le chinois à l'école."},
  "书":    {zh:"这本书很有意思。",            py:"Zhè běn shū hěn yǒu yì si.",       fr:"Ce livre est très intéressant."},
  "人":    {zh:"这里有很多人。",             py:"Zhè lǐ yǒu hěn duō rén.",          fr:"Il y a beaucoup de gens ici."},
  "朋友":  {zh:"她是我最好的朋友。",          py:"Tā shì wǒ zuì hǎo de péng you.",   fr:"Elle est ma meilleure amie."},
};
