var APP_VERSION = '1.0.1';

var EXAMPLES = {

// ── YCT 1 ──────────────────────────────────────────────────────────────────
"你好":    {zh:"你好，我叫小明。",         py:"Nǐ hǎo, wǒ jiào Xiǎo Míng.",       fr:"Bonjour, je m'appelle Xiao Ming."},
"谢谢":    {zh:"谢谢你帮助我。",           py:"Xiè xie nǐ bāng zhù wǒ.",          fr:"Merci de m'avoir aidé."},
"再见":    {zh:"明天见，再见！",           py:"Míng tiān jiàn, zài jiàn!",         fr:"À demain, au revoir !"},
"对不起":  {zh:"对不起，我来晚了。",       py:"Duì bu qǐ, wǒ lái wǎn le.",        fr:"Pardon, je suis en retard."},
"不客气":  {zh:"谢谢你！——不客气。",      py:"Xiè xie nǐ! — Bù kè qi.",          fr:"Merci ! — De rien."},
"没关系":  {zh:"没关系，不要担心。",       py:"Méi guān xi, bú yào dān xīn.",     fr:"Ce n'est pas grave, ne t'inquiète pas."},
"我":      {zh:"我是学生。",               py:"Wǒ shì xué shēng.",                 fr:"Je suis étudiant."},
"你":      {zh:"你叫什么名字？",           py:"Nǐ jiào shén me míng zi?",          fr:"Comment tu t'appelles ?"},
"他":      {zh:"他是我的老师。",           py:"Tā shì wǒ de lǎo shī.",             fr:"Il est mon professeur."},
"她":      {zh:"她很漂亮。",               py:"Tā hěn piào liang.",                fr:"Elle est très belle."},
"我们":    {zh:"我们一起去学校。",         py:"Wǒ men yī qǐ qù xué xiào.",        fr:"Nous allons à l'école ensemble."},
"你们":    {zh:"你们都是朋友吗？",         py:"Nǐ men dōu shì péng you ma?",      fr:"Vous êtes tous amis ?"},
"他们":    {zh:"他们在公园玩。",           py:"Tā men zài gōng yuán wán.",         fr:"Ils jouent dans le parc."},
"零":      {zh:"今天气温是零度。",         py:"Jīn tiān qì wēn shì líng dù.",     fr:"La température est zéro degré aujourd'hui."},
"一":      {zh:"我有一只猫。",             py:"Wǒ yǒu yī zhī māo.",               fr:"J'ai un chat."},
"二":      {zh:"我有二个苹果。",           py:"Wǒ yǒu èr gè píng guǒ.",           fr:"J'ai deux pommes."},
"三":      {zh:"我家有三口人。",           py:"Wǒ jiā yǒu sān kǒu rén.",          fr:"Il y a trois personnes dans ma famille."},
"四":      {zh:"桌子上有四本书。",         py:"Zhuō zi shàng yǒu sì běn shū.",    fr:"Il y a quatre livres sur la table."},
"五":      {zh:"我今年五岁。",             py:"Wǒ jīn nián wǔ suì.",              fr:"J'ai cinq ans cette année."},
"六":      {zh:"我们班有六个同学。",       py:"Wǒ men bān yǒu liù gè tóng xué.", fr:"Il y a six camarades dans notre classe."},
"七":      {zh:"一个星期有七天。",         py:"Yī gè xīng qī yǒu qī tiān.",      fr:"Une semaine a sept jours."},
"八":      {zh:"他有八本书。",             py:"Tā yǒu bā běn shū.",               fr:"Il a huit livres."},
"九":      {zh:"九月是秋天。",             py:"Jiǔ yuè shì qiū tiān.",            fr:"Septembre, c'est l'automne."},
"十":      {zh:"我有十个朋友。",           py:"Wǒ yǒu shí gè péng you.",          fr:"J'ai dix amis."},
"百":      {zh:"这本书有一百页。",         py:"Zhè běn shū yǒu yī bǎi yè.",      fr:"Ce livre a cent pages."},
"千":      {zh:"这件衣服要一千块。",       py:"Zhè jiàn yī fu yào yī qiān kuài.",fr:"Ce vêtement coûte mille yuans."},
"爸爸":    {zh:"我爸爸每天去工作。",       py:"Wǒ bà ba měi tiān qù gōng zuò.",  fr:"Mon papa va travailler tous les jours."},
"妈妈":    {zh:"妈妈在厨房做饭。",         py:"Māma zài chú fáng zuò fàn.",       fr:"Maman fait la cuisine dans la cuisine."},
"哥哥":    {zh:"我哥哥比我高。",           py:"Wǒ gē ge bǐ wǒ gāo.",             fr:"Mon grand frère est plus grand que moi."},
"姐姐":    {zh:"我姐姐很漂亮。",           py:"Wǒ jiě jie hěn piào liang.",       fr:"Ma grande sœur est très belle."},
"弟弟":    {zh:"我弟弟喜欢踢足球。",       py:"Wǒ dì di xǐ huān tī zú qiú.",     fr:"Mon petit frère aime jouer au football."},
"妹妹":    {zh:"妹妹今年八岁。",           py:"Mèi mei jīn nián bā suì.",         fr:"Ma petite sœur a huit ans cette année."},
"老师":    {zh:"我们的老师很好。",         py:"Wǒ men de lǎo shī hěn hǎo.",      fr:"Notre professeur est très bien."},
"同学":    {zh:"我和同学一起学习。",       py:"Wǒ hé tóng xué yī qǐ xué xí.",    fr:"J'étudie avec mes camarades de classe."},
"朋友":    {zh:"他是我最好的朋友。",       py:"Tā shì wǒ zuì hǎo de péng you.",  fr:"Il est mon meilleur ami."},
"猫":      {zh:"这只猫很可爱。",           py:"Zhè zhī māo hěn kě ài.",           fr:"Ce chat est très mignon."},
"狗":      {zh:"那只狗叫得很大声。",       py:"Nà zhī gǒu jiào de hěn dà shēng.",fr:"Ce chien aboie très fort."},
"鸟":      {zh:"树上有一只鸟。",           py:"Shù shàng yǒu yī zhī niǎo.",      fr:"Il y a un oiseau sur l'arbre."},
"鱼":      {zh:"我喜欢吃鱼。",             py:"Wǒ xǐ huān chī yú.",              fr:"J'aime manger du poisson."},
"马":      {zh:"这匹马跑得很快。",         py:"Zhè pǐ mǎ pǎo de hěn kuài.",     fr:"Ce cheval court très vite."},
"苹果":    {zh:"我每天吃一个苹果。",       py:"Wǒ měi tiān chī yī gè píng guǒ.",fr:"Je mange une pomme chaque jour."},
"水":      {zh:"请给我一杯水。",           py:"Qǐng gěi wǒ yī bēi shuǐ.",        fr:"Donne-moi un verre d'eau s'il te plaît."},
"米饭":    {zh:"我中午吃米饭。",           py:"Wǒ zhōng wǔ chī mǐ fàn.",         fr:"Je mange du riz à midi."},
"面条":    {zh:"这碗面条很好吃。",         py:"Zhè wǎn miàn tiáo hěn hǎo chī.", fr:"Ce bol de nouilles est délicieux."},
"好吃":    {zh:"妈妈做的菜很好吃。",       py:"Māma zuò de cài hěn hǎo chī.",    fr:"Les plats cuisinés par maman sont délicieux."},
"大":      {zh:"这个苹果很大。",           py:"Zhè gè píng guǒ hěn dà.",         fr:"Cette pomme est très grande."},
"小":      {zh:"我的书包很小。",           py:"Wǒ de shū bāo hěn xiǎo.",         fr:"Mon cartable est très petit."},
"好":      {zh:"今天天气很好。",           py:"Jīn tiān tiān qì hěn hǎo.",        fr:"Il fait beau aujourd'hui."},
"多":      {zh:"这里有很多花。",           py:"Zhè lǐ yǒu hěn duō huā.",          fr:"Il y a beaucoup de fleurs ici."},
"高兴":    {zh:"我今天很高兴。",           py:"Wǒ jīn tiān hěn gāo xìng.",       fr:"Je suis très content aujourd'hui."},
"漂亮":    {zh:"她的裙子很漂亮。",         py:"Tā de qún zi hěn piào liang.",     fr:"Sa robe est très belle."},
"高":      {zh:"那座山很高。",             py:"Nà zuò shān hěn gāo.",             fr:"Cette montagne est très haute."},
"今天":    {zh:"今天是我的生日。",         py:"Jīn tiān shì wǒ de shēng rì.",     fr:"Aujourd'hui c'est mon anniversaire."},
"明天":    {zh:"明天我去看医生。",         py:"Míng tiān wǒ qù kàn yī shēng.",    fr:"Demain je vais voir le médecin."},
"昨天":    {zh:"昨天我们去公园了。",       py:"Zuó tiān wǒ men qù gōng yuán le.",fr:"Hier nous sommes allés au parc."},
"年":      {zh:"今年是二〇二五年。",       py:"Jīn nián shì èr líng èr wǔ nián.",fr:"Cette année, c'est 2025."},
"月":      {zh:"一年有十二个月。",         py:"Yī nián yǒu shí èr gè yuè.",      fr:"Il y a douze mois dans une année."},
"日":      {zh:"今天是三月一日。",         py:"Jīn tiān shì sān yuè yī rì.",      fr:"Aujourd'hui c'est le premier mars."},
"星期":    {zh:"这个星期我很忙。",         py:"Zhè gè xīng qī wǒ hěn máng.",     fr:"Cette semaine je suis très occupé."},
"去":      {zh:"我去学校上课。",           py:"Wǒ qù xué xiào shàng kè.",         fr:"Je vais à l'école suivre des cours."},
"来":      {zh:"请你来我家。",             py:"Qǐng nǐ lái wǒ jiā.",              fr:"Viens chez moi s'il te plaît."},
"看":      {zh:"我喜欢看书。",             py:"Wǒ xǐ huān kàn shū.",              fr:"J'aime lire des livres."},
"吃":      {zh:"我们一起吃饭吧。",         py:"Wǒ men yī qǐ chī fàn ba.",         fr:"Mangeons ensemble."},
"喝":      {zh:"天热的时候多喝水。",       py:"Tiān rè de shí hou duō hē shuǐ.",  fr:"Bois beaucoup d'eau quand il fait chaud."},
"说":      {zh:"他说汉语说得很好。",       py:"Tā shuō Hàn yǔ shuō de hěn hǎo.", fr:"Il parle très bien le chinois."},
"叫":      {zh:"我叫李明。",               py:"Wǒ jiào Lǐ Míng.",                 fr:"Je m'appelle Li Ming."},
"有":      {zh:"我有一本新书。",           py:"Wǒ yǒu yī běn xīn shū.",           fr:"J'ai un nouveau livre."},
"没有":    {zh:"我没有哥哥。",             py:"Wǒ méi yǒu gē ge.",                fr:"Je n'ai pas de grand frère."},
"是":      {zh:"这是我的书。",             py:"Zhè shì wǒ de shū.",               fr:"C'est mon livre."},
"在":      {zh:"我在图书馆学习。",         py:"Wǒ zài tú shū guǎn xué xí.",      fr:"J'étudie à la bibliothèque."},
"学":      {zh:"我在学汉语。",             py:"Wǒ zài xué Hàn yǔ.",              fr:"J'apprends le chinois."},
"什么":    {zh:"你在做什么？",             py:"Nǐ zài zuò shén me?",              fr:"Qu'est-ce que tu fais ?"},
"谁":      {zh:"那个人是谁？",             py:"Nà gè rén shì shéi?",              fr:"Qui est cette personne ?"},
"哪":      {zh:"你是哪国人？",             py:"Nǐ shì nǎ guó rén?",              fr:"De quel pays es-tu ?"},
"几":      {zh:"你家有几口人？",           py:"Nǐ jiā yǒu jǐ kǒu rén?",          fr:"Combien de personnes y a-t-il dans ta famille ?"},
"多少":    {zh:"这个多少钱？",             py:"Zhè gè duō shao qián?",            fr:"Combien ça coûte ?"},
"这":      {zh:"这是我的书包。",           py:"Zhè shì wǒ de shū bāo.",           fr:"C'est mon cartable."},
"那":      {zh:"那是什么动物？",           py:"Nà shì shén me dòng wù?",          fr:"Quel est cet animal ?"},
"不":      {zh:"我不喜欢吃辣的。",         py:"Wǒ bù xǐ huān chī là de.",         fr:"Je n'aime pas manger épicé."},
"书":      {zh:"这本书很有意思。",         py:"Zhè běn shū hěn yǒu yì si.",       fr:"Ce livre est très intéressant."},
"中国":    {zh:"我想去中国旅行。",         py:"Wǒ xiǎng qù Zhōng guó lǚ xíng.",  fr:"Je veux voyager en Chine."},

// ── YCT 2 ──────────────────────────────────────────────────────────────────
"学校":    {zh:"我每天去学校上课。",         py:"Wǒ měi tiān qù xué xiào shàng kè.",        fr:"Je vais à l'école suivre des cours tous les jours."},
"家":      {zh:"我家很大，很舒服。",         py:"Wǒ jiā hěn dà, hěn shū fu.",               fr:"Ma maison est grande et confortable."},
"医院":    {zh:"她每天在医院工作。",         py:"Tā měi tiān zài yī yuàn gōng zuò.",        fr:"Elle travaille à l'hôpital tous les jours."},
"商店":    {zh:"那家商店卖很多东西。",       py:"Nà jiā shāng diàn mài hěn duō dōng xi.",   fr:"Ce magasin vend beaucoup de choses."},
"公园":    {zh:"我们周末去公园玩。",         py:"Wǒ men zhōu mò qù gōng yuán wán.",         fr:"Nous allons jouer au parc le week-end."},
"饭馆":    {zh:"这家饭馆的菜很好吃。",       py:"Zhè jiā fàn guǎn de cài hěn hǎo chī.",    fr:"Les plats de ce restaurant sont délicieux."},
"教室":    {zh:"教室里有很多学生。",         py:"Jiào shì lǐ yǒu hěn duō xué shēng.",      fr:"Il y a beaucoup d'élèves dans la salle de classe."},
"超市":    {zh:"妈妈去超市买菜。",           py:"Māma qù chāo shì mǎi cài.",                fr:"Maman va au supermarché acheter des légumes."},
"喜欢":    {zh:"我很喜欢中国音乐。",         py:"Wǒ hěn xǐ huān Zhōng guó yīn yuè.",       fr:"J'aime beaucoup la musique chinoise."},
"想":      {zh:"他想去看电影。",             py:"Tā xiǎng qù kàn diàn yǐng.",              fr:"Il veut aller voir un film."},
"知道":    {zh:"我知道他住在哪里。",         py:"Wǒ zhī dào tā zhù zài nǎ lǐ.",            fr:"Je sais où il habite."},
"听":      {zh:"我喜欢听音乐。",             py:"Wǒ xǐ huān tīng yīn yuè.",                fr:"J'aime écouter de la musique."},
"写":      {zh:"他正在写作业。",             py:"Tā zhèng zài xiě zuò yè.",                 fr:"Il est en train de faire ses devoirs."},
"读":      {zh:"她每天读一本书。",           py:"Tā měi tiān dú yī běn shū.",              fr:"Elle lit un livre chaque jour."},
"做":      {zh:"我在做作业。",               py:"Wǒ zài zuò zuò yè.",                       fr:"Je fais mes devoirs."},
"玩":      {zh:"孩子们在院子里玩。",         py:"Hái zi men zài yuàn zi lǐ wán.",           fr:"Les enfants jouent dans la cour."},
"睡觉":    {zh:"我每天晚上十点睡觉。",       py:"Wǒ měi tiān wǎn shang shí diǎn shuì jiào.",fr:"Je dors tous les soirs à dix heures."},
"起床":    {zh:"我每天七点起床。",           py:"Wǒ měi tiān qī diǎn qǐ chuáng.",          fr:"Je me lève à sept heures tous les jours."},
"坐":      {zh:"请坐，不要站着。",           py:"Qǐng zuò, bú yào zhàn zhe.",              fr:"Assieds-toi, ne reste pas debout."},
"走":      {zh:"我们一起走回家吧。",         py:"Wǒ men yī qǐ zǒu huí jiā ba.",            fr:"Rentrons à pied ensemble."},
"买":      {zh:"我要去买一件新衣服。",       py:"Wǒ yào qù mǎi yī jiàn xīn yī fu.",        fr:"Je vais acheter un nouveau vêtement."},
"卖":      {zh:"这家店卖很多水果。",         py:"Zhè jiā diàn mài hěn duō shuǐ guǒ.",      fr:"Ce magasin vend beaucoup de fruits."},
"跑":      {zh:"他每天早上跑步。",           py:"Tā měi tiān zǎo shang pǎo bù.",            fr:"Il fait du jogging chaque matin."},
"站":      {zh:"请不要站在椅子上。",         py:"Qǐng bú yào zhàn zài yǐ zi shàng.",       fr:"Ne te mets pas debout sur la chaise s'il te plaît."},
"回":      {zh:"我晚上六点回家。",           py:"Wǒ wǎn shang liù diǎn huí jiā.",          fr:"Je rentre chez moi à six heures du soir."},
"唱":      {zh:"她唱歌唱得很好。",           py:"Tā chàng gē chàng de hěn hǎo.",           fr:"Elle chante très bien."},
"画":      {zh:"他喜欢画山水画。",           py:"Tā xǐ huān huà shān shuǐ huà.",           fr:"Il aime peindre des paysages."},
"打电话":  {zh:"我给妈妈打电话。",           py:"Wǒ gěi māma dǎ diàn huà.",                fr:"J'appelle maman au téléphone."},
"回答":    {zh:"老师的问题他都能回答。",     py:"Lǎo shī de wèn tí tā dōu néng huí dá.",   fr:"Il peut répondre à toutes les questions du professeur."},
"星期一":  {zh:"星期一我有数学课。",         py:"Xīng qī yī wǒ yǒu shù xué kè.",          fr:"J'ai cours de maths le lundi."},
"星期二":  {zh:"星期二我去游泳。",           py:"Xīng qī èr wǒ qù yóu yǒng.",             fr:"Je vais nager le mardi."},
"星期三":  {zh:"星期三下午没有课。",         py:"Xīng qī sān xià wǔ méi yǒu kè.",         fr:"Mercredi après-midi il n'y a pas cours."},
"星期四":  {zh:"星期四我学画画。",           py:"Xīng qī sì wǒ xué huà huà.",             fr:"J'apprends à dessiner le jeudi."},
"星期五":  {zh:"星期五是一周的最后一天。",   py:"Xīng qī wǔ shì yī zhōu de zuì hòu yī tiān.",fr:"Vendredi est le dernier jour de la semaine."},
"星期六":  {zh:"星期六我和家人去公园。",     py:"Xīng qī liù wǒ hé jiā rén qù gōng yuán.",fr:"Samedi je vais au parc avec ma famille."},
"星期天":  {zh:"星期天我在家休息。",         py:"Xīng qī tiān wǒ zài jiā xiū xi.",         fr:"Le dimanche je me repose à la maison."},
"早上":    {zh:"早上我吃面包喝牛奶。",       py:"Zǎo shang wǒ chī miàn bāo hē niú nǎi.",  fr:"Le matin je mange du pain et bois du lait."},
"上午":    {zh:"上午我在学校上课。",         py:"Shàng wǔ wǒ zài xué xiào shàng kè.",      fr:"Le matin (avant-midi) j'ai cours à l'école."},
"中午":    {zh:"中午我和同学一起吃饭。",     py:"Zhōng wǔ wǒ hé tóng xué yī qǐ chī fàn.", fr:"À midi je mange avec mes camarades."},
"下午":    {zh:"下午我去图书馆看书。",       py:"Xià wǔ wǒ qù tú shū guǎn kàn shū.",      fr:"L'après-midi je vais lire à la bibliothèque."},
"晚上":    {zh:"晚上我和家人一起看电视。",   py:"Wǎn shang wǒ hé jiā rén yī qǐ kàn diàn shì.",fr:"Le soir je regarde la télé avec ma famille."},
"现在":    {zh:"现在几点了？",               py:"Xiàn zài jǐ diǎn le?",                    fr:"Quelle heure est-il maintenant ?"},
"以前":    {zh:"以前我不会说汉语。",         py:"Yǐ qián wǒ bù huì shuō Hàn yǔ.",         fr:"Avant je ne savais pas parler chinois."},
"以后":    {zh:"以后我想去中国工作。",       py:"Yǐ hòu wǒ xiǎng qù Zhōng guó gōng zuò.", fr:"Après je voudrais aller travailler en Chine."},
"鸡蛋":    {zh:"早饭我吃了两个鸡蛋。",       py:"Zǎo fàn wǒ chī le liǎng gè jī dàn.",     fr:"J'ai mangé deux œufs au petit-déjeuner."},
"牛奶":    {zh:"我每天早上喝牛奶。",         py:"Wǒ měi tiān zǎo shang hē niú nǎi.",       fr:"Je bois du lait chaque matin."},
"茶":      {zh:"爷爷喜欢喝绿茶。",           py:"Yé ye xǐ huān hē lǜ chá.",               fr:"Grand-père aime boire du thé vert."},
"果汁":    {zh:"我喜欢喝橙子果汁。",         py:"Wǒ xǐ huān hē chéng zi guǒ zhī.",        fr:"J'aime boire du jus d'orange."},
"面包":    {zh:"早上我吃了一片面包。",       py:"Zǎo shang wǒ chī le yī piàn miàn bāo.",  fr:"Le matin j'ai mangé une tranche de pain."},
"饺子":    {zh:"春节我们吃饺子。",           py:"Chūn jié wǒ men chī jiǎo zi.",           fr:"Nous mangeons des raviolis pendant la Fête du Printemps."},
"肉":      {zh:"他不喜欢吃肉。",             py:"Tā bù xǐ huān chī ròu.",                  fr:"Il n'aime pas manger de viande."},
"蔬菜":    {zh:"多吃蔬菜对身体好。",         py:"Duō chī shū cài duì shēn tǐ hǎo.",        fr:"Manger beaucoup de légumes est bon pour la santé."},
"香蕉":    {zh:"猴子爱吃香蕉。",             py:"Hóu zi ài chī xiāng jiāo.",               fr:"Les singes adorent manger des bananes."},
"西瓜":    {zh:"夏天吃西瓜很解渴。",         py:"Xià tiān chī xī guā hěn jiě kě.",         fr:"Manger de la pastèque en été désaltère bien."},
"葡萄":    {zh:"这串葡萄又甜又大。",         py:"Zhè chuàn pú tao yòu tián yòu dà.",       fr:"Cette grappe de raisin est à la fois sucrée et grosse."},
"橙子":    {zh:"橙子富含维生素C。",           py:"Chéng zi fù hán wéi shēng sù C.",         fr:"Les oranges sont riches en vitamine C."},
"红色":    {zh:"她穿了一件红色的裙子。",     py:"Tā chuān le yī jiàn hóng sè de qún zi.",  fr:"Elle porte une robe rouge."},
"黄色":    {zh:"向日葵是黄色的。",           py:"Xiàng rì kuí shì huáng sè de.",           fr:"Les tournesols sont jaunes."},
"蓝色":    {zh:"天空是蓝色的。",             py:"Tiān kōng shì lán sè de.",                fr:"Le ciel est bleu."},
"绿色":    {zh:"草地是绿色的。",             py:"Cǎo dì shì lǜ sè de.",                    fr:"La prairie est verte."},
"白色":    {zh:"雪是白色的。",               py:"Xuě shì bái sè de.",                       fr:"La neige est blanche."},
"黑色":    {zh:"他穿了一件黑色的外套。",     py:"Tā chuān le yī jiàn hēi sè de wài tào.",  fr:"Il porte un manteau noir."},
"粉色":    {zh:"她喜欢粉色的花。",           py:"Tā xǐ huān fěn sè de huā.",               fr:"Elle aime les fleurs roses."},
"热":      {zh:"今天很热，要喝水。",         py:"Jīn tiān hěn rè, yào hē shuǐ.",           fr:"Il fait chaud aujourd'hui, il faut boire de l'eau."},
"冷":      {zh:"冬天很冷，要穿厚衣服。",     py:"Dōng tiān hěn lěng, yào chuān hòu yī fu.",fr:"Il fait froid en hiver, il faut porter des vêtements chauds."},
"贵":      {zh:"这件衣服太贵了。",           py:"Zhè jiàn yī fu tài guì le.",              fr:"Ce vêtement est trop cher."},
"便宜":    {zh:"这家店的东西很便宜。",       py:"Zhè jiā diàn de dōng xi hěn pián yi.",    fr:"Les articles de ce magasin sont bon marché."},
"新":      {zh:"我买了一双新鞋。",           py:"Wǒ mǎi le yī shuāng xīn xié.",           fr:"J'ai acheté une nouvelle paire de chaussures."},
"旧":      {zh:"这本书很旧，但还能看。",     py:"Zhè běn shū hěn jiù, dàn hái néng kàn.", fr:"Ce livre est vieux mais on peut encore le lire."},
"快":      {zh:"他走路走得很快。",           py:"Tā zǒu lù zǒu de hěn kuài.",             fr:"Il marche très vite."},
"慢":      {zh:"请说慢一点，谢谢。",         py:"Qǐng shuō màn yī diǎn, xiè xie.",         fr:"Parlez plus lentement s'il vous plaît, merci."},
"长":      {zh:"这条路很长。",               py:"Zhè tiáo lù hěn cháng.",                  fr:"Cette route est très longue."},
"短":      {zh:"今天的课很短。",             py:"Jīn tiān de kè hěn duǎn.",                fr:"Le cours d'aujourd'hui est très court."},
"难":      {zh:"这道题很难。",               py:"Zhè dào tí hěn nán.",                     fr:"Cet exercice est très difficile."},
"容易":    {zh:"这个问题很容易。",           py:"Zhè gè wèn tí hěn róng yì.",             fr:"Cette question est très facile."},
"汽车":    {zh:"爸爸开汽车上班。",           py:"Bà ba kāi qì chē shàng bān.",             fr:"Papa conduit une voiture pour aller travailler."},
"公共汽车":{zh:"我每天坐公共汽车去学校。", py:"Wǒ měi tiān zuò gōng gòng qì chē qù xué xiào.",fr:"Je prends le bus tous les jours pour aller à l'école."},
"自行车":  {zh:"他骑自行车去上班。",         py:"Tā qí zì xíng chē qù shàng bān.",         fr:"Il va au travail à vélo."},
"火车":    {zh:"我们坐火车去北京。",         py:"Wǒ men zuò huǒ chē qù Běi jīng.",         fr:"Nous allons à Pékin en train."},
"飞机":    {zh:"他坐飞机去日本。",           py:"Tā zuò fēi jī qù Rì běn.",               fr:"Il va au Japon en avion."},
"头":      {zh:"我今天头有点疼。",           py:"Wǒ jīn tiān tóu yǒu diǎn téng.",          fr:"J'ai un peu mal à la tête aujourd'hui."},
"眼睛":    {zh:"她的眼睛很大很漂亮。",       py:"Tā de yǎn jīng hěn dà hěn piào liang.",  fr:"Ses yeux sont grands et beaux."},
"鼻子":    {zh:"冬天我的鼻子很冷。",         py:"Dōng tiān wǒ de bí zi hěn lěng.",         fr:"En hiver mon nez a très froid."},
"嘴":      {zh:"请用嘴轻轻说话。",           py:"Qǐng yòng zuǐ qīng qīng shuō huà.",      fr:"Parlez doucement s'il vous plaît."},
"耳朵":    {zh:"他的耳朵很大。",             py:"Tā de ěr duo hěn dà.",                    fr:"Ses oreilles sont grandes."},
"手":      {zh:"请洗手再吃饭。",             py:"Qǐng xǐ shǒu zài chī fàn.",              fr:"Lavez-vous les mains avant de manger."},
"脚":      {zh:"她的脚很小。",               py:"Tā de jiǎo hěn xiǎo.",                    fr:"Ses pieds sont petits."},
"天气":    {zh:"今天天气很好，适合出门。",   py:"Jīn tiān tiān qì hěn hǎo, shì hé chū mén.",fr:"Il fait beau aujourd'hui, c'est idéal pour sortir."},
"晴天":    {zh:"晴天我喜欢在外面玩。",       py:"Qíng tiān wǒ xǐ huān zài wài miàn wán.", fr:"Par temps ensoleillé j'aime jouer dehors."},
"下雨":    {zh:"今天下雨，别忘了带伞。",     py:"Jīn tiān xià yǔ, bié wàng le dài sǎn.",  fr:"Il pleut aujourd'hui, n'oublie pas de prendre un parapluie."},
"下雪":    {zh:"冬天有时候会下雪。",         py:"Dōng tiān yǒu shí hou huì xià xuě.",      fr:"Il neige parfois en hiver."},
"风":      {zh:"今天风很大。",               py:"Jīn tiān fēng hěn dà.",                   fr:"Il y a beaucoup de vent aujourd'hui."},
"爷爷":    {zh:"爷爷每天早上打太极拳。",     py:"Yé ye měi tiān zǎo shang dǎ tài jí quán.",fr:"Grand-père fait du tai-chi chaque matin."},
"奶奶":    {zh:"奶奶给我做了好吃的饺子。",   py:"Nǎi nai gěi wǒ zuò le hǎo chī de jiǎo zi.",fr:"Grand-mère m'a préparé de délicieux raviolis."},
"外公":    {zh:"外公住在乡下。",             py:"Wài gōng zhù zài xiāng xia.",             fr:"Grand-père maternel habite à la campagne."},
"外婆":    {zh:"外婆做的菜最好吃。",         py:"Wài pó zuò de cài zuì hǎo chī.",          fr:"Les plats cuisinés par grand-mère maternelle sont les meilleurs."},
"儿子":    {zh:"他的儿子今年五岁。",         py:"Tā de ér zi jīn nián wǔ suì.",            fr:"Son fils a cinq ans cette année."},
"音乐":    {zh:"我每天听音乐放松。",         py:"Wǒ měi tiān tīng yīn yuè fàng sōng.",     fr:"J'écoute de la musique tous les jours pour me détendre."},
"电影":    {zh:"我们周末去看电影。",         py:"Wǒ men zhōu mò qù kàn diàn yǐng.",        fr:"Nous allons voir un film le week-end."},
"运动":    {zh:"每天运动对身体好。",         py:"Měi tiān yùn dòng duì shēn tǐ hǎo.",      fr:"Faire du sport tous les jours est bon pour la santé."},
"游泳":    {zh:"夏天我喜欢去游泳。",         py:"Xià tiān wǒ xǐ huān qù yóu yǒng.",        fr:"J'aime aller nager en été."},
"足球":    {zh:"他最喜欢踢足球。",           py:"Tā zuì xǐ huān tī zú qiú.",              fr:"Son sport préféré est le football."},
"也":      {zh:"我也喜欢吃苹果。",           py:"Wǒ yě xǐ huān chī píng guǒ.",            fr:"J'aime aussi manger des pommes."},
"都":      {zh:"他们都是好学生。",           py:"Tā men dōu shì hǎo xué shēng.",           fr:"Ils sont tous de bons élèves."},
"很":      {zh:"今天天气很好。",             py:"Jīn tiān tiān qì hěn hǎo.",               fr:"Il fait très beau aujourd'hui."},
"太":      {zh:"这个蛋糕太甜了。",           py:"Zhè gè dàn gāo tài tián le.",             fr:"Ce gâteau est trop sucré."},
"非常":    {zh:"这本书非常有意思。",         py:"Zhè běn shū fēi cháng yǒu yì si.",        fr:"Ce livre est extrêmement intéressant."},
"一起":    {zh:"我们一起去吃饭吧。",         py:"Wǒ men yī qǐ qù chī fàn ba.",             fr:"Allons manger ensemble."},
"上面":    {zh:"书在桌子上面。",             py:"Shū zài zhuō zi shàng miàn.",             fr:"Le livre est sur la table."},
"下面":    {zh:"猫在床下面睡觉。",           py:"Māo zài chuáng xià miàn shuì jiào.",      fr:"Le chat dort sous le lit."},
"前面":    {zh:"学校在前面，不远。",         py:"Xué xiào zài qián miàn, bù yuǎn.",        fr:"L'école est devant, pas loin."},
"后面":    {zh:"图书馆在学校后面。",         py:"Tú shū guǎn zài xué xiào hòu miàn.",     fr:"La bibliothèque est derrière l'école."},
"名字":    {zh:"你叫什么名字？",             py:"Nǐ jiào shén me míng zi?",               fr:"Comment tu t'appelles ?"},
"电话":    {zh:"你的电话号码是多少？",       py:"Nǐ de diàn huà hào mǎ shì duō shao?",    fr:"Quel est ton numéro de téléphone ?"},
"电脑":    {zh:"我用电脑做作业。",           py:"Wǒ yòng diàn nǎo zuò zuò yè.",           fr:"J'utilise l'ordinateur pour faire mes devoirs."},
"钱":      {zh:"我没有带钱。",               py:"Wǒ méi yǒu dài qián.",                    fr:"Je n'ai pas apporté d'argent."},
"时间":    {zh:"现在有时间吗？",             py:"Xiàn zài yǒu shí jiān ma?",               fr:"Tu as du temps maintenant ?"},
"衣服":    {zh:"我买了一件新衣服。",         py:"Wǒ mǎi le yī jiàn xīn yī fu.",           fr:"J'ai acheté un nouveau vêtement."},
"桌子":    {zh:"书放在桌子上。",             py:"Shū fàng zài zhuō zi shàng.",             fr:"Les livres sont posés sur la table."},
"椅子":    {zh:"请坐到椅子上。",             py:"Qǐng zuò dào yǐ zi shàng.",              fr:"Assieds-toi sur la chaise s'il te plaît."},
"床":      {zh:"晚上我在床上看书。",         py:"Wǎn shang wǒ zài chuáng shàng kàn shū.", fr:"Le soir je lis au lit."},
"照片":    {zh:"这张照片拍得很好。",         py:"Zhè zhāng zhào piàn pāi de hěn hǎo.",    fr:"Cette photo est très bien prise."},
"礼物":    {zh:"他送给我一份礼物。",         py:"Tā sòng gěi wǒ yī fèn lǐ wù.",          fr:"Il m'a offert un cadeau."},
"节日":    {zh:"春节是中国最大的节日。",     py:"Chūn jié shì Zhōng guó zuì dà de jié rì.",fr:"La Fête du Printemps est la plus grande fête de Chine."},
"汉语":    {zh:"我在学习汉语。",             py:"Wǒ zài xué xí Hàn yǔ.",                  fr:"J'apprends le chinois."},

// ── YCT 3 ──────────────────────────────────────────────────────────────────
"城市":    {zh:"上海是中国最大的城市之一。", py:"Shàng hǎi shì Zhōng guó zuì dà de chéng shì zhī yī.",fr:"Shanghai est l'une des plus grandes villes de Chine."},
"农村":    {zh:"他出生在一个小农村。",       py:"Tā chū shēng zài yī gè xiǎo nóng cūn.",  fr:"Il est né dans un petit village à la campagne."},
"机场":    {zh:"我们去机场接朋友。",         py:"Wǒ men qù jī chǎng jiē péng you.",        fr:"Nous allons chercher un ami à l'aéroport."},
"火车站":  {zh:"火车站离这里不远。",         py:"Huǒ chē zhàn lí zhè lǐ bù yuǎn.",        fr:"La gare n'est pas loin d'ici."},
"银行":    {zh:"我去银行取了一些钱。",       py:"Wǒ qù yín háng qǔ le yī xiē qián.",      fr:"Je suis allé à la banque retirer de l'argent."},
"图书馆":  {zh:"我在图书馆借了几本书。",     py:"Wǒ zài tú shū guǎn jiè le jǐ běn shū.",  fr:"J'ai emprunté quelques livres à la bibliothèque."},
"饭店":    {zh:"他们在饭店吃晚饭。",         py:"Tā men zài fàn diàn chī wǎn fàn.",        fr:"Ils dînent au restaurant."},
"博物馆":  {zh:"这个博物馆有很多历史文物。", py:"Zhè gè bó wù guǎn yǒu hěn duō lì shǐ wén wù.",fr:"Ce musée a de nombreuses reliques historiques."},
"工作":    {zh:"他的工作很有意思。",         py:"Tā de gōng zuò hěn yǒu yì si.",           fr:"Son travail est très intéressant."},
"工程师":  {zh:"他是一位软件工程师。",       py:"Tā shì yī wèi ruǎn jiàn gōng chéng shī.", fr:"Il est ingénieur logiciel."},
"经理":    {zh:"他升职做了经理。",           py:"Tā shēng zhí zuò le jīng lǐ.",            fr:"Il a été promu directeur."},
"律师":    {zh:"她是一位有名的律师。",       py:"Tā shì yī wèi yǒu míng de lǜ shī.",      fr:"Elle est une avocate célèbre."},
"护士":    {zh:"护士耐心地照顾病人。",       py:"Hù shi nài xīn de zhào gù bìng rén.",     fr:"L'infirmière s'occupe patiemment des malades."},
"警察":    {zh:"警察正在调查这个案件。",     py:"Jǐng chá zhèng zài diào chá zhè gè àn jiàn.",fr:"La police enquête sur cette affaire."},
"司机":    {zh:"出租车司机很热情。",         py:"Chū zū chē sī jī hěn rè qíng.",          fr:"Le chauffeur de taxi est très chaleureux."},
"厨师":    {zh:"这位厨师做的菜非常好吃。",   py:"Zhè wèi chú shī zuò de cài fēi cháng hǎo chī.",fr:"Les plats de ce cuisinier sont délicieux."},
"演员":    {zh:"她是一位很受欢迎的演员。",   py:"Tā shì yī wèi hěn shòu huān yíng de yǎn yuán.",fr:"C'est une actrice très populaire."},
"旅游":    {zh:"我喜欢去不同的地方旅游。",   py:"Wǒ xǐ huān qù bù tóng de dì fāng lǚ yóu.",fr:"J'aime voyager dans différents endroits."},
"护照":    {zh:"出国旅行需要护照。",         py:"Chū guó lǚ xíng xū yào hù zhào.",         fr:"Il faut un passeport pour voyager à l'étranger."},
"行李":    {zh:"我的行李太重了。",           py:"Wǒ de xíng li tài zhòng le.",             fr:"Mes bagages sont trop lourds."},
"地图":    {zh:"我用手机看地图找路。",       py:"Wǒ yòng shǒu jī kàn dì tú zhǎo lù.",     fr:"J'utilise mon téléphone pour regarder la carte et trouver mon chemin."},
"签证":    {zh:"去法国需要申请签证。",       py:"Qù Fǎ guó xū yào shēn qǐng qiān zhèng.", fr:"Il faut faire une demande de visa pour aller en France."},
"出发":    {zh:"我们明天早上八点出发。",     py:"Wǒ men míng tiān zǎo shang bā diǎn chū fā.",fr:"Nous partons demain matin à huit heures."},
"到达":    {zh:"飞机下午三点到达北京。",     py:"Fēi jī xià wǔ sān diǎn dào dá Běi jīng.", fr:"L'avion arrive à Pékin à trois heures de l'après-midi."},
"旅行":    {zh:"这次旅行让我难忘。",         py:"Zhè cì lǚ xíng ràng wǒ nán wàng.",        fr:"Ce voyage m'a laissé un souvenir inoubliable."},
"气候":    {zh:"中国不同地区气候不同。",     py:"Zhōng guó bù tóng dì qū qì hòu bù tóng.", fr:"Le climat varie selon les régions de Chine."},
"山":      {zh:"我们爬了一座很高的山。",     py:"Wǒ men pá le yī zuò hěn gāo de shān.",   fr:"Nous avons gravi une très haute montagne."},
"河":      {zh:"这条河水很清。",             py:"Zhè tiáo hé shuǐ hěn qīng.",             fr:"L'eau de cette rivière est très claire."},
"海":      {zh:"我第一次看到大海。",         py:"Wǒ dì yī cì kàn dào dà hǎi.",            fr:"C'est la première fois que je vois la mer."},
"森林":    {zh:"森林里有很多动物。",         py:"Sēn lín lǐ yǒu hěn duō dòng wù.",         fr:"Il y a beaucoup d'animaux dans la forêt."},
"花":      {zh:"春天公园里开满了花。",       py:"Chūn tiān gōng yuán lǐ kāi mǎn le huā.",  fr:"Au printemps le parc est couvert de fleurs."},
"树":      {zh:"院子里有一棵大树。",         py:"Yuàn zi lǐ yǒu yī kē dà shù.",           fr:"Il y a un grand arbre dans la cour."},
"天空":    {zh:"今天天空很蓝。",             py:"Jīn tiān tiān kōng hěn lán.",             fr:"Le ciel est très bleu aujourd'hui."},
"月亮":    {zh:"中秋节的月亮特别圆。",       py:"Zhōng qiū jié de yuè liang tè bié yuán.", fr:"La lune de la Fête de la mi-automne est particulièrement ronde."},
"春天":    {zh:"春天天气暖和，花儿盛开。",   py:"Chūn tiān tiān qì nuǎn huo, huār shèng kāi.",fr:"Au printemps le temps est doux et les fleurs s'épanouissent."},
"夏天":    {zh:"夏天很热，我们去游泳吧。",   py:"Xià tiān hěn rè, wǒ men qù yóu yǒng ba.",fr:"Il fait chaud en été, allons nager."},
"秋天":    {zh:"秋天树叶变黄了。",           py:"Qiū tiān shù yè biàn huáng le.",          fr:"En automne les feuilles deviennent jaunes."},
"冬天":    {zh:"冬天我最喜欢下雪。",         py:"Dōng tiān wǒ zuì xǐ huān xià xuě.",      fr:"Ce que j'aime le plus en hiver c'est la neige."},
"生病":    {zh:"他生病了，需要休息。",       py:"Tā shēng bìng le, xū yào xiū xi.",        fr:"Il est malade, il a besoin de se reposer."},
"头疼":    {zh:"我头疼，想休息一下。",       py:"Wǒ tóu téng, xiǎng xiū xi yī xià.",      fr:"J'ai mal à la tête, je veux me reposer un peu."},
"发烧":    {zh:"孩子发烧了，要去看医生。",   py:"Hái zi fā shāo le, yào qù kàn yī shēng.", fr:"L'enfant a de la fièvre, il faut voir un médecin."},
"药":      {zh:"医生给了我一些药。",         py:"Yī shēng gěi le wǒ yī xiē yào.",          fr:"Le médecin m'a donné des médicaments."},
"休息":    {zh:"工作累了要好好休息。",       py:"Gōng zuò lèi le yào hǎo hǎo xiū xi.",     fr:"Quand on est fatigué du travail, il faut bien se reposer."},
"健康":    {zh:"健康是最重要的事情。",       py:"Jiàn kāng shì zuì zhòng yào de shì qing.", fr:"La santé est la chose la plus importante."},
"感冒":    {zh:"我感冒了，浑身不舒服。",     py:"Wǒ gǎn mào le, hún shēn bù shū fu.",      fr:"J'ai un rhume, je ne me sens pas bien du tout."},
"因为":    {zh:"因为下雨，我们没有出门。",   py:"Yīn wèi xià yǔ, wǒ men méi yǒu chū mén.",fr:"Parce qu'il pleut, nous ne sommes pas sortis."},
"所以":    {zh:"他很努力，所以成绩很好。",   py:"Tā hěn nǔ lì, suǒ yǐ chéng jì hěn hǎo.", fr:"Il travaille dur, donc ses résultats sont bons."},
"虽然":    {zh:"虽然很累，他还是坚持完成了。",py:"Suī rán hěn lèi, tā hái shì jiān chí wán chéng le.",fr:"Bien qu'épuisé, il a persisté et terminé."},
"但是":    {zh:"我想去，但是没有时间。",     py:"Wǒ xiǎng qù, dàn shì méi yǒu shí jiān.", fr:"Je veux y aller, mais je n'ai pas le temps."},
"如果":    {zh:"如果明天下雨，我们就不去了。",py:"Rú guǒ míng tiān xià yǔ, wǒ men jiù bù qù le.",fr:"S'il pleut demain, nous n'irons pas."},
"而且":    {zh:"她聪明，而且非常努力。",     py:"Tā cōng míng, ér qiě fēi cháng nǔ lì.",  fr:"Elle est intelligente et de plus très travailleuse."},
"可以":    {zh:"你可以借我这本书吗？",       py:"Nǐ kě yǐ jiè wǒ zhè běn shū ma?",        fr:"Peux-tu me prêter ce livre ?"},
"应该":    {zh:"我们应该多运动。",           py:"Wǒ men yīng gāi duō yùn dòng.",           fr:"Nous devrions faire plus d'exercice."},
"必须":    {zh:"上学必须准时到。",           py:"Shàng xué bì xū zhǔn shí dào.",           fr:"Il faut arriver à l'heure pour l'école."},
"能":      {zh:"他能说三种语言。",           py:"Tā néng shuō sān zhǒng yǔ yán.",          fr:"Il est capable de parler trois langues."},
"要":      {zh:"我要一杯咖啡，谢谢。",       py:"Wǒ yào yī bēi kā fēi, xiè xie.",         fr:"Je voudrais un café, merci."},
"了解":    {zh:"我想更了解中国文化。",       py:"Wǒ xiǎng gèng liǎo jiě Zhōng guó wén huà.",fr:"Je veux mieux comprendre la culture chinoise."},
"介绍":    {zh:"请介绍一下你自己。",         py:"Qǐng jiè shào yī xià nǐ zì jǐ.",         fr:"Présentez-vous s'il vous plaît."},
"参加":    {zh:"我想参加这次比赛。",         py:"Wǒ xiǎng cān jiā zhè cì bǐ sài.",         fr:"Je veux participer à cette compétition."},
"准备":    {zh:"我正在准备考试。",           py:"Wǒ zhèng zài zhǔn bèi kǎo shì.",          fr:"Je me prépare pour l'examen."},
"解决":    {zh:"我们一起来解决这个问题。",   py:"Wǒ men yī qǐ lái jiě jué zhè gè wèn tí.", fr:"Résolvons ce problème ensemble."},
"发现":    {zh:"科学家发现了新的行星。",     py:"Kē xué jiā fā xiàn le xīn de xíng xīng.", fr:"Les scientifiques ont découvert une nouvelle planète."},
"决定":    {zh:"我决定明年去中国留学。",     py:"Wǒ jué dìng míng nián qù Zhōng guó liú xué.",fr:"J'ai décidé d'aller étudier en Chine l'année prochaine."},
"选择":    {zh:"你选择哪个专业？",           py:"Nǐ xuǎn zé nǎ gè zhuān yè?",             fr:"Quelle spécialité choisis-tu ?"},
"危险":    {zh:"雨天开车很危险。",           py:"Yǔ tiān kāi chē hěn wēi xiǎn.",           fr:"Conduire par temps de pluie est très dangereux."},
"安全":    {zh:"这条路很安全，放心走吧。",   py:"Zhè tiáo lù hěn ān quán, fàng xīn zǒu ba.",fr:"Cette route est sûre, marche sans crainte."},
"简单":    {zh:"这道题很简单，我一下就做完了。",py:"Zhè dào tí hěn jiǎn dān, wǒ yī xià jiù zuò wán le.",fr:"Cet exercice est simple, je l'ai fini rapidement."},
"复杂":    {zh:"这个问题比较复杂。",         py:"Zhè gè wèn tí bǐ jiào fù zá.",            fr:"Cette question est relativement complexe."},
"方便":    {zh:"住在地铁附近很方便。",       py:"Zhù zài dì tiě fù jìn hěn fāng biàn.",    fr:"Habiter près du métro est très pratique."},
"有名":    {zh:"长城是世界有名的景点。",     py:"Cháng chéng shì shì jiè yǒu míng de jǐng diǎn.",fr:"La Grande Muraille est un site touristique mondialement connu."},
"认真":    {zh:"她学习很认真。",             py:"Tā xué xí hěn rèn zhēn.",                  fr:"Elle étudie très sérieusement."},
"丈夫":    {zh:"她的丈夫是一名医生。",       py:"Tā de zhàng fu shì yī míng yī shēng.",    fr:"Son mari est médecin."},
"妻子":    {zh:"他和妻子一起去旅行。",       py:"Tā hé qī zi yī qǐ qù lǚ xíng.",          fr:"Il voyage avec sa femme."},
"父母":    {zh:"父母很关心我的学习。",       py:"Fù mǔ hěn guān xīn wǒ de xué xí.",       fr:"Mes parents se soucient beaucoup de mes études."},
"孩子":    {zh:"孩子们在操场上玩。",         py:"Hái zi men zài cāo chǎng shàng wán.",     fr:"Les enfants jouent sur le terrain de sport."},
"邻居":    {zh:"我们的邻居非常友好。",       py:"Wǒ men de lín jū fēi cháng yǒu hǎo.",     fr:"Nos voisins sont très sympathiques."},
"同事":    {zh:"他和同事关系很好。",         py:"Tā hé tóng shì guān xi hěn hǎo.",         fr:"Il a de bonnes relations avec ses collègues."},
"文化":    {zh:"中国文化历史悠久。",         py:"Zhōng guó wén huà lì shǐ yōu jiǔ.",      fr:"La culture chinoise a une longue histoire."},
"历史":    {zh:"我对中国历史很感兴趣。",     py:"Wǒ duì Zhōng guó lì shǐ hěn gǎn xìng qù.",fr:"Je m'intéresse beaucoup à l'histoire de Chine."},
"经济":    {zh:"这个国家经济发展很快。",     py:"Zhè gè guó jiā jīng jì fā zhǎn hěn kuài.",fr:"L'économie de ce pays se développe rapidement."},
"社会":    {zh:"社会上有各种各样的人。",     py:"Shè huì shàng yǒu gè zhǒng gè yàng de rén.",fr:"Il y a toutes sortes de personnes dans la société."},
"教育":    {zh:"教育是国家发展的基础。",     py:"Jiào yù shì guó jiā fā zhǎn de jī chǔ.",  fr:"L'éducation est le fondement du développement national."},
"科技":    {zh:"科技进步改变了我们的生活。", py:"Kē jì jìn bù gǎi biàn le wǒ men de shēng huó.",fr:"Le progrès technologique a changé notre vie."},

// ── YCT 3 — ajouts ────────────────────────────────────────────────────────
"认识":    {zh:"我在北京认识了很多朋友。",     py:"Wǒ zài Běi jīng rèn shi le hěn duō péng you.",fr:"J'ai rencontré beaucoup d'amis à Pékin."},
"帮助":    {zh:"他帮助我解决了这个问题。",     py:"Tā bāng zhù wǒ jiě jué le zhè gè wèn tí.", fr:"Il m'a aidé à résoudre ce problème."},
"告诉":    {zh:"请告诉我你的电话号码。",       py:"Qǐng gào su wǒ nǐ de diàn huà hào mǎ.",    fr:"Dis-moi ton numéro de téléphone s'il te plaît."},
"希望":    {zh:"我希望将来能去法国留学。",     py:"Wǒ xī wàng jiāng lái néng qù Fǎ guó liú xué.",fr:"J'espère pouvoir aller étudier en France à l'avenir."},
"注意":    {zh:"过马路要注意安全。",           py:"Guò mǎ lù yào zhù yì ān quán.",            fr:"Fais attention à la sécurité en traversant la rue."},
"觉得":    {zh:"我觉得这部电影很有意思。",     py:"Wǒ jué de zhè bù diàn yǐng hěn yǒu yì si.",fr:"Je trouve ce film très intéressant."},
"需要":    {zh:"学好汉语需要每天练习。",       py:"Xué hǎo Hàn yǔ xū yào měi tiān liàn xí.",  fr:"Pour bien apprendre le chinois, il faut s'entraîner tous les jours."},
"完成":    {zh:"他按时完成了所有作业。",       py:"Tā àn shí wán chéng le suǒ yǒu zuò yè.",   fr:"Il a terminé tous ses devoirs à temps."},
"开始":    {zh:"我们明天开始新的课程。",       py:"Wǒ men míng tiān kāi shǐ xīn de kè chéng.", fr:"Nous commençons le nouveau programme demain."},
"结束":    {zh:"比赛已经结束了。",             py:"Bǐ sài yǐ jīng jié shù le.",               fr:"La compétition est déjà terminée."},
"忘记":    {zh:"我忘记带钥匙了。",             py:"Wǒ wàng jì dài yào shi le.",               fr:"J'ai oublié d'apporter mes clés."},
"记得":    {zh:"你还记得我们第一次见面吗？",   py:"Nǐ hái jì de wǒ men dì yī cì jiàn miàn ma?",fr:"Tu te souviens encore de notre première rencontre ?"},
"使用":    {zh:"这款软件很容易使用。",         py:"Zhè kuǎn ruǎn jiàn hěn róng yì shǐ yòng.", fr:"Ce logiciel est très facile à utiliser."},
"打算":    {zh:"你打算什么时候回国？",         py:"Nǐ dǎ suàn shén me shí hou huí guó?",      fr:"Quand as-tu l'intention de rentrer dans ton pays ?"},
"借":      {zh:"我可以借你的自行车吗？",       py:"Wǒ kě yǐ jiè nǐ de zì xíng chē ma?",      fr:"Est-ce que je peux emprunter ton vélo ?"},
"换":      {zh:"我想换一件更大的衣服。",       py:"Wǒ xiǎng huàn yī jiàn gèng dà de yī fu.",  fr:"Je veux échanger contre un vêtement plus grand."},
"找":      {zh:"我在找我的手机，你看到了吗？", py:"Wǒ zài zhǎo wǒ de shǒu jī, nǐ kàn dào le ma?",fr:"Je cherche mon téléphone, tu l'as vu ?"},
"送":      {zh:"他送了我一束花。",             py:"Tā sòng le wǒ yī shù huā.",                fr:"Il m'a offert un bouquet de fleurs."},
"联系":    {zh:"有问题可以随时联系我。",       py:"Yǒu wèn tí kě yǐ suí shí lián xì wǒ.",    fr:"Si tu as des questions, contacte-moi à tout moment."},
"继续":    {zh:"请继续，不要停。",             py:"Qǐng jì xù, bú yào tíng.",                fr:"Continuez, ne vous arrêtez pas."},
"放":      {zh:"请把书包放在桌子上。",         py:"Qǐng bǎ shū bāo fàng zài zhuō zi shàng.", fr:"Pose ton cartable sur la table s'il te plaît."},
"拿":      {zh:"他拿着一本书走进来。",         py:"Tā ná zhe yī běn shū zǒu jìn lái.",        fr:"Il est entré en portant un livre."},
"解释":    {zh:"老师解释了这道难题。",         py:"Lǎo shī jiě shì le zhè dào nán tí.",       fr:"Le professeur a expliqué cet exercice difficile."},
"比较":    {zh:"这两种方法各有优缺点，很难比较。",py:"Zhè liǎng zhǒng fāng fǎ gè yǒu yōu quē diǎn, hěn nán bǐ jiào.",fr:"Ces deux méthodes ont chacune leurs avantages et inconvénients, difficile de les comparer."},
"担心":    {zh:"妈妈很担心我的健康。",         py:"Māma hěn dān xīn wǒ de jiàn kāng.",        fr:"Maman s'inquiète beaucoup pour ma santé."},
"相信":    {zh:"我相信你一定能成功。",         py:"Wǒ xiāng xìn nǐ yī dìng néng chéng gōng.", fr:"Je crois que tu vas réussir."},
"改变":    {zh:"学习改变了我的生活。",         py:"Xué xí gǎi biàn le wǒ de shēng huó.",      fr:"L'étude a changé ma vie."},
"提高":    {zh:"多练习可以提高汉语水平。",     py:"Duō liàn xí kě yǐ tí gāo Hàn yǔ shuǐ píng.",fr:"Pratiquer davantage peut améliorer le niveau de chinois."},
"请":      {zh:"我请你吃饭，今天我来付。",     py:"Wǒ qǐng nǐ chī fàn, jīn tiān wǒ lái fù.", fr:"Je t'invite à manger, c'est moi qui paie aujourd'hui."},
"带":      {zh:"出门别忘了带雨伞。",           py:"Chū mén bié wàng le dài yǔ sǎn.",          fr:"N'oublie pas d'apporter un parapluie en sortant."},
"大家":    {zh:"大家一起来唱歌吧！",           py:"Dà jiā yī qǐ lái chàng gē ba!",            fr:"Chantons tous ensemble !"},
"别人":    {zh:"不要总是拿自己跟别人比较。",   py:"Bú yào zǒng shì ná zì jǐ gēn bié rén bǐ jiào.",fr:"Ne te compare pas toujours aux autres."},
"自己":    {zh:"做事要相信自己。",             py:"Zuò shì yào xiāng xìn zì jǐ.",             fr:"Il faut croire en soi dans ce qu'on fait."},
"客人":    {zh:"今晚家里有客人来吃饭。",       py:"Jīn wǎn jiā lǐ yǒu kè rén lái chī fàn.",  fr:"Ce soir des invités viennent dîner à la maison."},
"服务员":  {zh:"服务员，请给我看一下菜单。",   py:"Fú wù yuán, qǐng gěi wǒ kàn yī xià cài dān.",fr:"Serveur, montrez-moi le menu s'il vous plaît."},
"地方":    {zh:"这个地方风景很美。",           py:"Zhè gè dì fāng fēng jǐng hěn měi.",        fr:"Le paysage de cet endroit est très beau."},
"附近":    {zh:"学校附近有一家超市。",         py:"Xué xiào fù jìn yǒu yī jiā chāo shì.",     fr:"Il y a un supermarché près de l'école."},
"中间":    {zh:"他坐在我们两个人中间。",       py:"Tā zuò zài wǒ men liǎng gè rén zhōng jiān.",fr:"Il est assis entre nous deux."},
"旁边":    {zh:"图书馆就在银行旁边。",         py:"Tú shū guǎn jiù zài yín háng páng biān.",  fr:"La bibliothèque est juste à côté de la banque."},
"左边":    {zh:"学校在邮局左边。",             py:"Xué xiào zài yóu jú zuǒ biān.",             fr:"L'école est à gauche de la poste."},
"右边":    {zh:"餐厅在书店右边。",             py:"Cān tīng zài shū diàn yòu biān.",           fr:"Le restaurant est à droite de la librairie."},
"外面":    {zh:"外面下雨了，不要出去。",       py:"Wài miàn xià yǔ le, bú yào chū qù.",       fr:"Il pleut dehors, ne sors pas."},
"里面":    {zh:"盒子里面放着一封信。",         py:"Hé zi lǐ miàn fàng zhe yī fēng xìn.",      fr:"Il y a une lettre à l'intérieur de la boîte."},
"时候":    {zh:"小的时候，我很喜欢画画。",     py:"Xiǎo de shí hou, wǒ hěn xǐ huān huà huà.", fr:"Quand j'étais petit, j'aimais beaucoup dessiner."},
"最近":    {zh:"最近我很忙，没有时间休息。",   py:"Zuì jìn wǒ hěn máng, méi yǒu shí jiān xiū xi.",fr:"Récemment je suis très occupé et n'ai pas le temps de me reposer."},
"刚才":    {zh:"刚才谁打电话来了？",           py:"Gāng cái shéi dǎ diàn huà lái le?",        fr:"Qui a appelé tout à l'heure ?"},
"将来":    {zh:"我将来想成为一名医生。",       py:"Wǒ jiāng lái xiǎng chéng wéi yī míng yī shēng.",fr:"Je veux devenir médecin à l'avenir."},
"东西":    {zh:"你买了什么东西？",             py:"Nǐ mǎi le shén me dōng xi?",               fr:"Qu'est-ce que tu as acheté ?"},
"事情":    {zh:"我有一件重要的事情要告诉你。", py:"Wǒ yǒu yī jiàn zhòng yào de shì qing yào gào su nǐ.",fr:"J'ai quelque chose d'important à te dire."},
"问题":    {zh:"这道题有问题，答案不对。",     py:"Zhè dào tí yǒu wèn tí, dá àn bú duì.",     fr:"Cet exercice a un problème, la réponse est fausse."},
"机会":    {zh:"这是一个很好的学习机会。",     py:"Zhè shì yī gè hěn hǎo de xué xí jī huì.",  fr:"C'est une très bonne occasion d'apprendre."},
"声音":    {zh:"外面的声音太大了。",           py:"Wài miàn de shēng yīn tài dà le.",          fr:"Le bruit dehors est trop fort."},
"方法":    {zh:"学习汉语有很多好的方法。",     py:"Xué xí Hàn yǔ yǒu hěn duō hǎo de fāng fǎ.",fr:"Il existe de nombreuses bonnes méthodes pour apprendre le chinois."},
"原因":    {zh:"他缺席的原因是生病了。",       py:"Tā quē xí de yuán yīn shì shēng bìng le.", fr:"La raison de son absence est qu'il est tombé malade."},
"结果":    {zh:"考试结果出来了，他得了满分。", py:"Kǎo shì jié guǒ chū lái le, tā dé le mǎn fēn.",fr:"Les résultats de l'examen sont sortis, il a eu la note maximale."},
"意思":    {zh:"这个词是什么意思？",           py:"Zhè gè cí shì shén me yì si?",             fr:"Quel est le sens de ce mot ?"},
"信息":    {zh:"我从网上得到了很多有用的信息。",py:"Wǒ cóng wǎng shàng dé dào le hěn duō yǒu yòng de xìn xī.",fr:"J'ai trouvé beaucoup d'informations utiles sur Internet."},
"习惯":    {zh:"他有早起的好习惯。",           py:"Tā yǒu zǎo qǐ de hǎo xí guàn.",           fr:"Il a la bonne habitude de se lever tôt."},
"计划":    {zh:"你有什么暑假计划？",           py:"Nǐ yǒu shén me shǔ jià jì huà?",           fr:"Quels sont tes projets pour les vacances d'été ?"},
"成绩":    {zh:"他这次考试成绩很好。",         py:"Tā zhè cì kǎo shì chéng jì hěn hǎo.",      fr:"Il a obtenu de très bons résultats à cet examen."},
"作业":    {zh:"老师布置了很多作业。",         py:"Lǎo shī bù zhì le hěn duō zuò yè.",        fr:"Le professeur a donné beaucoup de devoirs."},
"考试":    {zh:"明天有汉语考试，我要好好复习。",py:"Míng tiān yǒu Hàn yǔ kǎo shì, wǒ yào hǎo hǎo fù xí.",fr:"Demain il y a un examen de chinois, je dois bien réviser."},
"裙子":    {zh:"她穿着一条蓝色的裙子。",       py:"Tā chuān zhe yī tiáo lán sè de qún zi.",   fr:"Elle porte une jupe bleue."},
"裤子":    {zh:"这条裤子太长了，需要改短。",   py:"Zhè tiáo kù zi tài cháng le, xū yào gǎi duǎn.",fr:"Ce pantalon est trop long, il faut le raccourcir."},
"鞋":      {zh:"他买了一双新鞋。",             py:"Tā mǎi le yī shuāng xīn xié.",             fr:"Il a acheté une nouvelle paire de chaussures."},
"帽子":    {zh:"冬天出门要戴帽子。",           py:"Dōng tiān chū mén yào dài mào zi.",         fr:"En hiver il faut porter un chapeau en sortant."},
"外套":    {zh:"天冷了，穿上外套吧。",         py:"Tiān lěng le, chuān shàng wài tào ba.",     fr:"Il fait froid, mets ton manteau."},
"袜子":    {zh:"我找不到我的袜子了。",         py:"Wǒ zhǎo bu dào wǒ de wà zi le.",           fr:"Je ne trouve plus mes chaussettes."},
"重要":    {zh:"健康是最重要的事情。",         py:"Jiàn kāng shì zuì zhòng yào de shì qing.",  fr:"La santé est la chose la plus importante."},
"可爱":    {zh:"这只小狗太可爱了！",           py:"Zhè zhī xiǎo gǒu tài kě ài le!",           fr:"Ce petit chien est trop mignon !"},
"特别":    {zh:"今天的天气特别好。",           py:"Jīn tiān de tiān qì tè bié hǎo.",           fr:"Le temps est particulièrement beau aujourd'hui."},
"正确":    {zh:"你的答案是正确的。",           py:"Nǐ de dá àn shì zhèng què de.",             fr:"Ta réponse est correcte."},
"有趣":    {zh:"这本书非常有趣。",             py:"Zhè běn shū fēi cháng yǒu qù.",             fr:"Ce livre est très intéressant."},
"难过":    {zh:"她听到这个消息非常难过。",     py:"Tā tīng dào zhè gè xiāo xi fēi cháng nán guò.",fr:"Elle était très triste en apprenant cette nouvelle."},
"干净":    {zh:"房间收拾得很干净。",           py:"Fáng jiān shōu shi de hěn gān jìng.",       fr:"La chambre est bien rangée et propre."},
"聪明":    {zh:"这个孩子很聪明，学什么都快。", py:"Zhè gè hái zi hěn cōng míng, xué shén me dōu kuài.",fr:"Cet enfant est très intelligent, il apprend tout vite."},
"紧张":    {zh:"考试前他非常紧张。",           py:"Kǎo shì qián tā fēi cháng jǐn zhāng.",      fr:"Il était très nerveux avant l'examen."},
"舒服":    {zh:"这张沙发坐上去很舒服。",       py:"Zhè zhāng shā fā zuò shàng qù hěn shū fu.", fr:"Ce canapé est très confortable pour s'asseoir."},
"累":      {zh:"工作了一天，我很累了。",       py:"Gōng zuò le yī tiān, wǒ hěn lèi le.",      fr:"Après avoir travaillé toute la journée, je suis très fatigué."},
"忙":      {zh:"最近工作太忙，没时间休息。",   py:"Zuì jìn gōng zuò tài máng, méi shí jiān xiū xi.",fr:"Récemment le travail est trop chargé, pas le temps de se reposer."},
"年轻":    {zh:"她看起来很年轻，其实已经四十岁了。",py:"Tā kàn qǐ lái hěn nián qīng, qí shí yǐ jīng sì shí suì le.",fr:"Elle paraît très jeune, mais elle a en fait déjà quarante ans."},
"普通":    {zh:"这是一道很普通的家常菜。",     py:"Zhè shì yī dào hěn pǔ tōng de jiā cháng cài.",fr:"C'est un plat familial très ordinaire."},
"开心":    {zh:"看到你我很开心。",             py:"Kàn dào nǐ wǒ hěn kāi xīn.",               fr:"Je suis très content de te voir."},
"当然":    {zh:"当然，你可以来参加我们的活动。",py:"Dāng rán, nǐ kě yǐ lái cān jiā wǒ men de huó dòng.",fr:"Bien sûr, tu peux venir participer à notre activité."},
"可能":    {zh:"明天可能会下雨。",             py:"Míng tiān kě néng huì xià yǔ.",             fr:"Il est possible qu'il pleuve demain."},
"一定":    {zh:"你一定要来参加我的生日聚会！", py:"Nǐ yī dìng yào lái cān jiā wǒ de shēng rì jù huì!",fr:"Tu dois absolument venir à ma fête d'anniversaire !"},
"其实":    {zh:"他看起来严肃，其实很幽默。",   py:"Tā kàn qǐ lái yán sù, qí shí hěn yōu mò.", fr:"Il paraît sérieux, mais en fait il est très drôle."},
"一直":    {zh:"他一直在努力学习汉语。",       py:"Tā yī zhí zài nǔ lì xué xí Hàn yǔ.",       fr:"Il apprend le chinois assidûment depuis toujours."},
"怎么":    {zh:"这个字怎么读？",               py:"Zhè gè zì zěn me dú?",                     fr:"Comment lit-on ce caractère ?"},
"已经":    {zh:"他已经学了三年汉语了。",       py:"Tā yǐ jīng xué le sān nián Hàn yǔ le.",    fr:"Il étudie le chinois depuis trois ans déjà."},
"还是":    {zh:"你喝茶还是喝咖啡？",           py:"Nǐ hē chá hái shì hē kā fēi?",             fr:"Tu bois du thé ou du café ?"},
"总是":    {zh:"她总是第一个到学校。",         py:"Tā zǒng shì dì yī gè dào xué xiào.",        fr:"Elle est toujours la première arrivée à l'école."},
"马上":    {zh:"我马上就来，请稍等。",         py:"Wǒ mǎ shàng jiù lái, qǐng shāo děng.",     fr:"J'arrive tout de suite, patientez un instant."},
"尤其":    {zh:"他喜欢运动，尤其是游泳。",     py:"Tā xǐ huān yùn dòng, yóu qí shì yóu yǒng.", fr:"Il aime le sport, surtout la natation."},
"终于":    {zh:"经过努力，他终于考上了大学。", py:"Jīng guò nǔ lì, tā zhōng yú kǎo shàng le dà xué.",fr:"Après ses efforts, il a enfin réussi à entrer à l'université."},
"次":      {zh:"我去过中国两次。",             py:"Wǒ qù guò Zhōng guó liǎng cì.",             fr:"Je suis allé en Chine deux fois."},
"件":      {zh:"她买了三件新衣服。",           py:"Tā mǎi le sān jiàn xīn yī fu.",             fr:"Elle a acheté trois nouveaux vêtements."},
"条":      {zh:"他有两条裤子，一条蓝一条黑。", py:"Tā yǒu liǎng tiáo kù zi, yī tiáo lán yī tiáo hēi.",fr:"Il a deux pantalons, un bleu et un noir."},
"双":      {zh:"我买了一双白色的运动鞋。",     py:"Wǒ mǎi le yī shuāng bái sè de yùn dòng xié.",fr:"J'ai acheté une paire de baskets blanches."},
"瓶":      {zh:"他喝了一瓶水。",               py:"Tā hē le yī píng shuǐ.",                    fr:"Il a bu une bouteille d'eau."},

// ── YCT 4 ──────────────────────────────────────────────────────────────────
"辩论":    {zh:"两队进行了激烈的辩论。",     py:"Liǎng duì jìn xíng le jī liè de biàn lùn.",fr:"Les deux équipes ont mené un débat animé."},
"演讲":    {zh:"他在台上做了精彩的演讲。",   py:"Tā zài tái shàng zuò le jīng cǎi de yǎn jiǎng.",fr:"Il a fait un discours brillant sur scène."},
"表达":    {zh:"她善于表达自己的想法。",     py:"Tā shàn yú biǎo dá zì jǐ de xiǎng fǎ.",  fr:"Elle est douée pour exprimer ses idées."},
"交流":    {zh:"文化交流促进相互理解。",     py:"Wén huà jiāo liú cù jìn xiāng hù lǐ jiě.", fr:"Les échanges culturels favorisent la compréhension mutuelle."},
"描述":    {zh:"请描述一下那个人的外貌。",   py:"Qǐng miáo shù yī xià nà gè rén de wài mào.",fr:"Décrivez l'apparence de cette personne s'il vous plaît."},
"说明":    {zh:"请说明你的理由。",           py:"Qǐng shuō míng nǐ de lǐ yóu.",            fr:"Expliquez vos raisons s'il vous plaît."},
"强调":    {zh:"老师强调了这道题的重要性。", py:"Lǎo shī qiáng diào le zhè dào tí de zhòng yào xìng.",fr:"Le professeur a souligné l'importance de cet exercice."},
"反驳":    {zh:"他用事实反驳了对方的观点。", py:"Tā yòng shì shí fǎn bó le duì fāng de guān diǎn.",fr:"Il a réfuté le point de vue de l'adversaire avec des faits."},
"平等":    {zh:"人人都应该享有平等的权利。", py:"Rén rén dōu yīng gāi xiǎng yǒu píng děng de quán lì.",fr:"Tout le monde devrait jouir de droits égaux."},
"民主":    {zh:"民主制度保障公民的参与权。", py:"Mín zhǔ zhì dù bǎo zhàng gōng mín de cān yù quán.",fr:"Le système démocratique garantit le droit de participation des citoyens."},
"自由":    {zh:"每个人都有表达自由的权利。", py:"Měi gè rén dōu yǒu biǎo dá zì yóu de quán lì.",fr:"Chacun a le droit à la liberté d'expression."},
"责任":    {zh:"保护环境是我们共同的责任。", py:"Bǎo hù huán jìng shì wǒ men gòng tóng de zé rèn.",fr:"Protéger l'environnement est notre responsabilité commune."},
"权利":    {zh:"受教育是每个孩子的权利。",   py:"Shòu jiào yù shì měi gè hái zi de quán lì.",fr:"Recevoir une éducation est le droit de chaque enfant."},
"义务":    {zh:"纳税是公民的义务。",         py:"Nà shuì shì gōng mín de yì wù.",           fr:"Payer des impôts est une obligation citoyenne."},
"公平":    {zh:"比赛结果应该是公平的。",     py:"Bǐ sài jié guǒ yīng gāi shì gōng píng de.",fr:"Les résultats de la compétition devraient être équitables."},
"规则":    {zh:"每个游戏都有它的规则。",     py:"Měi gè yóu xì dōu yǒu tā de guī zé.",     fr:"Chaque jeu a ses règles."},
"传统":    {zh:"过春节是中国的传统。",       py:"Guò chūn jié shì Zhōng guó de chuán tǒng.", fr:"Célébrer la Fête du Printemps est une tradition chinoise."},
"习俗":    {zh:"不同地区有不同的风俗习惯。", py:"Bù tóng dì qū yǒu bù tóng de fēng sú xí guàn.",fr:"Différentes régions ont différentes coutumes et traditions."},
"投资":    {zh:"他把钱投资到股票市场。",     py:"Tā bǎ qián tóu zī dào gǔ piào shì chǎng.", fr:"Il a investi son argent dans le marché boursier."},
"利润":    {zh:"这家公司今年利润很高。",     py:"Zhè jiā gōng sī jīn nián lì rùn hěn gāo.", fr:"Cette entreprise a réalisé de bons bénéfices cette année."},
"市场":    {zh:"这种商品在市场上很受欢迎。", py:"Zhè zhǒng shāng pǐn zài shì chǎng shàng hěn shòu huān yíng.",fr:"Ce produit est très populaire sur le marché."},
"消费":    {zh:"消费者权益受法律保护。",     py:"Xiāo fèi zhě quán yì shòu fǎ lǜ bǎo hù.",  fr:"Les droits des consommateurs sont protégés par la loi."},
"税收":    {zh:"政府用税收建设公共设施。",   py:"Zhèng fǔ yòng shuì shōu jiàn shè gōng gòng shè shī.",fr:"Le gouvernement utilise les impôts pour construire des équipements publics."},
"预算":    {zh:"这个项目的预算是一百万元。", py:"Zhè gè xiàng mù de yù suàn shì yī bǎi wàn yuán.",fr:"Le budget de ce projet est d'un million de yuans."},
"通货膨胀":{zh:"通货膨胀导致物价上涨。",   py:"Tōng huò péng zhàng dǎo zhì wù jià shàng zhǎng.",fr:"L'inflation entraîne une hausse des prix."},
"贸易":    {zh:"两国之间贸易往来频繁。",     py:"Liǎng guó zhī jiān mào yì wǎng lái pín fán.",fr:"Les échanges commerciaux entre les deux pays sont fréquents."},
"环境":    {zh:"保护环境是全人类的责任。",   py:"Bǎo hù huán jìng shì quán rén lèi de zé rèn.",fr:"Protéger l'environnement est la responsabilité de toute l'humanité."},
"污染":    {zh:"工厂排放废气造成了空气污染。",py:"Gōng chǎng pái fàng fèi qì zào chéng le kōng qì wū rǎn.",fr:"Les émissions des usines causent la pollution de l'air."},
"能源":    {zh:"太阳能是一种清洁能源。",     py:"Tài yáng néng shì yī zhǒng qīng jié néng yuán.",fr:"L'énergie solaire est une énergie propre."},
"生态":    {zh:"我们要保护当地的生态环境。", py:"Wǒ men yào bǎo hù dāng dì de shēng tài huán jìng.",fr:"Nous devons protéger l'environnement écologique local."},
"气候变化":{zh:"气候变化威胁着整个地球。",  py:"Qì hòu biàn huà wēi xié zhe zhěng gè dì qiú.",fr:"Le changement climatique menace toute la planète."},
"可再生":  {zh:"可再生能源是未来发展的方向。",py:"Kě zài shēng néng yuán shì wèi lái fā zhǎn de fāng xiàng.",fr:"Les énergies renouvelables sont la direction du développement futur."},
"人工智能":{zh:"人工智能正在改变各行各业。", py:"Rén gōng zhì néng zhèng zài gǎi biàn gè háng gè yè.",fr:"L'intelligence artificielle est en train de transformer tous les secteurs."},
"机器人":  {zh:"工厂里用机器人代替人工。",   py:"Gōng chǎng lǐ yòng jī qì rén dài tì rén gōng.",fr:"Les usines utilisent des robots pour remplacer le travail humain."},
"研究":    {zh:"科学家花了多年研究这个问题。",py:"Kē xué jiā huā le duō nián yán jiū zhè gè wèn tí.",fr:"Les scientifiques ont consacré de nombreuses années à étudier cette question."},
"实验":    {zh:"他在实验室做实验。",         py:"Tā zài shí yàn shì zuò shí yàn.",          fr:"Il fait des expériences en laboratoire."},
"发明":    {zh:"印刷术是中国的四大发明之一。",py:"Yìn shuā shù shì Zhōng guó de sì dà fā míng zhī yī.",fr:"L'imprimerie est l'une des quatre grandes inventions chinoises."},
"创新":    {zh:"创新是推动社会进步的动力。", py:"Chuàng xīn shì tuī dòng shè huì jìn bù de dòng lì.",fr:"L'innovation est le moteur du progrès social."},
"技术":    {zh:"新技术提高了生产效率。",     py:"Xīn jì shù tí gāo le shēng chǎn xiào lǜ.", fr:"Les nouvelles technologies ont amélioré l'efficacité productive."},
"数字化":  {zh:"数字化转型成为各行业的趋势。",py:"Shù zì huà zhuǎn xíng chéng wéi gè háng yè de qū shì.",fr:"La transformation numérique est devenue une tendance dans tous les secteurs."},
"文学":    {zh:"中国文学有几千年的历史。",   py:"Zhōng guó wén xué yǒu jǐ qiān nián de lì shǐ.",fr:"La littérature chinoise a plusieurs milliers d'années d'histoire."},
"小说":    {zh:"他喜欢读历史小说。",         py:"Tā xǐ huān dú lì shǐ xiǎo shuō.",         fr:"Il aime lire des romans historiques."},
"诗歌":    {zh:"李白是中国著名的诗歌大师。", py:"Lǐ Bái shì Zhōng guó zhù míng de shī gē dà shī.",fr:"Li Bai est un grand maître de la poésie chinoise."},
"艺术":    {zh:"艺术来源于生活。",           py:"Yì shù lái yuán yú shēng huó.",            fr:"L'art vient de la vie."},
"绘画":    {zh:"她从小就喜欢绘画。",         py:"Tā cóng xiǎo jiù xǐ huān huì huà.",       fr:"Elle aime la peinture depuis l'enfance."},
"音乐会":  {zh:"我们去听了一场古典音乐会。", py:"Wǒ men qù tīng le yī chǎng gǔ diǎn yīn yuè huì.",fr:"Nous sommes allés écouter un concert de musique classique."},
"心理":    {zh:"良好的心理状态有助于健康。", py:"Liáng hǎo de xīn lǐ zhuàng tài yǒu zhù yú jiàn kāng.",fr:"Un bon état psychologique contribue à la santé."},
"哲学":    {zh:"哲学引导我们思考生命的意义。",py:"Zhé xué yǐn dǎo wǒ men sī kǎo shēng mìng de yì yì.",fr:"La philosophie nous guide pour réfléchir au sens de la vie."},
"逻辑":    {zh:"他的推理很有逻辑性。",       py:"Tā de tuī lǐ hěn yǒu luó jí xìng.",       fr:"Son raisonnement est très logique."},
"道德":    {zh:"诚实是基本的道德准则。",     py:"Chéng shí shì jī běn de dào dé zhǔn zé.", fr:"L'honnêteté est un principe moral fondamental."},
"坚持":    {zh:"只有坚持，才能实现目标。",   py:"Zhǐ yǒu jiān chí, cái néng shí xiàn mù biāo.",fr:"Ce n'est qu'en persévérant qu'on peut atteindre ses objectifs."},
"勇气":    {zh:"面对困难需要勇气。",         py:"Miàn duì kùn nán xū yào yǒng qì.",         fr:"Faire face aux difficultés demande du courage."},
"耐心":    {zh:"教孩子需要很多耐心。",       py:"Jiāo hái zi xū yào hěn duō nài xīn.",     fr:"Enseigner aux enfants demande beaucoup de patience."},
"谦虚":    {zh:"他取得成功后依然保持谦虚。", py:"Tā qǔ dé chéng gōng hòu yī rán bǎo chí qiān xū.",fr:"Il reste humble même après son succès."},
"诚实":    {zh:"诚实是做人的基本品质。",     py:"Chéng shí shì zuò rén de jī běn pǐn zhì.", fr:"L'honnêteté est une qualité fondamentale de l'être humain."},
"积极":    {zh:"他对工作总是很积极。",       py:"Tā duì gōng zuò zǒng shì hěn jī jí.",     fr:"Il est toujours très actif et positif dans son travail."},
"乐观":    {zh:"乐观的人更容易快乐。",       py:"Lè guān de rén gèng róng yì kuài lè.",    fr:"Les personnes optimistes ont plus facilement tendance à être heureuses."},
"悲观":    {zh:"悲观的态度不利于解决问题。", py:"Bēi guān de tài dù bù lì yú jiě jué wèn tí.",fr:"Une attitude pessimiste ne favorise pas la résolution des problèmes."},
"移民":    {zh:"很多移民为这个国家做出了贡献。",py:"Hěn duō yí mín wèi zhè gè guó jiā zuò chū le gòng xiàn.",fr:"Beaucoup d'immigrants ont contribué à ce pays."},
"全球化":  {zh:"全球化加快了信息传播速度。", py:"Quán qiú huà jiā kuài le xìn xī chuán bō sù dù.",fr:"La mondialisation a accéléré la vitesse de diffusion de l'information."},
"国际":    {zh:"他参加了国际学术会议。",     py:"Tā cān jiā le guó jì xué shù huì yì.",    fr:"Il a participé à une conférence académique internationale."},
"冲突":    {zh:"双方通过谈判解决了冲突。",   py:"Shuāng fāng tōng guò tán pàn jiě jué le chōng tū.",fr:"Les deux parties ont résolu le conflit par la négociation."},
"和平":    {zh:"世界和平是全人类共同的愿望。",py:"Shì jiè hé píng shì quán rén lèi gòng tóng de yuàn wàng.",fr:"La paix mondiale est le désir commun de toute l'humanité."},
"战争":    {zh:"战争给人类带来巨大的痛苦。", py:"Zhàn zhēng gěi rén lèi dài lái jù dà de tòng kǔ.",fr:"La guerre apporte d'immenses souffrances à l'humanité."},

// ── YCT 5 ──────────────────────────────────────────────────────────────────
"抽象":    {zh:"艺术有时是抽象的，难以理解。",py:"Yì shù yǒu shí shì chōu xiàng de, nán yǐ lǐ jiě.",fr:"L'art est parfois abstrait et difficile à comprendre."},
"具体":    {zh:"请举一个具体的例子。",       py:"Qǐng jǔ yī gè jù tǐ de lì zi.",           fr:"Donnez un exemple concret s'il vous plaît."},
"本质":    {zh:"哲学家致力于探索事物的本质。",py:"Zhé xué jiā zhì lì yú tàn suǒ shì wù de běn zhì.",fr:"Les philosophes s'efforcent d'explorer l'essence des choses."},
"现象":    {zh:"全球变暖是一个令人担忧的现象。",py:"Quán qiú biàn nuǎn shì yī gè lìng rén dān yōu de xiàn xiàng.",fr:"Le réchauffement climatique est un phénomène préoccupant."},
"规律":    {zh:"科学研究发现了自然界的规律。",py:"Kē xué yán jiū fā xiàn le zì rán jiè de guī lǜ.",fr:"La recherche scientifique a découvert les lois de la nature."},
"假设":    {zh:"这个实验基于一个重要的假设。",py:"Zhè gè shí yàn jī yú yī gè zhòng yào de jiǎ shè.",fr:"Cette expérience repose sur une hypothèse importante."},
"推理":    {zh:"逻辑推理是解决问题的好方法。",py:"Luó jí tuī lǐ shì jiě jué wèn tí de hǎo fāng fǎ.",fr:"Le raisonnement logique est une bonne méthode pour résoudre les problèmes."},
"客观":    {zh:"评价一件事应该保持客观。",   py:"Píng jià yī jiàn shì yīng gāi bǎo chí kè guān.",fr:"L'évaluation d'une situation devrait rester objective."},
"主观":    {zh:"他的判断太主观，缺乏依据。", py:"Tā de pàn duàn tài zhǔ guān, quē fá yī jù.",fr:"Son jugement est trop subjectif et manque de fondement."},
"认知":    {zh:"儿童认知发展需要丰富的环境。",py:"Ér tóng rèn zhī fā zhǎn xū yào fēng fù de huán jìng.",fr:"Le développement cognitif des enfants nécessite un environnement riche."},
"意志":    {zh:"强大的意志力帮助他度过了困难。",py:"Qiáng dà de yì zhì lì bāng zhù tā dù guò le kùn nán.",fr:"Une forte volonté l'a aidé à surmonter les difficultés."},
"潜意识":  {zh:"梦境常常反映人的潜意识。",   py:"Mèng jìng cháng cháng fǎn yìng rén de qián yì shí.",fr:"Les rêves reflètent souvent l'inconscient."},
"情绪":    {zh:"他善于控制自己的情绪。",     py:"Tā shàn yú kòng zhì zì jǐ de qíng xù.",   fr:"Il est doué pour contrôler ses émotions."},
"动机":    {zh:"了解学习动机有助于提高效率。",py:"Liǎo jiě xué xí dòng jī yǒu zhù yú tí gāo xiào lǜ.",fr:"Comprendre la motivation d'apprentissage aide à améliorer l'efficacité."},
"焦虑":    {zh:"考试前很多学生会感到焦虑。", py:"Kǎo shì qián hěn duō xué shēng huì gǎn dào jiāo lǜ.",fr:"Avant les examens, beaucoup d'élèves ressentent de l'anxiété."},
"抑郁":    {zh:"抑郁症需要专业的心理治疗。", py:"Yì yù zhèng xū yào zhuān yè de xīn lǐ zhì liáo.",fr:"La dépression nécessite un traitement psychologique professionnel."},
"共情":    {zh:"共情能力让人更好地理解他人。",py:"Gòng qíng néng lì ràng rén gèng hǎo de lǐ jiě tā rén.",fr:"La capacité d'empathie permet de mieux comprendre les autres."},
"自我":    {zh:"认识自我是个人成长的起点。", py:"Rèn shì zì wǒ shì gè rén chéng zhǎng de qǐ diǎn.",fr:"Se connaître soi-même est le point de départ de la croissance personnelle."},
"立法":    {zh:"议会负责立法和修改法律。",   py:"Yì huì fù zé lì fǎ hé xiū gǎi fǎ lǜ.",   fr:"Le parlement est chargé de légiférer et de modifier les lois."},
"宪法":    {zh:"宪法是国家的根本大法。",     py:"Xiàn fǎ shì guó jiā de gēn běn dà fǎ.",   fr:"La constitution est la loi fondamentale de l'État."},
"主权":    {zh:"每个国家都有维护主权的权利。",py:"Měi gè guó jiā dōu yǒu wéi hù zhǔ quán de quán lì.",fr:"Chaque pays a le droit de défendre sa souveraineté."},
"选举":    {zh:"公民通过选举表达政治意愿。", py:"Gōng mín tōng guò xuǎn jǔ biǎo dá zhèng zhì yì yuàn.",fr:"Les citoyens expriment leur volonté politique par les élections."},
"改革":    {zh:"经济改革推动了国家发展。",   py:"Jīng jì gǎi gé tuī dòng le guó jiā fā zhǎn.",fr:"Les réformes économiques ont favorisé le développement national."},
"腐败":    {zh:"打击腐败是维护社会公正的关键。",py:"Dǎ jī fǔ bài shì wéi hù shè huì gōng zhèng de guān jiàn.",fr:"Lutter contre la corruption est essentiel pour maintenir la justice sociale."},
"透明度":  {zh:"政府决策需要更高的透明度。", py:"Zhèng fǔ jué cè xū yào gèng gāo de tòu míng dù.",fr:"Les décisions gouvernementales nécessitent une plus grande transparence."},
"问责":    {zh:"公众要求对官员进行问责。",   py:"Gōng zhòng yāo qiú duì guān yuán jìn xíng wèn zé.",fr:"Le public exige que les fonctionnaires soient tenus responsables."},
"货币":    {zh:"人民币是中国的法定货币。",   py:"Rén mín bì shì Zhōng guó de fǎ dìng huò bì.",fr:"Le renminbi est la monnaie légale de Chine."},
"汇率":    {zh:"汇率变化影响国际贸易。",     py:"Huì lǜ biàn huà yǐng xiǎng guó jì mào yì.",fr:"Les variations du taux de change influencent le commerce international."},
"赤字":    {zh:"政府预算赤字需要谨慎应对。", py:"Zhèng fǔ yù suàn chì zì xū yào jǐn shèn yìng duì.",fr:"Le déficit budgétaire gouvernemental doit être géré avec prudence."},
"垄断":    {zh:"反垄断法防止市场被少数控制。",py:"Fǎn lǒng duàn fǎ fáng zhǐ shì chǎng bèi shǎo shù kòng zhì.",fr:"La loi antitrust empêche que le marché soit contrôlé par une minorité."},
"金融":    {zh:"金融危机对全球经济影响深远。",py:"Jīn róng wēi jī duì quán qiú jīng jì yǐng xiǎng shēn yuǎn.",fr:"La crise financière a un impact profond sur l'économie mondiale."},
"资本主义":{zh:"资本主义制度强调市场竞争。", py:"Zī běn zhǔ yì zhì dù qiáng diào shì chǎng jìng zhēng.",fr:"Le système capitaliste met l'accent sur la concurrence du marché."},
"基因工程":{zh:"基因工程为医学带来了革命性突破。",py:"Jī yīn gōng chéng wèi yī xué dài lái le gé mìng xìng tū pò.",fr:"Le génie génétique a apporté des percées révolutionnaires à la médecine."},
"量子计算":{zh:"量子计算将彻底改变信息处理方式。",py:"Liàng zǐ jì suàn jiāng chè dǐ gǎi biàn xìn xī chǔ lǐ fāng shì.",fr:"L'informatique quantique va transformer fondamentalement le traitement de l'information."},
"神经网络":{zh:"深度学习依赖于神经网络模型。", py:"Shēn dù xué xí yī lài yú shén jīng wǎng luò mó xíng.",fr:"L'apprentissage profond repose sur des modèles de réseaux neuronaux."},
"区块链":  {zh:"区块链技术保证数据不可篡改。",py:"Qū kuài liàn jì shù bǎo zhèng shù jù bù kě cuàn gǎi.",fr:"La technologie blockchain garantit l'immuabilité des données."},
"虚拟现实":{zh:"虚拟现实技术改变了娱乐方式。",py:"Xū nǐ xiàn shí jì shù gǎi biàn le yú lè fāng shì.",fr:"La technologie de réalité virtuelle a transformé les loisirs."},
"深度学习":{zh:"深度学习是人工智能的核心技术。",py:"Shēn dù xué xí shì rén gōng zhì néng de hé xīn jì shù.",fr:"L'apprentissage profond est la technologie centrale de l'intelligence artificielle."},
"叙事":    {zh:"这部小说的叙事方式很独特。", py:"Zhè bù xiǎo shuō de xù shì fāng shì hěn dú tè.",fr:"La façon de narrer de ce roman est très originale."},
"隐喻":    {zh:"他用隐喻表达了深刻的思想。", py:"Tā yòng yǐn yù biǎo dá le shēn kè de sī xiǎng.",fr:"Il a exprimé des idées profondes par des métaphores."},
"象征":    {zh:"鸽子象征着和平。",           py:"Gē zi xiàng zhēng zhe hé píng.",            fr:"La colombe symbolise la paix."},
"讽刺":    {zh:"这首诗用讽刺手法批评社会现象。",py:"Zhè shǒu shī yòng fěng cì shǒu fǎ pī píng shè huì xiàn xiàng.",fr:"Ce poème critique des phénomènes sociaux par la satire."},
"修辞":    {zh:"修辞技巧使文章更有说服力。", py:"Xiū cí jì qiǎo shǐ wén zhāng gèng yǒu shuō fú lì.",fr:"Les techniques rhétoriques rendent les textes plus persuasifs."},
"风格":    {zh:"每位作家都有自己独特的风格。",py:"Měi wèi zuò jiā dōu yǒu zì jǐ dú tè de fēng gé.",fr:"Chaque écrivain a son style unique."},
"生物多样性":{zh:"保护生物多样性对地球至关重要。",py:"Bǎo hù shēng wù duō yàng xìng duì dì qiú zhì guān zhòng yào.",fr:"Protéger la biodiversité est crucial pour la Terre."},
"物种":    {zh:"每年都有物种因栖息地破坏而灭绝。",py:"Měi nián dōu yǒu wù zhǒng yīn qī xī dì pò huài ér miè jué.",fr:"Chaque année, des espèces s'éteignent à cause de la destruction de leur habitat."},
"碳中和":  {zh:"实现碳中和需要各国共同努力。",py:"Shí xiàn tàn zhōng hé xū yào gè guó gòng tóng nǔ lì.",fr:"Atteindre la neutralité carbone nécessite les efforts communs de tous les pays."},
"生态系统":{zh:"湿地生态系统为许多动植物提供家园。",py:"Shī dì shēng tài xì tǒng wèi xǔ duō dòng zhí wù tí gōng jiā yuán.",fr:"L'écosystème des zones humides fournit un habitat à de nombreux animaux et plantes."},
"沙漠化":  {zh:"过度开发导致部分地区沙漠化加剧。",py:"Guò dù kāi fā dǎo zhì bù fèn dì qū shā mò huà jiā jù.",fr:"Le surexploitation intensifie la désertification dans certaines régions."},
"海平面":  {zh:"气候变化导致海平面不断上升。",py:"Qì hòu biàn huà dǎo zhì hǎi píng miàn bù duàn shàng shēng.",fr:"Le changement climatique entraîne une montée continue du niveau de la mer."},
"城镇化":  {zh:"快速城镇化带来了人口聚集的挑战。",py:"Kuài sù chéng zhèn huà dài lái le rén kǒu jù jí de tiǎo zhàn.",fr:"L'urbanisation rapide entraîne des défis liés à la concentration de la population."},
"贫困":    {zh:"消除贫困是联合国的重要目标。",py:"Xiāo chú pín kùn shì Lián hé guó de zhòng yào mù biāo.",fr:"L'élimination de la pauvreté est un objectif important des Nations Unies."},
"不平等":  {zh:"经济不平等加剧了社会矛盾。",  py:"Jīng jì bù píng děng jiā jù le shè huì máo dùn.",fr:"Les inégalités économiques aggravent les contradictions sociales."},
"歧视":    {zh:"任何形式的种族歧视都是不可接受的。",py:"Rèn hé xíng shì de zhǒng zú qí shì dōu shì bù kě jiē shòu de.",fr:"Toute forme de discrimination raciale est inacceptable."},
"包容":    {zh:"多元社会需要包容不同的文化。",py:"Duō yuán shè huì xū yào bāo róng bù tóng de wén huà.",fr:"Une société plurielle doit être inclusive envers différentes cultures."},
"多元化":  {zh:"团队多元化有助于激发创新思维。",py:"Tuán duì duō yuán huà yǒu zhù yú jī fā chuàng xīn sī wéi.",fr:"La diversité des équipes favorise la pensée innovante."},
"企业家":  {zh:"成功的企业家敢于承担风险。",  py:"Chéng gōng de qǐ yè jiā gǎn yú chéng dān fēng xiǎn.",fr:"Les entrepreneurs qui réussissent osent prendre des risques."},
"初创":    {zh:"这家初创公司发展非常迅速。",  py:"Zhè jiā chū chuàng gōng sī fā zhǎn fēi cháng xùn sù.",fr:"Cette startup se développe très rapidement."},
"品牌":    {zh:"建立品牌需要长时间的积累。",  py:"Jiàn lì pǐn pái xū yào cháng shí jiān de jī lěi.",fr:"Construire une marque nécessite une longue accumulation."},
"营销":    {zh:"社交媒体已成为重要的营销渠道。",py:"Shè jiāo méi tǐ yǐ chéng wéi zhòng yào de yíng xiāo qú dào.",fr:"Les réseaux sociaux sont devenus un canal marketing important."},
"供应链":  {zh:"疫情暴露了全球供应链的脆弱性。",py:"Yì qíng bào lù le quán qiú gōng yìng liàn de cuì ruò xìng.",fr:"La pandémie a révélé la fragilité des chaînes d'approvisionnement mondiales."},
"商业模式":{zh:"创新的商业模式颠覆了传统行业。",py:"Chuàng xīn de shāng yè mó shì diān fù le chuán tǒng háng yè.",fr:"Les modèles économiques innovants ont bouleversé les secteurs traditionnels."}

};
