var data = {
yct1:{label:"YCT 1",lc:"l1",icon:"🟢",desc:"Débutant absolu",words:[
["你好","nǐ hǎo","Bonjour","Salutations"],["谢谢","xiè xie","Merci","Salutations"],
["再见","zài jiàn","Au revoir","Salutations"],["对不起","duì bu qǐ","Pardon / Désolé","Salutations"],
["不客气","bù kè qi","De rien","Salutations"],["没关系","méi guān xi","Ce n'est pas grave","Salutations"],
["我","wǒ","Je / Moi","Pronoms"],["你","nǐ","Tu / Toi","Pronoms"],["他","tā","Il / Lui","Pronoms"],
["她","tā","Elle","Pronoms"],["我们","wǒ men","Nous","Pronoms"],["你们","nǐ men","Vous","Pronoms"],["他们","tā men","Ils / Eux","Pronoms"],
["零","líng","Zéro","Chiffres"],["一","yī","Un","Chiffres"],["二","èr","Deux","Chiffres"],["三","sān","Trois","Chiffres"],
["四","sì","Quatre","Chiffres"],["五","wǔ","Cinq","Chiffres"],["六","liù","Six","Chiffres"],["七","qī","Sept","Chiffres"],
["八","bā","Huit","Chiffres"],["九","jiǔ","Neuf","Chiffres"],["十","shí","Dix","Chiffres"],["百","bǎi","Cent","Chiffres"],["千","qiān","Mille","Chiffres"],
["爸爸","bà ba","Papa","Famille"],["妈妈","mā ma","Maman","Famille"],["哥哥","gē ge","Grand frère","Famille"],
["姐姐","jiě jie","Grande sœur","Famille"],["弟弟","dì di","Petit frère","Famille"],["妹妹","mèi mei","Petite sœur","Famille"],
["老师","lǎo shī","Professeur","Personnes"],["同学","tóng xué","Camarade de classe","Personnes"],["朋友","péng you","Ami(e)","Personnes"],
["猫","māo","Chat","Animaux"],["狗","gǒu","Chien","Animaux"],["鸟","niǎo","Oiseau","Animaux"],["鱼","yú","Poisson","Animaux"],["马","mǎ","Cheval","Animaux"],
["苹果","píng guǒ","Pomme","Nourriture"],["水","shuǐ","Eau","Nourriture"],["米饭","mǐ fàn","Riz","Nourriture"],["面条","miàn tiáo","Nouilles","Nourriture"],["好吃","hǎo chī","Délicieux","Nourriture"],
["大","dà","Grand","Adjectifs"],["小","xiǎo","Petit","Adjectifs"],["好","hǎo","Bon / Bien","Adjectifs"],["多","duō","Beaucoup","Adjectifs"],
["高兴","gāo xìng","Content / Joyeux","Adjectifs"],["漂亮","piào liang","Joli / Beau","Adjectifs"],["高","gāo","Grand / Haut","Adjectifs"],
["今天","jīn tiān","Aujourd'hui","Temps"],["明天","míng tiān","Demain","Temps"],["昨天","zuó tiān","Hier","Temps"],
["年","nián","An / Année","Temps"],["月","yuè","Mois","Temps"],["日","rì","Jour (date)","Temps"],["星期","xīng qī","Semaine","Temps"],
["去","qù","Aller","Verbes"],["来","lái","Venir","Verbes"],["看","kàn","Regarder","Verbes"],
["吃","chī","Manger","Verbes"],["喝","hē","Boire","Verbes"],["说","shuō","Parler","Verbes"],
["叫","jiào","S'appeler","Verbes"],["有","yǒu","Avoir","Verbes"],["没有","méi yǒu","Ne pas avoir","Verbes"],
["是","shì","Être","Verbes"],["在","zài","Être à","Verbes"],["学","xué","Apprendre","Verbes"],
["什么","shén me","Quoi / Quel","Questions"],["谁","shéi","Qui","Questions"],["哪","nǎ","Lequel","Questions"],
["几","jǐ","Combien (petit nb)","Questions"],["多少","duō shao","Combien","Questions"],
["这","zhè","Ceci","Démonstratifs"],["那","nà","Cela","Démonstratifs"],
["不","bù","Non / Ne pas","Particules"],["书","shū","Livre","École"],["中国","zhōng guó","Chine","Pays"]
]},
yct2:{label:"YCT 2",lc:"l2",icon:"🔵",desc:"Élémentaire",words:[
["学校","xué xiào","École","Lieux"],["家","jiā","Maison","Lieux"],["医院","yī yuàn","Hôpital","Lieux"],
["商店","shāng diàn","Magasin","Lieux"],["公园","gōng yuán","Parc","Lieux"],["饭馆","fàn guǎn","Restaurant","Lieux"],
["教室","jiào shì","Salle de classe","Lieux"],["超市","chāo shì","Supermarché","Lieux"],
["喜欢","xǐ huān","Aimer","Verbes"],["想","xiǎng","Vouloir / Penser","Verbes"],["知道","zhī dào","Savoir","Verbes"],
["听","tīng","Écouter","Verbes"],["写","xiě","Écrire","Verbes"],["读","dú","Lire","Verbes"],
["做","zuò","Faire","Verbes"],["玩","wán","Jouer","Verbes"],["睡觉","shuì jiào","Dormir","Verbes"],
["起床","qǐ chuáng","Se lever","Verbes"],["坐","zuò","S'asseoir","Verbes"],["走","zǒu","Marcher","Verbes"],
["买","mǎi","Acheter","Verbes"],["卖","mài","Vendre","Verbes"],["跑","pǎo","Courir","Verbes"],
["站","zhàn","Se tenir debout","Verbes"],["回","huí","Rentrer","Verbes"],["唱","chàng","Chanter","Verbes"],
["画","huà","Dessiner","Verbes"],["打电话","dǎ diàn huà","Téléphoner","Verbes"],["回答","huí dá","Répondre","Verbes"],
["星期一","xīng qī yī","Lundi","Jours"],["星期二","xīng qī èr","Mardi","Jours"],["星期三","xīng qī sān","Mercredi","Jours"],
["星期四","xīng qī sì","Jeudi","Jours"],["星期五","xīng qī wǔ","Vendredi","Jours"],["星期六","xīng qī liù","Samedi","Jours"],["星期天","xīng qī tiān","Dimanche","Jours"],
["早上","zǎo shang","Matin","Temps"],["上午","shàng wǔ","Matinée","Temps"],["中午","zhōng wǔ","Midi","Temps"],
["下午","xià wǔ","Après-midi","Temps"],["晚上","wǎn shang","Soir","Temps"],["现在","xiàn zài","Maintenant","Temps"],
["以前","yǐ qián","Avant","Temps"],["以后","yǐ hòu","Après","Temps"],
["鸡蛋","jī dàn","Œuf","Nourriture"],["牛奶","niú nǎi","Lait","Nourriture"],["茶","chá","Thé","Nourriture"],
["果汁","guǒ zhī","Jus de fruit","Nourriture"],["面包","miàn bāo","Pain","Nourriture"],["饺子","jiǎo zi","Raviolis","Nourriture"],
["肉","ròu","Viande","Nourriture"],["蔬菜","shū cài","Légumes","Nourriture"],["香蕉","xiāng jiāo","Banane","Nourriture"],
["西瓜","xī guā","Pastèque","Nourriture"],["葡萄","pú tao","Raisin","Nourriture"],["橙子","chéng zi","Orange","Nourriture"],
["红色","hóng sè","Rouge","Couleurs"],["黄色","huáng sè","Jaune","Couleurs"],["蓝色","lán sè","Bleu","Couleurs"],
["绿色","lǜ sè","Vert","Couleurs"],["白色","bái sè","Blanc","Couleurs"],["黑色","hēi sè","Noir","Couleurs"],["粉色","fěn sè","Rose","Couleurs"],
["热","rè","Chaud","Adjectifs"],["冷","lěng","Froid","Adjectifs"],["贵","guì","Cher","Adjectifs"],
["便宜","pián yi","Bon marché","Adjectifs"],["新","xīn","Nouveau","Adjectifs"],["旧","jiù","Vieux","Adjectifs"],
["快","kuài","Rapide","Adjectifs"],["慢","màn","Lent","Adjectifs"],["长","cháng","Long","Adjectifs"],
["短","duǎn","Court","Adjectifs"],["难","nán","Difficile","Adjectifs"],["容易","róng yì","Facile","Adjectifs"],
["汽车","qì chē","Voiture","Transports"],["公共汽车","gōng gòng qì chē","Bus","Transports"],["自行车","zì xíng chē","Vélo","Transports"],
["火车","huǒ chē","Train","Transports"],["飞机","fēi jī","Avion","Transports"],
["头","tóu","Tête","Corps"],["眼睛","yǎn jīng","Yeux","Corps"],["鼻子","bí zi","Nez","Corps"],
["嘴","zuǐ","Bouche","Corps"],["耳朵","ěr duo","Oreille","Corps"],["手","shǒu","Main","Corps"],["脚","jiǎo","Pied","Corps"],
["天气","tiān qì","Météo","Météo"],["晴天","qíng tiān","Ensoleillé","Météo"],
["下雨","xià yǔ","Pleuvoir","Météo"],["下雪","xià xuě","Neiger","Météo"],["风","fēng","Vent","Météo"],
["爷爷","yé ye","Grand-père (paternel)","Famille"],["奶奶","nǎi nai","Grand-mère (paternelle)","Famille"],
["外公","wài gōng","Grand-père (maternel)","Famille"],["外婆","wài pó","Grand-mère (maternelle)","Famille"],["儿子","ér zi","Fils","Famille"],
["音乐","yīn yuè","Musique","Loisirs"],["电影","diàn yǐng","Film / Cinéma","Loisirs"],
["运动","yùn dòng","Sport","Loisirs"],["游泳","yóu yǒng","Nager","Loisirs"],["足球","zú qiú","Football","Loisirs"],
["也","yě","Aussi","Adverbes"],["都","dōu","Tous","Adverbes"],["很","hěn","Très","Adverbes"],
["太","tài","Trop","Adverbes"],["非常","fēi cháng","Extrêmement","Adverbes"],["一起","yī qǐ","Ensemble","Adverbes"],
["上面","shàng miàn","Dessus","Positions"],["下面","xià miàn","Dessous","Positions"],
["前面","qián miàn","Devant","Positions"],["后面","hòu miàn","Derrière","Positions"],
["名字","míng zi","Prénom / Nom","Divers"],["电话","diàn huà","Téléphone","Divers"],["电脑","diàn nǎo","Ordinateur","Divers"],
["钱","qián","Argent","Divers"],["时间","shí jiān","Temps / Heure","Divers"],["衣服","yī fu","Vêtements","Divers"],
["桌子","zhuō zi","Table","Divers"],["椅子","yǐ zi","Chaise","Divers"],["床","chuáng","Lit","Divers"],
["照片","zhào piàn","Photo","Divers"],["礼物","lǐ wù","Cadeau","Divers"],["节日","jié rì","Fête","Divers"],
["汉语","hàn yǔ","Chinois (langue)","Divers"]
]},
yct3:{label:"YCT 3",lc:"l3",icon:"🟣",desc:"Intermédiaire",words:[
["城市","chéng shì","Ville","Lieux"],["农村","nóng cūn","Campagne","Lieux"],["机场","jī chǎng","Aéroport","Lieux"],
["火车站","huǒ chē zhàn","Gare","Lieux"],["银行","yín háng","Banque","Lieux"],["图书馆","tú shū guǎn","Bibliothèque","Lieux"],
["饭店","fàn diàn","Hôtel / Restaurant","Lieux"],["博物馆","bó wù guǎn","Musée","Lieux"],
["工作","gōng zuò","Travail","Professions"],["工程师","gōng chéng shī","Ingénieur","Professions"],["经理","jīng lǐ","Directeur","Professions"],
["律师","lǜ shī","Avocat","Professions"],["护士","hù shi","Infirmier/ière","Professions"],["警察","jǐng chá","Policier","Professions"],
["司机","sī jī","Chauffeur","Professions"],["厨师","chú shī","Cuisinier","Professions"],["演员","yǎn yuán","Acteur","Professions"],
["旅游","lǚ yóu","Tourisme","Voyages"],["护照","hù zhào","Passeport","Voyages"],["行李","xíng li","Bagages","Voyages"],
["地图","dì tú","Carte / Plan","Voyages"],["签证","qiān zhèng","Visa","Voyages"],["出发","chū fā","Départ","Voyages"],
["到达","dào dá","Arrivée","Voyages"],["旅行","lǚ xíng","Voyage","Voyages"],
["气候","qì hòu","Climat","Nature"],["山","shān","Montagne","Nature"],["河","hé","Rivière","Nature"],
["海","hǎi","Mer","Nature"],["森林","sēn lín","Forêt","Nature"],["花","huā","Fleur","Nature"],
["树","shù","Arbre","Nature"],["天空","tiān kōng","Ciel","Nature"],["月亮","yuè liang","Lune","Nature"],
["春天","chūn tiān","Printemps","Saisons"],["夏天","xià tiān","Été","Saisons"],["秋天","qiū tiān","Automne","Saisons"],["冬天","dōng tiān","Hiver","Saisons"],
["生病","shēng bìng","Être malade","Santé"],["头疼","tóu téng","Mal de tête","Santé"],
["发烧","fā shāo","Fièvre","Santé"],["药","yào","Médicament","Santé"],
["休息","xiū xi","Se reposer","Santé"],["健康","jiàn kāng","Santé","Santé"],["感冒","gǎn mào","Rhume","Santé"],
["因为","yīn wèi","Parce que","Connecteurs"],["所以","suǒ yǐ","Donc","Connecteurs"],["虽然","suī rán","Bien que","Connecteurs"],
["但是","dàn shì","Mais","Connecteurs"],["如果","rú guǒ","Si (cond.)","Connecteurs"],["而且","ér qiě","De plus","Connecteurs"],
["可以","kě yǐ","Pouvoir","Auxiliaires"],["应该","yīng gāi","Devoir","Auxiliaires"],
["必须","bì xū","Devoir absolument","Auxiliaires"],["能","néng","Capable de","Auxiliaires"],["要","yào","Vouloir","Auxiliaires"],
["了解","liǎo jiě","Comprendre","Verbes"],["介绍","jiè shào","Présenter","Verbes"],["参加","cān jiā","Participer","Verbes"],
["准备","zhǔn bèi","Préparer","Verbes"],["解决","jiě jué","Résoudre","Verbes"],["发现","fā xiàn","Découvrir","Verbes"],
["决定","jué dìng","Décider","Verbes"],["选择","xuǎn zé","Choisir","Verbes"],
["危险","wēi xiǎn","Dangereux","Adjectifs"],["安全","ān quán","Sûr","Adjectifs"],["简单","jiǎn dān","Simple","Adjectifs"],
["复杂","fù zá","Complexe","Adjectifs"],["方便","fāng biàn","Pratique","Adjectifs"],
["有名","yǒu míng","Célèbre","Adjectifs"],["认真","rèn zhēn","Sérieux","Adjectifs"],
["丈夫","zhàng fu","Mari","Relations"],["妻子","qī zi","Épouse","Relations"],["父母","fù mǔ","Parents","Relations"],
["孩子","hái zi","Enfant","Relations"],["邻居","lín jū","Voisin","Relations"],["同事","tóng shì","Collègue","Relations"],
["文化","wén huà","Culture","Société"],["历史","lì shǐ","Histoire","Société"],["经济","jīng jì","Économie","Société"],
["社会","shè huì","Société","Société"],["教育","jiào yù","Éducation","Société"],["科技","kē jì","Technologie","Société"],
["认识","rèn shi","Connaître","Verbes"],["帮助","bāng zhù","Aider","Verbes"],["告诉","gào su","Dire / Informer","Verbes"],
["希望","xī wàng","Espérer","Verbes"],["注意","zhù yì","Faire attention","Verbes"],["觉得","jué de","Trouver / Penser","Verbes"],
["需要","xū yào","Avoir besoin","Verbes"],["完成","wán chéng","Accomplir","Verbes"],["开始","kāi shǐ","Commencer","Verbes"],
["结束","jié shù","Terminer","Verbes"],["忘记","wàng jì","Oublier","Verbes"],["记得","jì de","Se souvenir","Verbes"],
["使用","shǐ yòng","Utiliser","Verbes"],["打算","dǎ suàn","Avoir l'intention de","Verbes"],["借","jiè","Emprunter / Prêter","Verbes"],
["换","huàn","Changer / Échanger","Verbes"],["找","zhǎo","Chercher","Verbes"],["送","sòng","Offrir / Accompagner","Verbes"],
["联系","lián xì","Contacter","Verbes"],["继续","jì xù","Continuer","Verbes"],["放","fàng","Poser / Mettre","Verbes"],
["拿","ná","Prendre / Porter","Verbes"],["解释","jiě shì","Expliquer","Verbes"],["比较","bǐ jiào","Comparer","Verbes"],
["担心","dān xīn","S'inquiéter","Verbes"],["相信","xiāng xìn","Croire","Verbes"],["改变","gǎi biàn","Changer","Verbes"],
["提高","tí gāo","Améliorer","Verbes"],["请","qǐng","Inviter / Prier","Verbes"],["带","dài","Apporter / Emmener","Verbes"],
["大家","dà jiā","Tout le monde","Personnes"],["别人","bié rén","Les autres","Personnes"],
["自己","zì jǐ","Soi-même","Personnes"],["客人","kè rén","Invité","Personnes"],["服务员","fú wù yuán","Serveur/Serveuse","Personnes"],
["地方","dì fāng","Endroit / Lieu","Lieux"],["附近","fù jìn","À proximité","Positions"],
["中间","zhōng jiān","Au milieu","Positions"],["旁边","páng biān","À côté","Positions"],
["左边","zuǒ biān","À gauche","Positions"],["右边","yòu biān","À droite","Positions"],
["外面","wài miàn","Dehors","Positions"],["里面","lǐ miàn","À l'intérieur","Positions"],
["时候","shí hou","Moment","Temps"],["最近","zuì jìn","Récemment","Temps"],
["刚才","gāng cái","Tout à l'heure","Temps"],["将来","jiāng lái","Avenir","Temps"],
["东西","dōng xi","Chose / Objet","Divers"],["事情","shì qing","Affaire / Chose","Divers"],
["问题","wèn tí","Problème / Question","Divers"],["机会","jī huì","Opportunité","Divers"],
["声音","shēng yīn","Son / Voix","Divers"],["方法","fāng fǎ","Méthode","Divers"],
["原因","yuán yīn","Raison / Cause","Divers"],["结果","jié guǒ","Résultat","Divers"],
["意思","yì si","Sens / Signification","Divers"],["信息","xìn xī","Information","Divers"],
["习惯","xí guàn","Habitude","Divers"],["计划","jì huà","Plan","Divers"],
["成绩","chéng jì","Résultats scolaires","École"],["作业","zuò yè","Devoirs","École"],["考试","kǎo shì","Examen","École"],
["裙子","qún zi","Jupe / Robe","Vêtements"],["裤子","kù zi","Pantalon","Vêtements"],
["鞋","xié","Chaussures","Vêtements"],["帽子","mào zi","Chapeau","Vêtements"],
["外套","wài tào","Manteau","Vêtements"],["袜子","wà zi","Chaussettes","Vêtements"],
["重要","zhòng yào","Important","Adjectifs"],["可爱","kě ài","Mignon / Adorable","Adjectifs"],
["特别","tè bié","Spécial / Particulier","Adjectifs"],["正确","zhèng què","Correct / Juste","Adjectifs"],
["有趣","yǒu qù","Intéressant / Amusant","Adjectifs"],["难过","nán guò","Triste","Adjectifs"],
["干净","gān jìng","Propre","Adjectifs"],["聪明","cōng míng","Intelligent","Adjectifs"],
["紧张","jǐn zhāng","Nerveux / Stressé","Adjectifs"],["舒服","shū fu","Confortable","Adjectifs"],
["累","lèi","Fatigué","Adjectifs"],["忙","máng","Occupé","Adjectifs"],
["年轻","nián qīng","Jeune","Adjectifs"],["普通","pǔ tōng","Ordinaire / Commun","Adjectifs"],
["开心","kāi xīn","Content / Joyeux","Adjectifs"],
["当然","dāng rán","Bien sûr","Adverbes"],["可能","kě néng","Peut-être / Possible","Adverbes"],
["一定","yī dìng","Certainement","Adverbes"],["其实","qí shí","En fait","Adverbes"],
["一直","yī zhí","Continuellement","Adverbes"],["怎么","zěn me","Comment","Adverbes"],
["已经","yǐ jīng","Déjà","Adverbes"],["还是","hái shì","Ou bien / Quand même","Adverbes"],
["总是","zǒng shì","Toujours","Adverbes"],["马上","mǎ shàng","Tout de suite","Adverbes"],
["尤其","yóu qí","Surtout","Adverbes"],["终于","zhōng yú","Enfin","Adverbes"],
["次","cì","Fois","Mesures"],["件","jiàn","Pièce (vêtement)","Mesures"],
["条","tiáo","Élément allongé","Mesures"],["双","shuāng","Paire","Mesures"],["瓶","píng","Bouteille","Mesures"]
]},
yct4:{label:"YCT 4",lc:"l4",icon:"🟠",desc:"Intermédiaire supérieur",words:[
["辩论","biàn lùn","Débattre","Communication"],["演讲","yǎn jiǎng","Discours","Communication"],
["表达","biǎo dá","Exprimer","Communication"],["交流","jiāo liú","Échanger","Communication"],
["描述","miáo shù","Décrire","Communication"],["说明","shuō míng","Expliquer","Communication"],
["强调","qiáng diào","Souligner","Communication"],["反驳","fǎn bó","Réfuter","Communication"],
["平等","píng děng","Égalité","Société"],["民主","mín zhǔ","Démocratie","Société"],
["自由","zì yóu","Liberté","Société"],["责任","zé rèn","Responsabilité","Société"],
["权利","quán lì","Droit","Société"],["义务","yì wù","Obligation","Société"],
["公平","gōng píng","Juste","Société"],["规则","guī zé","Règle","Société"],
["传统","chuán tǒng","Tradition","Société"],["习俗","xí sú","Coutume","Société"],
["投资","tóu zī","Investir","Économie"],["利润","lì rùn","Bénéfice","Économie"],
["市场","shì chǎng","Marché","Économie"],["消费","xiāo fèi","Consommer","Économie"],
["税收","shuì shōu","Impôts","Économie"],["预算","yù suàn","Budget","Économie"],
["通货膨胀","tōng huò péng zhàng","Inflation","Économie"],["贸易","mào yì","Commerce","Économie"],
["环境","huán jìng","Environnement","Nature"],["污染","wū rǎn","Pollution","Nature"],
["能源","néng yuán","Énergie","Nature"],["生态","shēng tài","Écologie","Nature"],
["气候变化","qì hòu biàn huà","Changement climatique","Nature"],["可再生","kě zài shēng","Renouvelable","Nature"],
["人工智能","rén gōng zhì néng","Intelligence artificielle","Science"],["机器人","jī qì rén","Robot","Science"],
["研究","yán jiū","Recherche","Science"],["实验","shí yàn","Expérience","Science"],
["发明","fā míng","Invention","Science"],["创新","chuàng xīn","Innovation","Science"],
["技术","jì shù","Technique","Science"],["数字化","shù zì huà","Numérique","Science"],
["文学","wén xué","Littérature","Arts"],["小说","xiǎo shuō","Roman","Arts"],
["诗歌","shī gē","Poésie","Arts"],["艺术","yì shù","Art","Arts"],
["绘画","huì huà","Peinture","Arts"],["音乐会","yīn yuè huì","Concert","Arts"],
["心理","xīn lǐ","Psychologie","Sciences humaines"],["哲学","zhé xué","Philosophie","Sciences humaines"],
["逻辑","luó jí","Logique","Sciences humaines"],["道德","dào dé","Éthique","Sciences humaines"],
["坚持","jiān chí","Persévérer","Caractère"],["勇气","yǒng qì","Courage","Caractère"],
["耐心","nài xīn","Patience","Caractère"],["谦虚","qiān xū","Humilité","Caractère"],
["诚实","chéng shí","Honnête","Caractère"],["积极","jī jí","Positif / Actif","Caractère"],
["乐观","lè guān","Optimiste","Caractère"],["悲观","bēi guān","Pessimiste","Caractère"],
["移民","yí mín","Immigration","Monde"],["全球化","quán qiú huà","Mondialisation","Monde"],
["国际","guó jì","International","Monde"],["冲突","chōng tū","Conflit","Monde"],
["和平","hé píng","Paix","Monde"],["战争","zhàn zhēng","Guerre","Monde"],
["影响","yǐng xiǎng","Influencer / Affecter","Verbes"],["支持","zhī chí","Soutenir","Verbes"],
["反对","fǎn duì","S'opposer","Verbes"],["实现","shí xiàn","Réaliser / Accomplir","Verbes"],
["建立","jiàn lì","Établir / Créer","Verbes"],["提供","tí gōng","Fournir","Verbes"],
["考虑","kǎo lǜ","Considérer","Verbes"],["面对","miàn duì","Faire face à","Verbes"],
["接受","jiē shòu","Accepter","Verbes"],["拒绝","jù jué","Refuser","Verbes"],
["承认","chéng rèn","Admettre / Reconnaître","Verbes"],["避免","bì miǎn","Éviter","Verbes"],
["合作","hé zuò","Coopérer","Verbes"],["批评","pī píng","Critiquer","Verbes"],
["分析","fēn xī","Analyser","Verbes"],["评价","píng jià","Évaluer","Verbes"],
["总结","zǒng jié","Résumer","Verbes"],["促进","cù jìn","Promouvoir","Verbes"],
["保护","bǎo hù","Protéger","Verbes"],["竞争","jìng zhēng","Concurrencer","Verbes"],
["政府","zhèng fǔ","Gouvernement","Gouvernance"],["法律","fǎ lǜ","Loi","Gouvernance"],
["制度","zhì dù","Système / Institution","Gouvernance"],["公民","gōng mín","Citoyen","Gouvernance"],
["政策","zhèng cè","Politique / Mesure","Gouvernance"],["权力","quán lì","Pouvoir","Gouvernance"],
["领导","lǐng dǎo","Direction / Leader","Gouvernance"],["组织","zǔ zhī","Organisation","Gouvernance"],
["企业","qǐ yè","Entreprise","Business"],["公司","gōng sī","Société / Compagnie","Business"],
["产品","chǎn pǐn","Produit","Business"],["价格","jià gé","Prix","Business"],
["质量","zhì liàng","Qualité","Business"],["资源","zī yuán","Ressource","Business"],
["合同","hé tóng","Contrat","Business"],["效率","xiào lǜ","Efficacité","Business"],
["大学","dà xué","Université","Éducation"],["专业","zhuān yè","Spécialité / Major","Éducation"],
["课程","kè chéng","Programme / Cours","Éducation"],["知识","zhī shì","Connaissance","Éducation"],
["能力","néng lì","Capacité","Éducation"],["水平","shuǐ píng","Niveau","Éducation"],
["成功","chéng gōng","Succès","Éducation"],["失败","shī bài","Échec","Éducation"],
["媒体","méi tǐ","Médias","Société"],["网络","wǎng luò","Réseau / Internet","Société"],
["平台","píng tái","Plateforme","Société"],["社区","shè qū","Communauté","Société"],
["矛盾","máo dùn","Contradiction / Conflit","Société"],["价值观","jià zhí guān","Valeurs","Société"],
["文明","wén míng","Civilisation","Société"],["舆论","yú lùn","Opinion publique","Société"],
["压力","yā lì","Pression / Stress","Psychologie"],["幸福","xìng fú","Bonheur","Psychologie"],
["信心","xìn xīn","Confiance en soi","Psychologie"],["动力","dòng lì","Motivation / Élan","Psychologie"],
["精神","jīng shén","Esprit / Mental","Psychologie"],
["严重","yán zhòng","Grave / Sérieux","Adjectifs"],["有效","yǒu xiào","Efficace","Adjectifs"],
["独立","dú lì","Indépendant","Adjectifs"],["共同","gòng tóng","Commun / Collectif","Adjectifs"],
["主动","zhǔ dòng","Proactif / Actif","Adjectifs"],["合理","hé lǐ","Raisonnable","Adjectifs"],
["关键","guān jiàn","Clé / Crucial","Adjectifs"],["广泛","guǎng fàn","Large / Répandu","Adjectifs"],
["深刻","shēn kè","Profond","Adjectifs"],["理性","lǐ xìng","Rationnel","Adjectifs"],
["尽管","jǐn guǎn","Bien que / Malgré","Adverbes"],["然而","rán ér","Cependant / Pourtant","Adverbes"],
["因此","yīn cǐ","Par conséquent","Adverbes"],["此外","cǐ wài","De plus / En outre","Adverbes"],
["逐渐","zhú jiàn","Progressivement","Adverbes"],["最终","zuì zhōng","Finalement","Adverbes"],
["总体","zǒng tǐ","Dans l'ensemble","Adverbes"]
]},
yct5:{label:"YCT 5",lc:"l5",icon:"🔴",desc:"Avancé",words:[
["抽象","chōu xiàng","Abstrait","Pensée"],["具体","jù tǐ","Concret","Pensée"],
["本质","běn zhì","Essence","Pensée"],["现象","xiàn xiàng","Phénomène","Pensée"],
["规律","guī lǜ","Loi naturelle","Pensée"],["假设","jiǎ shè","Hypothèse","Pensée"],
["推理","tuī lǐ","Raisonnement","Pensée"],["客观","kè guān","Objectif","Pensée"],
["主观","zhǔ guān","Subjectif","Pensée"],["认知","rèn zhī","Cognition","Pensée"],
["意志","yì zhì","Volonté","Psychologie"],["潜意识","qián yì shí","Inconscient","Psychologie"],
["情绪","qíng xù","État émotionnel","Psychologie"],["动机","dòng jī","Motivation","Psychologie"],
["焦虑","jiāo lǜ","Anxiété","Psychologie"],["抑郁","yì yù","Dépression","Psychologie"],
["共情","gòng qíng","Empathie","Psychologie"],["自我","zì wǒ","Soi-même","Psychologie"],
["立法","lì fǎ","Législation","Politique"],["宪法","xiàn fǎ","Constitution","Politique"],
["主权","zhǔ quán","Souveraineté","Politique"],["选举","xuǎn jǔ","Élection","Politique"],
["改革","gǎi gé","Réforme","Politique"],["腐败","fǔ bài","Corruption","Politique"],
["透明度","tòu míng dù","Transparence","Politique"],["问责","wèn zé","Responsabilisation","Politique"],
["货币","huò bì","Monnaie","Économie"],["汇率","huì lǜ","Taux de change","Économie"],
["赤字","chì zì","Déficit","Économie"],["垄断","lǒng duàn","Monopole","Économie"],
["金融","jīn róng","Finance","Économie"],["资本主义","zī běn zhǔ yì","Capitalisme","Économie"],
["基因工程","jī yīn gōng chéng","Génie génétique","Sciences"],["量子计算","liàng zǐ jì suàn","Informatique quantique","Sciences"],
["神经网络","shén jīng wǎng luò","Réseau neuronal","Sciences"],["区块链","qū kuài liàn","Blockchain","Sciences"],
["虚拟现实","xū nǐ xiàn shí","Réalité virtuelle","Sciences"],["深度学习","shēn dù xué xí","Apprentissage profond","Sciences"],
["叙事","xù shì","Narration","Littérature"],["隐喻","yǐn yù","Métaphore","Littérature"],
["象征","xiàng zhēng","Symbole","Littérature"],["讽刺","fěng cì","Satire","Littérature"],
["修辞","xiū cí","Rhétorique","Littérature"],["风格","fēng gé","Style","Littérature"],
["生物多样性","shēng wù duō yàng xìng","Biodiversité","Environnement"],["物种","wù zhǒng","Espèce","Environnement"],
["碳中和","tàn zhōng hé","Neutralité carbone","Environnement"],["生态系统","shēng tài xì tǒng","Écosystème","Environnement"],
["沙漠化","shā mò huà","Désertification","Environnement"],["海平面","hǎi píng miàn","Niveau de la mer","Environnement"],
["城镇化","chéng zhèn huà","Urbanisation","Sociologie"],["贫困","pín kùn","Pauvreté","Sociologie"],
["不平等","bù píng děng","Inégalité","Sociologie"],["歧视","qí shì","Discrimination","Sociologie"],
["包容","bāo róng","Inclusion","Sociologie"],["多元化","duō yuán huà","Diversité","Sociologie"],
["企业家","qǐ yè jiā","Entrepreneur","Business"],["初创","chū chuàng","Startup","Business"],
["品牌","pǐn pái","Marque","Business"],["营销","yíng xiāo","Marketing","Business"],
["供应链","gōng yìng liàn","Chaîne d'approvisionnement","Business"],["商业模式","shāng yè mó shì","Modèle économique","Business"],
["阐述","chǎn shù","Exposer / Développer","Verbes"],["论证","lùn zhèng","Démontrer / Argumenter","Verbes"],
["质疑","zhì yí","Remettre en question","Verbes"],["超越","chāo yuè","Dépasser / Transcender","Verbes"],
["制约","zhì yuē","Contraindre / Limiter","Verbes"],["颠覆","diān fù","Renverser / Subvertir","Verbes"],
["融合","róng hé","Fusionner / Intégrer","Verbes"],["重构","chóng gòu","Reconstruire","Verbes"],
["推动","tuī dòng","Propulser / Pousser","Verbes"],["优化","yōu huà","Optimiser","Verbes"],
["调控","diào kòng","Réguler / Contrôler","Verbes"],["整合","zhěng hé","Intégrer / Consolider","Verbes"],
["演化","yǎn huà","Évoluer","Verbes"],["驱动","qū dòng","Piloter / Conduire","Verbes"],
["渗透","shèn tòu","Pénétrer / Imprégner","Verbes"],
["危机","wēi jī","Crise","Concepts"],["结构","jié gòu","Structure","Concepts"],
["增长","zēng zhǎng","Croissance","Concepts"],["数据","shù jù","Données","Concepts"],
["算法","suàn fǎ","Algorithme","Concepts"],["模型","mó xíng","Modèle","Concepts"],
["指标","zhǐ biāo","Indicateur","Concepts"],["框架","kuāng jià","Cadre / Framework","Concepts"],
["共识","gòng shí","Consensus","Concepts"],["原则","yuán zé","Principe","Concepts"],
["范式","fàn shì","Paradigme","Concepts"],["悖论","bèi lùn","Paradoxe","Concepts"],
["批判","pī pàn","Critique / Remise en cause","Concepts"],["媒介","méi jiè","Médium / Intermédiaire","Concepts"],
["载体","zài tǐ","Vecteur / Support","Concepts"],
["可持续","kě chí xù","Durable","Adjectifs"],["全面","quán miàn","Complet / Global","Adjectifs"],
["综合","zōng hé","Synthétique / Intégré","Adjectifs"],["深远","shēn yuǎn","Profond et durable","Adjectifs"],
["微妙","wēi miào","Subtil / Délicat","Adjectifs"],["根本","gēn běn","Fondamental","Adjectifs"],
["关联","guān lián","Corrélé / Lié","Adjectifs"],["复合","fù hé","Composite / Mixte","Adjectifs"],
["显然","xiǎn rán","Évident / Manifeste","Adjectifs"],["系统","xì tǒng","Systématique","Adjectifs"],
["诚然","chéng rán","Certes / Il est vrai","Connecteurs"],["固然","gù rán","Certes / Sans doute","Connecteurs"],
["毕竟","bì jìng","Après tout","Connecteurs"],["况且","kuàng qiě","De plus / En outre","Connecteurs"],
["进而","jìn ér","En outre / Par là","Connecteurs"],["反之","fǎn zhī","À l'inverse","Connecteurs"],
["由此","yóu cǐ","De ce fait / Ainsi","Connecteurs"],["综上","zōng shàng","En résumé / Tout compte fait","Connecteurs"],
["换言之","huàn yán zhī","Autrement dit","Connecteurs"],["就此","jiù cǐ","À ce sujet / Là-dessus","Connecteurs"]
]}
};
Object.keys(data).forEach(function(k){
  data[k].words=data[k].words.map(function(a){return{h:a[0],p:a[1],fr:a[2],c:a[3]};});
});
