var data = {
yct1:{label:"YCT 1",lc:"l1",icon:"🟢",desc:"Débutant absolu",words:[
["你好","nǐ hǎo","Bonjour","Salutations"],["谢谢","xiè xie","Merci","Salutations"],
["再见","zài jiàn","Au revoir","Salutations"],["对不起","duì bu qǐ","Pardon / Désolé","Salutations"],
["不客气","bù kè qi","De rien","Salutations"],["没关系","méi guān xi","Ce n'est pas grave","Salutations"],
["我","wǒ","Je / Moi","Pronoms"],["你","nǐ","Tu / Toi","Pronoms"],["他","tā","Il / Lui","Pronoms"],
["她","tā","Elle","Pronoms"],["我们","wǒ men","Nous","Pronoms"],["你们","nǐ men","Vous","Pronoms"],["他们","tā men","Ils / Eux","Pronoms"],
["零","líng","Zéro","Chiffres"],["一","yī","Un","Chiffres"],["二","èr","Deux","Chiffres"],["三","sān","Trois","Chiffres"],
["四","sì","Quatre","Chiffres"],["五","wǔ","Cinq","Chiffres"],["六","liù","Six","Chiffres"],["七","qī","Sept","Chiffres"],
["八","bā","Huit","Chiffres"],["九","jiǔ","Neuf","Chiffres"],["十","shí","Dix","Chiffres"],["百","bǎi","Cent","Chiffres"],["千","qiān","Mille","Chiffres"],
["爸爸","bà ba","Papa","Famille"],["妈妈","mā ma","Maman","Famille"],["哥哥","gē ge","Grand frère","Famille"],
["姐姐","jiě jie","Grande sœur","Famille"],["弟弟","dì di","Petit frère","Famille"],["妹妹","mèi mei","Petite sœur","Famille"],
["老师","lǎo shī","Professeur","Personnes"],["同学","tóng xué","Camarade de classe","Personnes"],["朋友","péng you","Ami(e)","Personnes"],
["猫","māo","Chat","Animaux"],["狗","gǒu","Chien","Animaux"],["鸟","niǎo","Oiseau","Animaux"],["鱼","yú","Poisson","Animaux"],["马","mǎ","Cheval","Animaux"],
["苹果","píng guǒ","Pomme","Nourriture"],["水","shuǐ","Eau","Nourriture"],["米饭","mǐ fàn","Riz","Nourriture"],["面条","miàn tiáo","Nouilles","Nourriture"],["好吃","hǎo chī","Délicieux","Nourriture"],
["大","dà","Grand","Adjectifs"],["小","xiǎo","Petit","Adjectifs"],["好","hǎo","Bon / Bien","Adjectifs"],["多","duō","Beaucoup","Adjectifs"],
["高兴","gāo xìng","Content / Joyeux","Adjectifs"],["漂亮","piào liang","Joli / Beau","Adjectifs"],["高","gāo","Grand / Haut","Adjectifs"],
["今天","jīn tiān","Aujourd'hui","Temps"],["明天","míng tiān","Demain","Temps"],["昨天","zuó tiān","Hier","Temps"],
["年","nián","An / Année","Temps"],["月","yuè","Mois","Temps"],["日","rì","Jour (date)","Temps"],["星期","xīng qī","Semaine","Temps"],
["去","qù","Aller","Verbes"],["来","lái","Venir","Verbes"],["看","kàn","Regarder","Verbes"],
["吃","chī","Manger","Verbes"],["喝","hē","Boire","Verbes"],["说","shuō","Parler","Verbes"],
["叫","jiào","S'appeler","Verbes"],["有","yǒu","Avoir","Verbes"],["没有","méi yǒu","Ne pas avoir","Verbes"],
["是","shì","Être","Verbes"],["在","zài","Être à","Verbes"],["学","xué","Apprendre","Verbes"],
["什么","shén me","Quoi / Quel","Questions"],["谁","shéi","Qui","Questions"],["哪","nǎ","Lequel","Questions"],
["几","jǐ","Combien (petit nb)","Questions"],["多少","duō shao","Combien","Questions"],
["这","zhè","Ceci","Démonstratifs"],["那","nà","Cela","Démonstratifs"],
["不","bù","Non / Ne pas","Particules"],["书","shū","Livre","École"],["中国","zhōng guó","Chine","Pays"],
["个","gè","Classificateur général","Chiffres"],["两","liǎng","Deux (+ classificateur)","Chiffres"],
["岁","suì","An (âge)","Chiffres"],["号","hào","Numéro / Date","Chiffres"],
["点","diǎn","Heure (pile)","Chiffres"],["块","kuài","Yuan (monnaie)","Chiffres"],
["人","rén","Personne / Humain","Personnes"],["学生","xué shēng","Élève / Étudiant","Personnes"],
["男","nán","Homme / Masculin","Personnes"],["女","nǚ","Femme / Féminin","Personnes"],
["脸","liǎn","Visage","Corps"],
["熊猫","xióng māo","Panda","Animaux"],["兔子","tù zi","Lapin","Animaux"],
["老虎","lǎo hǔ","Tigre","Animaux"],["大象","dà xiàng","Éléphant","Animaux"],
["猴子","hóu zi","Singe","Animaux"],["牛","niú","Bœuf / Vache","Animaux"],
["羊","yáng","Mouton","Animaux"],["鸡","jī","Poule / Poulet","Animaux"],
["水果","shuǐ guǒ","Fruit","Nourriture"],["蛋糕","dàn gāo","Gâteau","Nourriture"],
["糖","táng","Bonbon / Sucre","Nourriture"],["汤","tāng","Soupe","Nourriture"],
["包子","bāo zi","Brioche farcie","Nourriture"],
["杯子","bēi zi","Verre / Tasse","Divers"],["门","mén","Porte","Divers"],
["电视","diàn shì","Télévision","Divers"],["手机","shǒu jī","Téléphone portable","Divers"],
["生日","shēng rì","Anniversaire","Divers"],["房间","fáng jiān","Chambre / Pièce","Divers"],
["书包","shū bāo","Cartable","École"],["铅笔","qiān bǐ","Crayon","École"],
["笔","bǐ","Stylo","École"],["本子","běn zi","Cahier","École"],
["汉字","hàn zì","Caractère chinois","École"],["课","kè","Cours / Leçon","École"],
["班","bān","Classe (groupe)","École"],
["爱","ài","Aimer","Verbes"],["开","kāi","Ouvrir / Conduire","Verbes"],
["关","guān","Fermer","Verbes"],["给","gěi","Donner","Verbes"],
["住","zhù","Habiter","Verbes"],["穿","chuān","Porter (vêtement)","Verbes"],
["洗","xǐ","Laver","Verbes"],["用","yòng","Utiliser","Verbes"],
["到","dào","Arriver","Verbes"],["会","huì","Savoir (faire)","Verbes"],
["问","wèn","Demander","Verbes"],["笑","xiào","Rire / Sourire","Verbes"],
["哭","kū","Pleurer","Verbes"],["跳","tiào","Sauter / Danser","Verbes"],
["少","shǎo","Peu","Adjectifs"],["矮","ǎi","Petit (taille)","Adjectifs"],
["胖","pàng","Gros","Adjectifs"],["瘦","shòu","Mince","Adjectifs"],
["快乐","kuài lè","Heureux","Adjectifs"],["老","lǎo","Vieux / Âgé","Adjectifs"],
["远","yuǎn","Loin","Adjectifs"],["近","jìn","Proche","Adjectifs"],
["太阳","tài yáng","Soleil","Nature"],["星星","xīng xing","Étoile","Nature"],
["云","yún","Nuage","Nature"],
["分钟","fēn zhōng","Minute","Temps"],["天","tiān","Jour","Temps"],
["哪儿","nǎr","Où","Questions"],["为什么","wèi shén me","Pourquoi","Questions"],
["吗","ma","Particule interrogative","Particules"],["呢","ne","Particule (et... ?)","Particules"],
["北京","běi jīng","Pékin","Pays"]
]},
yct2:{label:"YCT 2",lc:"l2",icon:"🔵",desc:"Élémentaire",words:[
["学校","xué xiào","École","Lieux"],["家","jiā","Maison","Lieux"],["医院","yī yuàn","Hôpital","Lieux"],
["商店","shāng diàn","Magasin","Lieux"],["公园","gōng yuán","Parc","Lieux"],["饭馆","fàn guǎn","Restaurant","Lieux"],
["教室","jiào shì","Salle de classe","Lieux"],["超市","chāo shì","Supermarché","Lieux"],
["喜欢","xǐ huān","Aimer","Verbes"],["想","xiǎng","Vouloir / Penser","Verbes"],["知道","zhī dào","Savoir","Verbes"],
["听","tīng","Écouter","Verbes"],["写","xiě","Écrire","Verbes"],["读","dú","Lire","Verbes"],
["做","zuò","Faire","Verbes"],["玩","wán","Jouer","Verbes"],["睡觉","shuì jiào","Dormir","Verbes"],
["起床","qǐ chuáng","Se lever","Verbes"],["坐","zuò","S'asseoir","Verbes"],["走","zǒu","Marcher","Verbes"],
["买","mǎi","Acheter","Verbes"],["卖","mài","Vendre","Verbes"],["跑","pǎo","Courir","Verbes"],
["站","zhàn","Se tenir debout","Verbes"],["回","huí","Rentrer","Verbes"],["唱","chàng","Chanter","Verbes"],
["画","huà","Dessiner","Verbes"],["打电话","dǎ diàn huà","Téléphoner","Verbes"],["回答","huí dá","Répondre","Verbes"],
["星期一","xīng qī yī","Lundi","Jours"],["星期二","xīng qī èr","Mardi","Jours"],["星期三","xīng qī sān","Mercredi","Jours"],
["星期四","xīng qī sì","Jeudi","Jours"],["星期五","xīng qī wǔ","Vendredi","Jours"],["星期六","xīng qī liù","Samedi","Jours"],["星期天","xīng qī tiān","Dimanche","Jours"],
["早上","zǎo shang","Matin","Temps"],["上午","shàng wǔ","Matinée","Temps"],["中午","zhōng wǔ","Midi","Temps"],
["下午","xià wǔ","Après-midi","Temps"],["晚上","wǎn shang","Soir","Temps"],["现在","xiàn zài","Maintenant","Temps"],
["以前","yǐ qián","Avant","Temps"],["以后","yǐ hòu","Après","Temps"],
["鸡蛋","jī dàn","Œuf","Nourriture"],["牛奶","niú nǎi","Lait","Nourriture"],["茶","chá","Thé","Nourriture"],
["果汁","guǒ zhī","Jus de fruit","Nourriture"],["面包","miàn bāo","Pain","Nourriture"],["饺子","jiǎo zi","Raviolis","Nourriture"],
["肉","ròu","Viande","Nourriture"],["蔬菜","shū cài","Légumes","Nourriture"],["香蕉","xiāng jiāo","Banane","Nourriture"],
["西瓜","xī guā","Pastèque","Nourriture"],["葡萄","pú tao","Raisin","Nourriture"],["橙子","chéng zi","Orange","Nourriture"],
["红色","hóng sè","Rouge","Couleurs"],["黄色","huáng sè","Jaune","Couleurs"],["蓝色","lán sè","Bleu","Couleurs"],
["绿色","lǜ sè","Vert","Couleurs"],["白色","bái sè","Blanc","Couleurs"],["黑色","hēi sè","Noir","Couleurs"],["粉色","fěn sè","Rose","Couleurs"],
["热","rè","Chaud","Adjectifs"],["冷","lěng","Froid","Adjectifs"],["贵","guì","Cher","Adjectifs"],
["便宜","pián yi","Bon marché","Adjectifs"],["新","xīn","Nouveau","Adjectifs"],["旧","jiù","Vieux","Adjectifs"],
["快","kuài","Rapide","Adjectifs"],["慢","màn","Lent","Adjectifs"],["长","cháng","Long","Adjectifs"],
["短","duǎn","Court","Adjectifs"],["难","nán","Difficile","Adjectifs"],["容易","róng yì","Facile","Adjectifs"],
["汽车","qì chē","Voiture","Transports"],["公共汽车","gōng gòng qì chē","Bus","Transports"],["自行车","zì xíng chē","Vélo","Transports"],
["火车","huǒ chē","Train","Transports"],["飞机","fēi jī","Avion","Transports"],
["头","tóu","Tête","Corps"],["眼睛","yǎn jīng","Yeux","Corps"],["鼻子","bí zi","Nez","Corps"],
["嘴","zuǐ","Bouche","Corps"],["耳朵","ěr duo","Oreille","Corps"],["手","shǒu","Main","Corps"],["脚","jiǎo","Pied","Corps"],
["天气","tiān qì","Météo","Météo"],["晴天","qíng tiān","Ensoleillé","Météo"],
["下雨","xià yǔ","Pleuvoir","Météo"],["下雪","xià xuě","Neiger","Météo"],["风","fēng","Vent","Météo"],
["爷爷","yé ye","Grand-père (paternel)","Famille"],["奶奶","nǎi nai","Grand-mère (paternelle)","Famille"],
["外公","wài gōng","Grand-père (maternel)","Famille"],["外婆","wài pó","Grand-mère (maternelle)","Famille"],["儿子","ér zi","Fils","Famille"],
["音乐","yīn yuè","Musique","Loisirs"],["电影","diàn yǐng","Film / Cinéma","Loisirs"],
["运动","yùn dòng","Sport","Loisirs"],["游泳","yóu yǒng","Nager","Loisirs"],["足球","zú qiú","Football","Loisirs"],
["也","yě","Aussi","Adverbes"],["都","dōu","Tous","Adverbes"],["很","hěn","Très","Adverbes"],
["太","tài","Trop","Adverbes"],["非常","fēi cháng","Extrêmement","Adverbes"],["一起","yī qǐ","Ensemble","Adverbes"],
["上面","shàng miàn","Dessus","Positions"],["下面","xià miàn","Dessous","Positions"],
["前面","qián miàn","Devant","Positions"],["后面","hòu miàn","Derrière","Positions"],
["名字","míng zi","Prénom / Nom","Divers"],["电话","diàn huà","Téléphone","Divers"],["电脑","diàn nǎo","Ordinateur","Divers"],
["钱","qián","Argent","Divers"],["时间","shí jiān","Temps / Heure","Divers"],["衣服","yī fu","Vêtements","Divers"],
["桌子","zhuō zi","Table","Divers"],["椅子","yǐ zi","Chaise","Divers"],["床","chuáng","Lit","Divers"],
["照片","zhào piàn","Photo","Divers"],["礼物","lǐ wù","Cadeau","Divers"],["节日","jié rì","Fête","Divers"],
["汉语","hàn yǔ","Chinois (langue)","Divers"],
["女儿","nǚ ér","Fille (enfant)","Famille"],
["上班","shàng bān","Aller au travail","Verbes"],["洗澡","xǐ zǎo","Se laver / Se doucher","Verbes"],
["刷牙","shuā yá","Se brosser les dents","Verbes"],["迟到","chí dào","Être en retard","Verbes"],
["等","děng","Attendre","Verbes"],["骑","qí","Monter (vélo / cheval)","Verbes"],
["洗手间","xǐ shǒu jiān","Toilettes","Lieux"],["厨房","chú fáng","Cuisine","Lieux"],
["动物园","dòng wù yuán","Zoo","Lieux"],
["早饭","zǎo fàn","Petit-déjeuner","Nourriture"],["午饭","wǔ fàn","Déjeuner","Nourriture"],
["晚饭","wǎn fàn","Dîner","Nourriture"],["咖啡","kā fēi","Café","Nourriture"],
["冰淇淋","bīng qí lín","Glace (dessert)","Nourriture"],
["渴","kě","Assoiffé","Adjectifs"],["饿","è","Affamé","Adjectifs"],
["疼","téng","Douloureux / Avoir mal","Adjectifs"],
["跳舞","tiào wǔ","Danser","Loisirs"],["篮球","lán qiú","Basket-ball","Loisirs"],
["游戏","yóu xì","Jeu","Loisirs"],
["灯","dēng","Lampe / Lumière","Divers"],["窗户","chuāng hu","Fenêtre","Divers"],
["房子","fáng zi","Maison / Bâtiment","Divers"],["紫色","zǐ sè","Violet","Couleurs"]
]},
yct3:{label:"YCT 3",lc:"l3",icon:"🟣",desc:"Intermédiaire",words:[
["城市","chéng shì","Ville","Lieux"],["农村","nóng cūn","Campagne","Lieux"],["机场","jī chǎng","Aéroport","Lieux"],
["火车站","huǒ chē zhàn","Gare","Lieux"],["银行","yín háng","Banque","Lieux"],["图书馆","tú shū guǎn","Bibliothèque","Lieux"],
["饭店","fàn diàn","Hôtel / Restaurant","Lieux"],["博物馆","bó wù guǎn","Musée","Lieux"],
["工作","gōng zuò","Travail","Professions"],["工程师","gōng chéng shī","Ingénieur","Professions"],["经理","jīng lǐ","Directeur","Professions"],
["律师","lǜ shī","Avocat","Professions"],["护士","hù shi","Infirmier/ière","Professions"],["警察","jǐng chá","Policier","Professions"],
["司机","sī jī","Chauffeur","Professions"],["厨师","chú shī","Cuisinier","Professions"],["演员","yǎn yuán","Acteur","Professions"],
["旅游","lǚ yóu","Tourisme","Voyages"],["护照","hù zhào","Passeport","Voyages"],["行李","xíng li","Bagages","Voyages"],
["地图","dì tú","Carte / Plan","Voyages"],["签证","qiān zhèng","Visa","Voyages"],["出发","chū fā","Départ","Voyages"],
["到达","dào dá","Arrivée","Voyages"],["旅行","lǚ xíng","Voyage","Voyages"],
["气候","qì hòu","Climat","Nature"],["山","shān","Montagne","Nature"],["河","hé","Rivière","Nature"],
["海","hǎi","Mer","Nature"],["森林","sēn lín","Forêt","Nature"],["花","huā","Fleur","Nature"],
["树","shù","Arbre","Nature"],["天空","tiān kōng","Ciel","Nature"],["月亮","yuè liang","Lune","Nature"],
["春天","chūn tiān","Printemps","Saisons"],["夏天","xià tiān","Été","Saisons"],["秋天","qiū tiān","Automne","Saisons"],["冬天","dōng tiān","Hiver","Saisons"],
["生病","shēng bìng","Être malade","Santé"],["头疼","tóu téng","Mal de tête","Santé"],
["发烧","fā shāo","Fièvre","Santé"],["药","yào","Médicament","Santé"],
["休息","xiū xi","Se reposer","Santé"],["健康","jiàn kāng","Santé","Santé"],["感冒","gǎn mào","Rhume","Santé"],
["因为","yīn wèi","Parce que","Connecteurs"],["所以","suǒ yǐ","Donc","Connecteurs"],["虽然","suī rán","Bien que","Connecteurs"],
["但是","dàn shì","Mais","Connecteurs"],["如果","rú guǒ","Si (cond.)","Connecteurs"],["而且","ér qiě","De plus","Connecteurs"],
["可以","kě yǐ","Pouvoir","Auxiliaires"],["应该","yīng gāi","Devoir","Auxiliaires"],
["必须","bì xū","Devoir absolument","Auxiliaires"],["能","néng","Capable de","Auxiliaires"],["要","yào","Vouloir","Auxiliaires"],
["了解","liǎo jiě","Comprendre","Verbes"],["介绍","jiè shào","Présenter","Verbes"],["参加","cān jiā","Participer","Verbes"],
["准备","zhǔn bèi","Préparer","Verbes"],["解决","jiě jué","Résoudre","Verbes"],["发现","fā xiàn","Découvrir","Verbes"],
["决定","jué dìng","Décider","Verbes"],["选择","xuǎn zé","Choisir","Verbes"],
["危险","wēi xiǎn","Dangereux","Adjectifs"],["安全","ān quán","Sûr","Adjectifs"],["简单","jiǎn dān","Simple","Adjectifs"],
["复杂","fù zá","Complexe","Adjectifs"],["方便","fāng biàn","Pratique","Adjectifs"],
["有名","yǒu míng","Célèbre","Adjectifs"],["认真","rèn zhēn","Sérieux","Adjectifs"],
["丈夫","zhàng fu","Mari","Relations"],["妻子","qī zi","Épouse","Relations"],["父母","fù mǔ","Parents","Relations"],
["孩子","hái zi","Enfant","Relations"],["邻居","lín jū","Voisin","Relations"],["同事","tóng shì","Collègue","Relations"],
["文化","wén huà","Culture","Société"],["历史","lì shǐ","Histoire","Société"],["经济","jīng jì","Économie","Société"],
["社会","shè huì","Société","Société"],["教育","jiào yù","Éducation","Société"],["科技","kē jì","Technologie","Société"],
["认识","rèn shi","Connaître","Verbes"],["帮助","bāng zhù","Aider","Verbes"],["告诉","gào su","Dire / Informer","Verbes"],
["希望","xī wàng","Espérer","Verbes"],["注意","zhù yì","Faire attention","Verbes"],["觉得","jué de","Trouver / Penser","Verbes"],
["需要","xū yào","Avoir besoin","Verbes"],["完成","wán chéng","Accomplir","Verbes"],["开始","kāi shǐ","Commencer","Verbes"],
["结束","jié shù","Terminer","Verbes"],["忘记","wàng jì","Oublier","Verbes"],["记得","jì de","Se souvenir","Verbes"],
["使用","shǐ yòng","Utiliser","Verbes"],["打算","dǎ suàn","Avoir l'intention de","Verbes"],["借","jiè","Emprunter / Prêter","Verbes"],
["换","huàn","Changer / Échanger","Verbes"],["找","zhǎo","Chercher","Verbes"],["送","sòng","Offrir / Accompagner","Verbes"],
["联系","lián xì","Contacter","Verbes"],["继续","jì xù","Continuer","Verbes"],["放","fàng","Poser / Mettre","Verbes"],
["拿","ná","Prendre / Porter","Verbes"],["解释","jiě shì","Expliquer","Verbes"],["比较","bǐ jiào","Comparer","Verbes"],
["担心","dān xīn","S'inquiéter","Verbes"],["相信","xiāng xìn","Croire","Verbes"],["改变","gǎi biàn","Changer","Verbes"],
["提高","tí gāo","Améliorer","Verbes"],["请","qǐng","Inviter / Prier","Verbes"],["带","dài","Apporter / Emmener","Verbes"],
["大家","dà jiā","Tout le monde","Personnes"],["别人","bié rén","Les autres","Personnes"],
["自己","zì jǐ","Soi-même","Personnes"],["客人","kè rén","Invité","Personnes"],["服务员","fú wù yuán","Serveur/Serveuse","Personnes"],
["地方","dì fāng","Endroit / Lieu","Lieux"],["附近","fù jìn","À proximité","Positions"],
["中间","zhōng jiān","Au milieu","Positions"],["旁边","páng biān","À côté","Positions"],
["左边","zuǒ biān","À gauche","Positions"],["右边","yòu biān","À droite","Positions"],
["外面","wài miàn","Dehors","Positions"],["里面","lǐ miàn","À l'intérieur","Positions"],
["时候","shí hou","Moment","Temps"],["最近","zuì jìn","Récemment","Temps"],
["刚才","gāng cái","Tout à l'heure","Temps"],["将来","jiāng lái","Avenir","Temps"],
["东西","dōng xi","Chose / Objet","Divers"],["事情","shì qing","Affaire / Chose","Divers"],
["问题","wèn tí","Problème / Question","Divers"],["机会","jī huì","Opportunité","Divers"],
["声音","shēng yīn","Son / Voix","Divers"],["方法","fāng fǎ","Méthode","Divers"],
["原因","yuán yīn","Raison / Cause","Divers"],["结果","jié guǒ","Résultat","Divers"],
["意思","yì si","Sens / Signification","Divers"],["信息","xìn xī","Information","Divers"],
["习惯","xí guàn","Habitude","Divers"],["计划","jì huà","Plan","Divers"],
["成绩","chéng jì","Résultats scolaires","École"],["作业","zuò yè","Devoirs","École"],["考试","kǎo shì","Examen","École"],
["裙子","qún zi","Jupe / Robe","Vêtements"],["裤子","kù zi","Pantalon","Vêtements"],
["鞋","xié","Chaussures","Vêtements"],["帽子","mào zi","Chapeau","Vêtements"],
["外套","wài tào","Manteau","Vêtements"],["袜子","wà zi","Chaussettes","Vêtements"],
["重要","zhòng yào","Important","Adjectifs"],["可爱","kě ài","Mignon / Adorable","Adjectifs"],
["特别","tè bié","Spécial / Particulier","Adjectifs"],["正确","zhèng què","Correct / Juste","Adjectifs"],
["有趣","yǒu qù","Intéressant / Amusant","Adjectifs"],["难过","nán guò","Triste","Adjectifs"],
["干净","gān jìng","Propre","Adjectifs"],["聪明","cōng míng","Intelligent","Adjectifs"],
["紧张","jǐn zhāng","Nerveux / Stressé","Adjectifs"],["舒服","shū fu","Confortable","Adjectifs"],
["累","lèi","Fatigué","Adjectifs"],["忙","máng","Occupé","Adjectifs"],
["年轻","nián qīng","Jeune","Adjectifs"],["普通","pǔ tōng","Ordinaire / Commun","Adjectifs"],
["开心","kāi xīn","Content / Joyeux","Adjectifs"],
["当然","dāng rán","Bien sûr","Adverbes"],["可能","kě néng","Peut-être / Possible","Adverbes"],
["一定","yī dìng","Certainement","Adverbes"],["其实","qí shí","En fait","Adverbes"],
["一直","yī zhí","Continuellement","Adverbes"],["怎么","zěn me","Comment","Adverbes"],
["已经","yǐ jīng","Déjà","Adverbes"],["还是","hái shì","Ou bien / Quand même","Adverbes"],
["总是","zǒng shì","Toujours","Adverbes"],["马上","mǎ shàng","Tout de suite","Adverbes"],
["尤其","yóu qí","Surtout","Adverbes"],["终于","zhōng yú","Enfin","Adverbes"],
["次","cì","Fois","Mesures"],["件","jiàn","Pièce (vêtement)","Mesures"],
["条","tiáo","Élément allongé","Mesures"],["双","shuāng","Paire","Mesures"],["瓶","píng","Bouteille","Mesures"],
["见面","jiàn miàn","Se rencontrer","Verbes"],["认为","rèn wéi","Considérer que","Verbes"],
["同意","tóng yì","Être d'accord","Verbes"],["明白","míng bai","Comprendre","Verbes"],
["懂","dǒng","Comprendre / Saisir","Verbes"],["练习","liàn xí","S'exercer","Verbes"],
["教","jiāo","Enseigner","Verbes"],["搬","bān","Déménager / Déplacer","Verbes"],
["打扫","dǎ sǎo","Nettoyer / Balayer","Verbes"],["结婚","jié hūn","Se marier","Verbes"],
["生气","shēng qì","Se fâcher","Verbes"],["付","fù","Payer","Verbes"],
["尝","cháng","Goûter","Verbes"],["挂","guà","Accrocher / Suspendre","Verbes"],
["接","jiē","Recevoir / Aller chercher","Verbes"],["陪","péi","Accompagner / Tenir compagnie","Verbes"],
["讲","jiǎng","Raconter / Expliquer","Verbes"],["表扬","biǎo yáng","Féliciter / Complimenter","Verbes"],
["及格","jí gé","Avoir la moyenne","Verbes"],["上网","shàng wǎng","Aller sur Internet","Verbes"],
["丢","diū","Perdre / Égarer","Verbes"],["醒","xǐng","Se réveiller","Verbes"],
["做饭","zuò fàn","Cuisiner","Verbes"],["加油","jiā yóu","Encourager / Courage !","Verbes"],
["数","shǔ","Compter","Verbes"],
["愿意","yuàn yì","Être disposé à","Auxiliaires"],["敢","gǎn","Oser","Auxiliaires"],
["好看","hǎo kàn","Beau / Joli","Adjectifs"],["好听","hǎo tīng","Agréable à écouter","Adjectifs"],
["好玩","hǎo wán","Amusant","Adjectifs"],["饱","bǎo","Rassasié","Adjectifs"],
["甜","tián","Sucré","Adjectifs"],["酸","suān","Acide","Adjectifs"],
["苦","kǔ","Amer","Adjectifs"],["辣","là","Épicé / Piquant","Adjectifs"],
["咸","xián","Salé","Adjectifs"],["新鲜","xīn xiān","Frais","Adjectifs"],
["主要","zhǔ yào","Principal","Adjectifs"],["一样","yī yàng","Pareil / Identique","Adjectifs"],
["不错","bú cuò","Pas mal / Bien","Adjectifs"],["满","mǎn","Plein","Adjectifs"],
["低","dī","Bas","Adjectifs"],["差","chà","Mauvais / Insuffisant","Adjectifs"],
["亮","liàng","Lumineux / Brillant","Adjectifs"],["暗","àn","Sombre","Adjectifs"],
["奇怪","qí guài","Étrange / Bizarre","Adjectifs"],["热闹","rè nao","Animé / Vivant","Adjectifs"],
["轻","qīng","Léger","Adjectifs"],["重","zhòng","Lourd","Adjectifs"],
["厚","hòu","Épais","Adjectifs"],["薄","báo","Fin / Mince","Adjectifs"],
["医生","yī shēng","Médecin","Professions"],["导游","dǎo yóu","Guide touristique","Professions"],
["农民","nóng mín","Paysan / Agriculteur","Professions"],["商人","shāng rén","Commerçant","Professions"],
["记者","jì zhě","Journaliste","Professions"],["科学家","kē xué jiā","Scientifique","Professions"],
["作家","zuò jiā","Écrivain","Professions"],["歌手","gē shǒu","Chanteur","Professions"],
["运动员","yùn dòng yuán","Athlète / Sportif","Professions"],
["办公室","bàn gōng shì","Bureau (pièce)","Lieux"],["邮局","yóu jú","Bureau de poste","Lieux"],
["药店","yào diàn","Pharmacie","Lieux"],["街道","jiē dào","Rue","Lieux"],
["路","lù","Route / Chemin","Lieux"],["桥","qiáo","Pont","Lieux"],
["宾馆","bīn guǎn","Hôtel","Lieux"],["客厅","kè tīng","Salon","Lieux"],
["卧室","wò shì","Chambre à coucher","Lieux"],
["地铁","dì tiě","Métro","Transports"],["出租车","chū zū chē","Taxi","Transports"],
["船","chuán","Bateau","Transports"],["票","piào","Billet / Ticket","Voyages"],
["地址","dì zhǐ","Adresse","Divers"],["邮件","yóu jiàn","Courrier / E-mail","Divers"],
["信","xìn","Lettre","Divers"],["报纸","bào zhǐ","Journal","Divers"],
["杂志","zá zhì","Magazine","Divers"],["故事","gù shi","Histoire / Conte","Divers"],
["词典","cí diǎn","Dictionnaire","École"],["黑板","hēi bǎn","Tableau noir","École"],
["肚子","dù zi","Ventre","Santé"],["牙","yá","Dent","Santé"],
["咳嗽","ké sou","Tousser","Santé"],["打针","dǎ zhēn","Faire une piqûre","Santé"],
["住院","zhù yuàn","Être hospitalisé","Santé"],
["湖","hú","Lac","Nature"],["草","cǎo","Herbe","Nature"],
["叶子","yè zi","Feuille","Nature"],["石头","shí tou","Pierre / Caillou","Nature"],
["动物","dòng wù","Animal","Nature"],["植物","zhí wù","Plante","Nature"],
["周末","zhōu mò","Week-end","Temps"],["小时","xiǎo shí","Heure (durée)","Temps"],
["半","bàn","Demi","Temps"],["世纪","shì jì","Siècle","Temps"],
["季节","jì jié","Saison","Saisons"],
["公斤","gōng jīn","Kilogramme","Mesures"],["米","mǐ","Mètre","Mesures"],
["张","zhāng","Classificateur (feuilles)","Mesures"],["只","zhī","Classificateur (animaux)","Mesures"],
["本","běn","Classificateur (livres)","Mesures"],["位","wèi","Classificateur (personnes, poli)","Mesures"],
["层","céng","Étage / Couche","Mesures"],
["生活","shēng huó","Vie (quotidienne)","Divers"],["工资","gōng zī","Salaire","Divers"],
["爱情","ài qíng","Amour","Relations"],["婚礼","hūn lǐ","Mariage (cérémonie)","Relations"],
["冰箱","bīng xiāng","Réfrigérateur","Divers"],["空调","kōng tiáo","Climatisation","Divers"],
["电梯","diàn tī","Ascenseur","Divers"],["钥匙","yào shi","Clé","Divers"],
["伞","sǎn","Parapluie","Divers"],["眼镜","yǎn jìng","Lunettes","Divers"],
["手表","shǒu biǎo","Montre","Divers"],
["毛衣","máo yī","Pull","Vêtements"],["衬衫","chèn shān","Chemise","Vêtements"],
["围巾","wéi jīn","Écharpe","Vêtements"],["手套","shǒu tào","Gants","Vêtements"],
["先","xiān","D'abord","Adverbes"],["然后","rán hòu","Ensuite","Adverbes"],
["最后","zuì hòu","Enfin / Finalement","Adverbes"],["一边","yī biān","Tout en (faisant)","Adverbes"],
["越来越","yuè lái yuè","De plus en plus","Adverbes"],["又","yòu","Encore / De nouveau","Adverbes"],
["再","zài","À nouveau / Encore","Adverbes"],["别","bié","Ne... pas (impératif)","Adverbes"],
["更","gèng","Plus / Davantage","Adverbes"],["最","zuì","Le plus","Adverbes"]
]},
yct4:{label:"YCT 4",lc:"l4",icon:"🟠",desc:"Intermédiaire supérieur",words:[
["辩论","biàn lùn","Débattre","Communication"],["演讲","yǎn jiǎng","Discours","Communication"],
["表达","biǎo dá","Exprimer","Communication"],["交流","jiāo liú","Échanger","Communication"],
["描述","miáo shù","Décrire","Communication"],["说明","shuō míng","Expliquer","Communication"],
["强调","qiáng diào","Souligner","Communication"],["反驳","fǎn bó","Réfuter","Communication"],
["平等","píng děng","Égalité","Société"],["民主","mín zhǔ","Démocratie","Société"],
["自由","zì yóu","Liberté","Société"],["责任","zé rèn","Responsabilité","Société"],
["权利","quán lì","Droit","Société"],["义务","yì wù","Obligation","Société"],
["公平","gōng píng","Juste","Société"],["规则","guī zé","Règle","Société"],
["传统","chuán tǒng","Tradition","Société"],["习俗","xí sú","Coutume","Société"],
["投资","tóu zī","Investir","Économie"],["利润","lì rùn","Bénéfice","Économie"],
["市场","shì chǎng","Marché","Économie"],["消费","xiāo fèi","Consommer","Économie"],
["税收","shuì shōu","Impôts","Économie"],["预算","yù suàn","Budget","Économie"],
["通货膨胀","tōng huò péng zhàng","Inflation","Économie"],["贸易","mào yì","Commerce","Économie"],
["环境","huán jìng","Environnement","Nature"],["污染","wū rǎn","Pollution","Nature"],
["能源","néng yuán","Énergie","Nature"],["生态","shēng tài","Écologie","Nature"],
["气候变化","qì hòu biàn huà","Changement climatique","Nature"],["可再生","kě zài shēng","Renouvelable","Nature"],
["人工智能","rén gōng zhì néng","Intelligence artificielle","Science"],["机器人","jī qì rén","Robot","Science"],
["研究","yán jiū","Recherche","Science"],["实验","shí yàn","Expérience","Science"],
["发明","fā míng","Invention","Science"],["创新","chuàng xīn","Innovation","Science"],
["技术","jì shù","Technique","Science"],["数字化","shù zì huà","Numérique","Science"],
["文学","wén xué","Littérature","Arts"],["小说","xiǎo shuō","Roman","Arts"],
["诗歌","shī gē","Poésie","Arts"],["艺术","yì shù","Art","Arts"],
["绘画","huì huà","Peinture","Arts"],["音乐会","yīn yuè huì","Concert","Arts"],
["心理","xīn lǐ","Psychologie","Sciences humaines"],["哲学","zhé xué","Philosophie","Sciences humaines"],
["逻辑","luó jí","Logique","Sciences humaines"],["道德","dào dé","Éthique","Sciences humaines"],
["坚持","jiān chí","Persévérer","Caractère"],["勇气","yǒng qì","Courage","Caractère"],
["耐心","nài xīn","Patience","Caractère"],["谦虚","qiān xū","Humilité","Caractère"],
["诚实","chéng shí","Honnête","Caractère"],["积极","jī jí","Positif / Actif","Caractère"],
["乐观","lè guān","Optimiste","Caractère"],["悲观","bēi guān","Pessimiste","Caractère"],
["移民","yí mín","Immigration","Monde"],["全球化","quán qiú huà","Mondialisation","Monde"],
["国际","guó jì","International","Monde"],["冲突","chōng tū","Conflit","Monde"],
["和平","hé píng","Paix","Monde"],["战争","zhàn zhēng","Guerre","Monde"],
["影响","yǐng xiǎng","Influencer / Affecter","Verbes"],["支持","zhī chí","Soutenir","Verbes"],
["反对","fǎn duì","S'opposer","Verbes"],["实现","shí xiàn","Réaliser / Accomplir","Verbes"],
["建立","jiàn lì","Établir / Créer","Verbes"],["提供","tí gōng","Fournir","Verbes"],
["考虑","kǎo lǜ","Considérer","Verbes"],["面对","miàn duì","Faire face à","Verbes"],
["接受","jiē shòu","Accepter","Verbes"],["拒绝","jù jué","Refuser","Verbes"],
["承认","chéng rèn","Admettre / Reconnaître","Verbes"],["避免","bì miǎn","Éviter","Verbes"],
["合作","hé zuò","Coopérer","Verbes"],["批评","pī píng","Critiquer","Verbes"],
["分析","fēn xī","Analyser","Verbes"],["评价","píng jià","Évaluer","Verbes"],
["总结","zǒng jié","Résumer","Verbes"],["促进","cù jìn","Promouvoir","Verbes"],
["保护","bǎo hù","Protéger","Verbes"],["竞争","jìng zhēng","Concurrencer","Verbes"],
["政府","zhèng fǔ","Gouvernement","Gouvernance"],["法律","fǎ lǜ","Loi","Gouvernance"],
["制度","zhì dù","Système / Institution","Gouvernance"],["公民","gōng mín","Citoyen","Gouvernance"],
["政策","zhèng cè","Politique / Mesure","Gouvernance"],["权力","quán lì","Pouvoir","Gouvernance"],
["领导","lǐng dǎo","Direction / Leader","Gouvernance"],["组织","zǔ zhī","Organisation","Gouvernance"],
["企业","qǐ yè","Entreprise","Business"],["公司","gōng sī","Société / Compagnie","Business"],
["产品","chǎn pǐn","Produit","Business"],["价格","jià gé","Prix","Business"],
["质量","zhì liàng","Qualité","Business"],["资源","zī yuán","Ressource","Business"],
["合同","hé tóng","Contrat","Business"],["效率","xiào lǜ","Efficacité","Business"],
["大学","dà xué","Université","Éducation"],["专业","zhuān yè","Spécialité / Major","Éducation"],
["课程","kè chéng","Programme / Cours","Éducation"],["知识","zhī shì","Connaissance","Éducation"],
["能力","néng lì","Capacité","Éducation"],["水平","shuǐ píng","Niveau","Éducation"],
["成功","chéng gōng","Succès","Éducation"],["失败","shī bài","Échec","Éducation"],
["媒体","méi tǐ","Médias","Société"],["网络","wǎng luò","Réseau / Internet","Société"],
["平台","píng tái","Plateforme","Société"],["社区","shè qū","Communauté","Société"],
["矛盾","máo dùn","Contradiction / Conflit","Société"],["价值观","jià zhí guān","Valeurs","Société"],
["文明","wén míng","Civilisation","Société"],["舆论","yú lùn","Opinion publique","Société"],
["压力","yā lì","Pression / Stress","Psychologie"],["幸福","xìng fú","Bonheur","Psychologie"],
["信心","xìn xīn","Confiance en soi","Psychologie"],["动力","dòng lì","Motivation / Élan","Psychologie"],
["精神","jīng shén","Esprit / Mental","Psychologie"],
["严重","yán zhòng","Grave / Sérieux","Adjectifs"],["有效","yǒu xiào","Efficace","Adjectifs"],
["独立","dú lì","Indépendant","Adjectifs"],["共同","gòng tóng","Commun / Collectif","Adjectifs"],
["主动","zhǔ dòng","Proactif / Actif","Adjectifs"],["合理","hé lǐ","Raisonnable","Adjectifs"],
["关键","guān jiàn","Clé / Crucial","Adjectifs"],["广泛","guǎng fàn","Large / Répandu","Adjectifs"],
["深刻","shēn kè","Profond","Adjectifs"],["理性","lǐ xìng","Rationnel","Adjectifs"],
["尽管","jǐn guǎn","Bien que / Malgré","Adverbes"],["然而","rán ér","Cependant / Pourtant","Adverbes"],
["因此","yīn cǐ","Par conséquent","Adverbes"],["此外","cǐ wài","De plus / En outre","Adverbes"],
["逐渐","zhú jiàn","Progressivement","Adverbes"],["最终","zuì zhōng","Finalement","Adverbes"],
["总体","zǒng tǐ","Dans l'ensemble","Adverbes"],
["态度","tài dù","Attitude","Caractère"],["观点","guān diǎn","Point de vue","Communication"],
["目标","mù biāo","Objectif","Éducation"],["方向","fāng xiàng","Direction","Divers"],
["过程","guò chéng","Processus","Divers"],
["条件","tiáo jiàn","Condition","Divers"],["标准","biāo zhǔn","Norme / Standard","Divers"],
["特点","tè diǎn","Caractéristique","Divers"],
["基础","jī chǔ","Base / Fondation","Éducation"],["内容","nèi róng","Contenu","Divers"],
["数量","shù liàng","Quantité","Divers"],["程度","chéng dù","Degré / Mesure","Divers"],
["范围","fàn wéi","Portée / Domaine","Divers"],["规模","guī mó","Échelle / Ampleur","Divers"],
["形式","xíng shì","Forme / Format","Divers"],["作用","zuò yòng","Rôle / Effet","Divers"],
["意义","yì yì","Signification / Importance","Divers"],["价值","jià zhí","Valeur","Divers"],
["需求","xū qiú","Demande / Besoin","Business"],["供给","gōng jǐ","Offre / Approvisionnement","Business"],
["发展","fā zhǎn","Développement","Société"],["变化","biàn huà","Changement","Divers"],
["现状","xiàn zhuàng","Situation actuelle","Divers"],
["挑战","tiǎo zhàn","Défi","Divers"],["机制","jī zhì","Mécanisme","Gouvernance"],
["影响力","yǐng xiǎng lì","Influence / Impact","Société"],["执行","zhí xíng","Exécuter / Mettre en œuvre","Verbes"],
["推广","tuī guǎng","Promouvoir / Diffuser","Verbes"],["监督","jiān dū","Superviser / Contrôler","Gouvernance"],
["改善","gǎi shàn","Améliorer","Verbes"],["加强","jiā qiáng","Renforcer","Verbes"],
["扩大","kuò dà","Élargir / Étendre","Verbes"],["缩小","suō xiǎo","Réduire / Rétrécir","Verbes"],
["突破","tū pò","Percée / Surmonter","Verbes"],["克服","kè fú","Surmonter / Vaincre","Verbes"],
["依据","yī jù","Base / Fondement","Divers"],["前提","qián tí","Prémisse / Condition préalable","Divers"],
["目的","mù dì","But / Objectif","Divers"],["手段","shǒu duàn","Moyen / Méthode","Divers"],
["后果","hòu guǒ","Conséquence","Divers"],["优势","yōu shì","Avantage","Divers"],
["劣势","liè shì","Désavantage / Faiblesse","Divers"],["趋势","qū shì","Tendance","Société"],
["现实","xiàn shí","Réalité","Divers"],["理想","lǐ xiǎng","Idéal","Caractère"],
["平衡","píng héng","Équilibre","Divers"],
["稳定","wěn dìng","Stable / Stabilité","Adjectifs"],
["消极","xiāo jí","Négatif / Passif","Adjectifs"],
["明确","míng què","Clair / Précis","Adjectifs"],["模糊","mó hu","Flou / Vague","Adjectifs"],
["讨论","tǎo lùn","Discuter","Verbes"],["建议","jiàn yì","Suggérer / Conseiller","Verbes"],
["安排","ān pái","Organiser / Planifier","Verbes"],["管理","guǎn lǐ","Gérer","Verbes"],
["训练","xùn liàn","Entraîner","Verbes"],["培养","péi yǎng","Former / Cultiver","Verbes"],
["鼓励","gǔ lì","Encourager","Verbes"],["邀请","yāo qǐng","Inviter","Verbes"],
["通知","tōng zhī","Informer / Notifier","Verbes"],["检查","jiǎn chá","Vérifier / Examiner","Verbes"],
["调查","diào chá","Enquêter","Verbes"],["报告","bào gào","Rapporter / Rapport","Verbes"],
["翻译","fān yì","Traduire","Verbes"],["增加","zēng jiā","Augmenter","Verbes"],
["减少","jiǎn shǎo","Diminuer","Verbes"],["缺少","quē shǎo","Manquer de","Verbes"],
["获得","huò dé","Obtenir","Verbes"],["失去","shī qù","Perdre","Verbes"],
["放弃","fàng qì","Abandonner","Verbes"],["尝试","cháng shì","Essayer","Verbes"],
["经历","jīng lì","Vivre / Traverser","Verbes"],["适应","shì yìng","S'adapter","Verbes"],
["满足","mǎn zú","Satisfaire","Verbes"],["吸引","xī yǐn","Attirer","Verbes"],
["引起","yǐn qǐ","Provoquer / Susciter","Verbes"],["造成","zào chéng","Causer","Verbes"],
["形成","xíng chéng","Former / Se former","Verbes"],["属于","shǔ yú","Appartenir à","Verbes"],
["包括","bāo kuò","Inclure","Verbes"],["表示","biǎo shì","Exprimer / Indiquer","Verbes"],
["表演","biǎo yǎn","Jouer / Se produire","Verbes"],["庆祝","qìng zhù","Célébrer","Verbes"],
["祝贺","zhù hè","Féliciter","Verbes"],["感谢","gǎn xiè","Remercier","Verbes"],
["道歉","dào qiàn","S'excuser","Verbes"],["原谅","yuán liàng","Pardonner","Verbes"],
["尊重","zūn zhòng","Respecter","Verbes"],["关心","guān xīn","Se soucier de","Verbes"],
["照顾","zhào gù","Prendre soin de","Verbes"],["保持","bǎo chí","Maintenir / Garder","Verbes"],
["存在","cún zài","Exister","Verbes"],["出现","chū xiàn","Apparaître","Verbes"],
["消失","xiāo shī","Disparaître","Verbes"],["举办","jǔ bàn","Organiser (événement)","Verbes"],
["参观","cān guān","Visiter","Verbes"],["申请","shēn qǐng","Postuler / Demander","Verbes"],
["毕业","bì yè","Obtenir son diplôme","Verbes"],["留学","liú xué","Étudier à l'étranger","Verbes"],
["复习","fù xí","Réviser","Verbes"],["预习","yù xí","Préparer une leçon","Verbes"],
["丰富","fēng fù","Riche / Abondant","Adjectifs"],["优秀","yōu xiù","Excellent","Adjectifs"],
["成熟","chéng shú","Mûr / Mature","Adjectifs"],["熟悉","shú xī","Familier","Adjectifs"],
["陌生","mò shēng","Inconnu / Étranger","Adjectifs"],["流利","liú lì","Courant / Fluide","Adjectifs"],
["正式","zhèng shì","Formel / Officiel","Adjectifs"],["随便","suí biàn","Décontracté / Au choix","Adjectifs"],
["严格","yán gé","Strict","Adjectifs"],["温暖","wēn nuǎn","Chaleureux / Doux","Adjectifs"],
["凉快","liáng kuai","Frais / Rafraîchissant","Adjectifs"],["无聊","wú liáo","Ennuyeux","Adjectifs"],
["精彩","jīng cǎi","Brillant / Formidable","Adjectifs"],["幽默","yōu mò","Humoristique","Adjectifs"],
["友好","yǒu hǎo","Amical","Adjectifs"],["热情","rè qíng","Chaleureux / Enthousiaste","Adjectifs"],
["冷静","lěng jìng","Calme / Posé","Adjectifs"],["勇敢","yǒng gǎn","Courageux","Adjectifs"],
["骄傲","jiāo ào","Fier / Orgueilleux","Adjectifs"],["害羞","hài xiū","Timide","Adjectifs"],
["粗心","cū xīn","Étourdi / Négligent","Adjectifs"],["仔细","zǐ xì","Minutieux / Attentif","Adjectifs"],
["辛苦","xīn kǔ","Pénible / Fatigant","Adjectifs"],["顺利","shùn lì","Sans encombre","Adjectifs"],
["准时","zhǔn shí","Ponctuel","Adjectifs"],["相同","xiāng tóng","Identique","Adjectifs"],
["相似","xiāng sì","Similaire","Adjectifs"],
["大概","dà gài","Probablement","Adverbes"],["也许","yě xǔ","Peut-être","Adverbes"],
["几乎","jī hū","Presque","Adverbes"],["完全","wán quán","Complètement","Adverbes"],
["突然","tū rán","Soudain","Adverbes"],["互相","hù xiāng","Mutuellement","Adverbes"],
["恐怕","kǒng pà","Je crains que","Adverbes"],["到底","dào dǐ","Enfin / Au fond","Adverbes"],
["甚至","shèn zhì","Même / Voire","Adverbes"],["仍然","réng rán","Toujours / Encore","Adverbes"],
["竟然","jìng rán","Contre toute attente","Adverbes"],["差不多","chà bu duō","À peu près","Adverbes"],
["及时","jí shí","À temps","Adverbes"],
["语法","yǔ fǎ","Grammaire","Éducation"],["词汇","cí huì","Vocabulaire","Éducation"],
["奖学金","jiǎng xué jīn","Bourse d'études","Éducation"],["学期","xué qī","Semestre","Éducation"],
["暑假","shǔ jià","Vacances d'été","Éducation"],["寒假","hán jià","Vacances d'hiver","Éducation"],
["心情","xīn qíng","Humeur","Psychologie"],["感觉","gǎn jué","Sensation / Impression","Psychologie"],
["梦想","mèng xiǎng","Rêve / Aspiration","Psychologie"],["记忆","jì yì","Mémoire / Souvenir","Psychologie"],
["空气","kōng qì","Air","Nature"],["阳光","yáng guāng","Soleil / Lumière du soleil","Nature"],
["地球","dì qiú","Terre (planète)","Nature"],["世界","shì jiè","Monde","Monde"],
["新闻","xīn wén","Actualités","Société"],["广告","guǎng gào","Publicité","Société"],
["节目","jié mù","Émission / Programme","Société"],["交通","jiāo tōng","Circulation / Transports","Société"],
["速度","sù dù","Vitesse","Science"],["温度","wēn dù","Température","Science"],
["重量","zhòng liàng","Poids","Science"],
["经验","jīng yàn","Expérience (acquise)","Divers"],["意见","yì jiàn","Opinion / Avis","Divers"],
["想法","xiǎng fǎ","Idée","Divers"],["兴趣","xìng qù","Intérêt","Divers"],
["爱好","ài hào","Loisir / Passion","Divers"],["距离","jù lí","Distance","Divers"],
["未来","wèi lái","Futur / Avenir","Divers"],["秘密","mì mì","Secret","Divers"],
["消息","xiāo xi","Nouvelle / Message","Divers"],["比赛","bǐ sài","Compétition / Match","Divers"],
["活动","huó dòng","Activité","Divers"],["会议","huì yì","Réunion","Divers"],
["假期","jià qī","Vacances","Divers"],
["发生","fā shēng","Se produire","Verbes"],["变成","biàn chéng","Devenir / Se changer en","Verbes"],
["成为","chéng wéi","Devenir","Verbes"],["离开","lí kāi","Quitter / Partir","Verbes"],
["经过","jīng guò","Passer par","Verbes"],["通过","tōng guò","Réussir / Passer par","Verbes"],
["收到","shōu dào","Recevoir","Verbes"],["收拾","shōu shi","Ranger","Verbes"],
["整理","zhěng lǐ","Organiser / Mettre en ordre","Verbes"],["修理","xiū lǐ","Réparer","Verbes"],
["掌握","zhǎng wò","Maîtriser","Verbes"],["记录","jì lù","Noter / Enregistrer","Verbes"],
["讨厌","tǎo yàn","Détester","Verbes"],["羡慕","xiàn mù","Envier","Verbes"],
["感动","gǎn dòng","Émouvoir","Verbes"],["后悔","hòu huǐ","Regretter","Verbes"],
["怀疑","huái yí","Douter / Soupçonner","Verbes"],["估计","gū jì","Estimer","Verbes"],
["判断","pàn duàn","Juger / Estimer","Verbes"],["证明","zhèng míng","Prouver","Verbes"],
["反映","fǎn yìng","Refléter","Verbes"],["展示","zhǎn shì","Présenter / Exposer","Verbes"],
["减轻","jiǎn qīng","Alléger / Réduire","Verbes"],["承担","chéng dān","Assumer","Verbes"],
["负责","fù zé","Être responsable de","Verbes"],["组成","zǔ chéng","Composer / Constituer","Verbes"],
["依靠","yī kào","Dépendre de / S'appuyer sur","Verbes"],["争取","zhēng qǔ","S'efforcer d'obtenir","Verbes"],
["呼吸","hū xī","Respirer","Verbes"],["锻炼","duàn liàn","Faire de l'exercice","Verbes"],
["散步","sàn bù","Se promener","Verbes"],
["情况","qíng kuàng","Situation","Divers"],["关系","guān xì","Relation","Divers"],
["区别","qū bié","Différence","Divers"],["优点","yōu diǎn","Qualité / Atout","Divers"],
["缺点","quē diǎn","Défaut","Divers"],["错误","cuò wù","Erreur","Divers"],
["困难","kùn nán","Difficulté","Divers"],["好处","hǎo chù","Avantage / Bienfait","Divers"],
["坏处","huài chù","Inconvénient","Divers"],["部分","bù fen","Partie","Divers"],
["细节","xì jié","Détail","Divers"],["例子","lì zi","Exemple","Divers"],
["规定","guī dìng","Règlement","Gouvernance"],["阶段","jiē duàn","Étape / Phase","Divers"],
["步骤","bù zhòu","Étape / Procédure","Divers"],["顺序","shùn xù","Ordre / Séquence","Divers"],
["位置","wèi zhì","Position / Emplacement","Divers"],["空间","kōng jiān","Espace","Divers"],
["表面","biǎo miàn","Surface","Divers"],["中心","zhōng xīn","Centre","Divers"],
["周围","zhōu wéi","Alentours","Divers"],["方面","fāng miàn","Aspect","Divers"],
["类型","lèi xíng","Type","Divers"],["种类","zhǒng lèi","Sorte / Catégorie","Divers"],
["材料","cái liào","Matériau","Science"],["工具","gōng jù","Outil","Science"],
["设备","shè bèi","Équipement","Science"],["项目","xiàng mù","Projet","Business"],
["任务","rèn wù","Tâche / Mission","Business"],["奖励","jiǎng lì","Récompense","Éducation"],
["惩罚","chéng fá","Punition","Éducation"],["收入","shōu rù","Revenu","Économie"],
["支出","zhī chū","Dépense","Économie"],["成本","chéng běn","Coût","Économie"],
["利益","lì yì","Intérêt / Bénéfice","Économie"],["损失","sǔn shī","Perte","Économie"],
["风险","fēng xiǎn","Risque","Économie"],
["失望","shī wàng","Déçu","Adjectifs"],["满意","mǎn yì","Satisfait","Adjectifs"],
["惊讶","jīng yà","Surpris","Adjectifs"],["兴奋","xīng fèn","Excité / Enthousiaste","Adjectifs"],
["孤独","gū dú","Solitaire / Seul","Adjectifs"],["自信","zì xìn","Sûr de soi","Adjectifs"],
["谨慎","jǐn shèn","Prudent","Adjectifs"],["大方","dà fang","Généreux","Adjectifs"],
["小气","xiǎo qì","Radin / Mesquin","Adjectifs"],["温柔","wēn róu","Doux / Tendre","Adjectifs"],
["严肃","yán sù","Sérieux / Grave","Adjectifs"],["活泼","huó pō","Vif / Enjoué","Adjectifs"],
["安静","ān jìng","Calme / Silencieux","Adjectifs"],["整齐","zhěng qí","Bien rangé / Ordonné","Adjectifs"],
["乱","luàn","En désordre","Adjectifs"],["直接","zhí jiē","Direct","Adjectifs"],
["间接","jiàn jiē","Indirect","Adjectifs"],["正常","zhèng cháng","Normal","Adjectifs"],
["特殊","tè shū","Particulier / Spécial","Adjectifs"],["普遍","pǔ biàn","Répandu / Courant","Adjectifs"],
["偶尔","ǒu ěr","Parfois / De temps en temps","Adverbes"],["经常","jīng cháng","Souvent","Adverbes"],
["立刻","lì kè","Immédiatement","Adverbes"],["故意","gù yì","Exprès","Adverbes"],
["亲自","qīn zì","En personne","Adverbes"],["千万","qiān wàn","Surtout (ne pas)","Adverbes"],
["至少","zhì shǎo","Au moins","Adverbes"],["顺便","shùn biàn","Au passage","Adverbes"],
["反正","fǎn zhèng","De toute façon","Adverbes"],
["适合","shì hé","Convenir à","Verbes"],["符合","fú hé","Correspondre à","Verbes"],
["达到","dá dào","Atteindre","Verbes"],["超过","chāo guò","Dépasser","Verbes"],
["降低","jiàng dī","Baisser / Réduire","Verbes"],["提前","tí qián","Avancer / Anticiper","Verbes"],
["推迟","tuī chí","Reporter / Retarder","Verbes"],["取消","qǔ xiāo","Annuler","Verbes"],
["停止","tíng zhǐ","Arrêter / Cesser","Verbes"],["禁止","jìn zhǐ","Interdire","Verbes"],
["允许","yǔn xǔ","Permettre / Autoriser","Verbes"],["要求","yāo qiú","Exiger / Exigence","Verbes"],
["商量","shāng liang","Discuter / Se concerter","Verbes"],["沟通","gōu tōng","Communiquer","Verbes"],
["说服","shuō fú","Convaincre","Verbes"],["提醒","tí xǐng","Rappeler (à quelqu'un)","Verbes"],
["成立","chéng lì","Fonder / Créer","Verbes"],["发表","fā biǎo","Publier / Exprimer","Verbes"],
["出版","chū bǎn","Éditer / Publier","Verbes"],["进行","jìn xíng","Mener / Effectuer","Verbes"],
["进步","jìn bù","Progresser / Progrès","Verbes"],["退步","tuì bù","Régresser","Verbes"],
["报名","bào míng","S'inscrire","Verbes"],["值得","zhí dé","Mériter / Valoir la peine","Verbes"],
["感受","gǎn shòu","Ressentir","Verbes"],["体会","tǐ huì","Éprouver / Saisir","Verbes"],
["体验","tǐ yàn","Expérimenter / Vivre","Verbes"],["想念","xiǎng niàn","Penser à / Regretter l'absence","Verbes"],
["想象","xiǎng xiàng","Imaginer","Verbes"],["回忆","huí yì","Se remémorer","Verbes"],
["忽略","hū lüè","Négliger / Ignorer","Verbes"],["重视","zhòng shì","Accorder de l'importance à","Verbes"],
["关注","guān zhù","Suivre / Prêter attention à","Verbes"],["争论","zhēng lùn","Se disputer / Débattre","Verbes"],
["处理","chǔ lǐ","Traiter / Gérer","Verbes"],["安慰","ān wèi","Consoler / Réconforter","Verbes"],
["支付","zhī fù","Payer / Régler","Verbes"],["节约","jié yuē","Économiser","Verbes"],
["浪费","làng fèi","Gaspiller","Verbes"],["打扰","dǎ rǎo","Déranger","Verbes"],
["麻烦","má fan","Déranger / Ennui","Verbes"],["帮忙","bāng máng","Donner un coup de main","Verbes"],
["招聘","zhāo pìn","Recruter","Verbes"],["辞职","cí zhí","Démissionner","Verbes"],
["加班","jiā bān","Faire des heures supplémentaires","Verbes"],["出差","chū chāi","Partir en déplacement professionnel","Verbes"],
["请假","qǐng jià","Demander un congé","Verbes"],["逃避","táo bì","Fuir / Se dérober","Verbes"],
["面临","miàn lín","Être confronté à","Verbes"],["遵守","zūn shǒu","Respecter (règles)","Verbes"],
["违反","wéi fǎn","Enfreindre","Verbes"],["调整","tiáo zhěng","Ajuster","Verbes"],
["恢复","huī fù","Rétablir / Récupérer","Verbes"],["保存","bǎo cún","Conserver / Sauvegarder","Verbes"],
["删除","shān chú","Supprimer","Verbes"],["下载","xià zài","Télécharger","Verbes"],
["上传","shàng chuán","Téléverser","Verbes"],["注册","zhù cè","S'enregistrer / Créer un compte","Verbes"],
["登录","dēng lù","Se connecter","Verbes"],
["人口","rén kǒu","Population","Société"],["民族","mín zú","Ethnie / Nation","Société"],
["国家","guó jiā","Pays / État","Gouvernance"],["首都","shǒu dū","Capitale","Monde"],
["地区","dì qū","Région","Monde"],["事故","shì gù","Accident","Société"],
["事件","shì jiàn","Événement","Société"],["危害","wēi hài","Nuisance / Nuire","Société"],
["垃圾","lā jī","Déchets","Nature"],["塑料","sù liào","Plastique","Nature"],
["灾难","zāi nàn","Catastrophe","Nature"],["地震","dì zhèn","Séisme","Nature"],
["台风","tái fēng","Typhon","Nature"],["风景","fēng jǐng","Paysage","Nature"],
["职业","zhí yè","Profession","Business"],["职位","zhí wèi","Poste (emploi)","Business"],
["简历","jiǎn lì","CV","Business"],["面试","miàn shì","Entretien d'embauche","Business"],
["老板","lǎo bǎn","Patron","Business"],["顾客","gù kè","Client","Business"],
["团队","tuán duì","Équipe","Business"],["成员","chéng yuán","Membre","Business"],
["服务","fú wù","Service","Business"],["优惠","yōu huì","Réduction / Avantageux","Business"],
["折扣","zhé kòu","Remise","Business"],["现金","xiàn jīn","Espèces / Liquide","Business"],
["信用卡","xìn yòng kǎ","Carte de crédit","Business"],["账户","zhàng hù","Compte (bancaire)","Business"],
["工厂","gōng chǎng","Usine","Économie"],["农业","nóng yè","Agriculture","Économie"],
["工业","gōng yè","Industrie","Économie"],["商业","shāng yè","Commerce","Économie"],
["专家","zhuān jiā","Expert","Personnes"],["代表","dài biǎo","Représentant / Représenter","Personnes"],
["观众","guān zhòng","Public / Spectateurs","Personnes"],["读者","dú zhě","Lecteur","Personnes"],
["作者","zuò zhě","Auteur","Personnes"],["青少年","qīng shào nián","Adolescents","Personnes"],
["儿童","ér tóng","Enfants","Personnes"],["老人","lǎo rén","Personnes âgées","Personnes"],
["教材","jiào cái","Manuel scolaire","Éducation"],["讲座","jiǎng zuò","Conférence","Éducation"],
["论文","lùn wén","Mémoire / Article","Éducation"],["学历","xué lì","Diplôme / Cursus","Éducation"],
["硕士","shuò shì","Master","Éducation"],["博士","bó shì","Doctorat","Éducation"],
["实习","shí xí","Stage","Éducation"],
["营养","yíng yǎng","Nutrition","Santé"],["体育","tǐ yù","Sport / Éducation physique","Santé"],
["心脏","xīn zàng","Cœur (organe)","Santé"],["皮肤","pí fū","Peau","Santé"],
["睡眠","shuì mián","Sommeil","Santé"],
["感情","gǎn qíng","Sentiments","Relations"],["友谊","yǒu yì","Amitié","Relations"],
["婚姻","hūn yīn","Mariage (institution)","Relations"],["家庭","jiā tíng","Famille / Foyer","Relations"],
["建筑","jiàn zhù","Architecture / Bâtiment","Arts"],["广场","guǎng chǎng","Place (publique)","Monde"],
["数字","shù zì","Chiffre / Nombre","Science"],["比例","bǐ lì","Proportion","Science"],
["平均","píng jūn","Moyenne / En moyenne","Science"],["倍","bèi","Fois / Multiple","Science"],
["软件","ruǎn jiàn","Logiciel","Science"],["硬件","yìng jiàn","Matériel (informatique)","Science"],
["屏幕","píng mù","Écran","Science"],["键盘","jiàn pán","Clavier","Science"],
["文件","wén jiàn","Fichier / Document","Science"],["资料","zī liào","Documentation / Données","Science"],
["网站","wǎng zhàn","Site web","Science"],["程序","chéng xù","Programme (informatique)","Science"],
["智能","zhì néng","Intelligent / Smart","Science"],["设计","shè jì","Concevoir / Design","Science"],
["功能","gōng néng","Fonction / Fonctionnalité","Science"],["版本","bǎn běn","Version","Science"],
["密码","mì mǎ","Mot de passe","Science"],
["时代","shí dài","Époque / Ère","Temps"],["时期","shí qī","Période","Temps"],
["日常","rì cháng","Quotidien","Temps"],["现代","xiàn dài","Moderne","Temps"],
["古代","gǔ dài","Antiquité / Ancien","Temps"],
["措施","cuò shī","Mesure (action)","Divers"],["方案","fāng àn","Plan / Proposition","Divers"],
["效果","xiào guǒ","Effet / Résultat","Divers"],["印象","yìn xiàng","Impression","Divers"],
["必要","bì yào","Nécessaire","Adjectifs"],["优美","yōu měi","Gracieux / Élégant","Adjectifs"],
["美丽","měi lì","Beau / Magnifique","Adjectifs"],["干燥","gān zào","Sec","Adjectifs"],
["潮湿","cháo shī","Humide","Adjectifs"],["暖和","nuǎn huo","Chaud (agréable)","Adjectifs"],
["内向","nèi xiàng","Introverti","Adjectifs"],["外向","wài xiàng","Extraverti","Adjectifs"],
["懒","lǎn","Paresseux","Adjectifs"],["勤奋","qín fèn","Assidu / Travailleur","Adjectifs"],
["努力","nǔ lì","Appliqué / S'efforcer","Adjectifs"],["马虎","mǎ hu","Négligent","Adjectifs"],
["细心","xì xīn","Soigneux / Minutieux","Adjectifs"],["无奈","wú nài","Résigné / Impuissant","Adjectifs"],
["遗憾","yí hàn","Regrettable / Regret","Adjectifs"],["先进","xiān jìn","Avancé / De pointe","Adjectifs"],
["落后","luò hòu","En retard / Arriéré","Adjectifs"],["发达","fā dá","Développé","Adjectifs"],
["富裕","fù yù","Riche / Aisé","Adjectifs"],["免费","miǎn fèi","Gratuit","Adjectifs"],
["流行","liú xíng","À la mode / Populaire","Adjectifs"],["礼貌","lǐ mào","Poli / Politesse","Adjectifs"],
["准确","zhǔn què","Exact / Précis","Adjectifs"],["详细","xiáng xì","Détaillé","Adjectifs"],
["完整","wán zhěng","Complet / Intégral","Adjectifs"],["灵活","líng huó","Flexible / Agile","Adjectifs"],
["强大","qiáng dà","Puissant","Adjectifs"],["弱","ruò","Faible","Adjectifs"],
["激烈","jī liè","Intense / Acharné","Adjectifs"],["紧急","jǐn jí","Urgent","Adjectifs"],
["迅速","xùn sù","Rapide / Prompt","Adjectifs"],
["曾经","céng jīng","Autrefois / Déjà","Adverbes"],["从来","cóng lái","Jamais / Depuis toujours","Adverbes"],
["永远","yǒng yuǎn","Pour toujours","Adverbes"],["果然","guǒ rán","Effectivement / Comme prévu","Adverbes"],
["尽量","jǐn liàng","Autant que possible","Adverbes"],["专门","zhuān mén","Spécialement","Adverbes"],
["挺","tǐng","Assez / Plutôt","Adverbes"],["稍微","shāo wēi","Légèrement","Adverbes"],
["重新","chóng xīn","À nouveau / Re-","Adverbes"],["正好","zhèng hǎo","Justement / Pile","Adverbes"],
["不过","bú guò","Mais / Cependant","Adverbes"],["否则","fǒu zé","Sinon","Adverbes"],
["只要","zhǐ yào","Pourvu que","Adverbes"],["只有","zhǐ yǒu","Seulement si","Adverbes"],
["不仅","bù jǐn","Non seulement","Adverbes"],["另外","lìng wài","Par ailleurs / En outre","Adverbes"],
["于是","yú shì","Alors / Sur ce","Adverbes"]
]},
yct5:{label:"YCT 5",lc:"l5",icon:"🔴",desc:"Avancé",words:[
["抽象","chōu xiàng","Abstrait","Pensée"],["具体","jù tǐ","Concret","Pensée"],
["本质","běn zhì","Essence","Pensée"],["现象","xiàn xiàng","Phénomène","Pensée"],
["规律","guī lǜ","Loi naturelle","Pensée"],["假设","jiǎ shè","Hypothèse","Pensée"],
["推理","tuī lǐ","Raisonnement","Pensée"],["客观","kè guān","Objectif","Pensée"],
["主观","zhǔ guān","Subjectif","Pensée"],["认知","rèn zhī","Cognition","Pensée"],
["意志","yì zhì","Volonté","Psychologie"],["潜意识","qián yì shí","Inconscient","Psychologie"],
["情绪","qíng xù","État émotionnel","Psychologie"],["动机","dòng jī","Motivation","Psychologie"],
["焦虑","jiāo lǜ","Anxiété","Psychologie"],["抑郁","yì yù","Dépression","Psychologie"],
["共情","gòng qíng","Empathie","Psychologie"],["自我","zì wǒ","Soi-même","Psychologie"],
["立法","lì fǎ","Législation","Politique"],["宪法","xiàn fǎ","Constitution","Politique"],
["主权","zhǔ quán","Souveraineté","Politique"],["选举","xuǎn jǔ","Élection","Politique"],
["改革","gǎi gé","Réforme","Politique"],["腐败","fǔ bài","Corruption","Politique"],
["透明度","tòu míng dù","Transparence","Politique"],["问责","wèn zé","Responsabilisation","Politique"],
["货币","huò bì","Monnaie","Économie"],["汇率","huì lǜ","Taux de change","Économie"],
["赤字","chì zì","Déficit","Économie"],["垄断","lǒng duàn","Monopole","Économie"],
["金融","jīn róng","Finance","Économie"],["资本主义","zī běn zhǔ yì","Capitalisme","Économie"],
["基因工程","jī yīn gōng chéng","Génie génétique","Sciences"],["量子计算","liàng zǐ jì suàn","Informatique quantique","Sciences"],
["神经网络","shén jīng wǎng luò","Réseau neuronal","Sciences"],["区块链","qū kuài liàn","Blockchain","Sciences"],
["虚拟现实","xū nǐ xiàn shí","Réalité virtuelle","Sciences"],["深度学习","shēn dù xué xí","Apprentissage profond","Sciences"],
["叙事","xù shì","Narration","Littérature"],["隐喻","yǐn yù","Métaphore","Littérature"],
["象征","xiàng zhēng","Symbole","Littérature"],["讽刺","fěng cì","Satire","Littérature"],
["修辞","xiū cí","Rhétorique","Littérature"],["风格","fēng gé","Style","Littérature"],
["生物多样性","shēng wù duō yàng xìng","Biodiversité","Environnement"],["物种","wù zhǒng","Espèce","Environnement"],
["碳中和","tàn zhōng hé","Neutralité carbone","Environnement"],["生态系统","shēng tài xì tǒng","Écosystème","Environnement"],
["沙漠化","shā mò huà","Désertification","Environnement"],["海平面","hǎi píng miàn","Niveau de la mer","Environnement"],
["城镇化","chéng zhèn huà","Urbanisation","Sociologie"],["贫困","pín kùn","Pauvreté","Sociologie"],
["不平等","bù píng děng","Inégalité","Sociologie"],["歧视","qí shì","Discrimination","Sociologie"],
["包容","bāo róng","Inclusion","Sociologie"],["多元化","duō yuán huà","Diversité","Sociologie"],
["企业家","qǐ yè jiā","Entrepreneur","Business"],["初创","chū chuàng","Startup","Business"],
["品牌","pǐn pái","Marque","Business"],["营销","yíng xiāo","Marketing","Business"],
["供应链","gōng yìng liàn","Chaîne d'approvisionnement","Business"],["商业模式","shāng yè mó shì","Modèle économique","Business"],
["阐述","chǎn shù","Exposer / Développer","Verbes"],["论证","lùn zhèng","Démontrer / Argumenter","Verbes"],
["质疑","zhì yí","Remettre en question","Verbes"],["超越","chāo yuè","Dépasser / Transcender","Verbes"],
["制约","zhì yuē","Contraindre / Limiter","Verbes"],["颠覆","diān fù","Renverser / Subvertir","Verbes"],
["融合","róng hé","Fusionner / Intégrer","Verbes"],["重构","chóng gòu","Reconstruire","Verbes"],
["推动","tuī dòng","Propulser / Pousser","Verbes"],["优化","yōu huà","Optimiser","Verbes"],
["调控","diào kòng","Réguler / Contrôler","Verbes"],["整合","zhěng hé","Intégrer / Consolider","Verbes"],
["演化","yǎn huà","Évoluer","Verbes"],["驱动","qū dòng","Piloter / Conduire","Verbes"],
["渗透","shèn tòu","Pénétrer / Imprégner","Verbes"],
["危机","wēi jī","Crise","Concepts"],["结构","jié gòu","Structure","Concepts"],
["增长","zēng zhǎng","Croissance","Concepts"],["数据","shù jù","Données","Concepts"],
["算法","suàn fǎ","Algorithme","Concepts"],["模型","mó xíng","Modèle","Concepts"],
["指标","zhǐ biāo","Indicateur","Concepts"],["框架","kuāng jià","Cadre / Framework","Concepts"],
["共识","gòng shí","Consensus","Concepts"],["原则","yuán zé","Principe","Concepts"],
["范式","fàn shì","Paradigme","Concepts"],["悖论","bèi lùn","Paradoxe","Concepts"],
["批判","pī pàn","Critique / Remise en cause","Concepts"],["媒介","méi jiè","Médium / Intermédiaire","Concepts"],
["载体","zài tǐ","Vecteur / Support","Concepts"],
["可持续","kě chí xù","Durable","Adjectifs"],["全面","quán miàn","Complet / Global","Adjectifs"],
["综合","zōng hé","Synthétique / Intégré","Adjectifs"],["深远","shēn yuǎn","Profond et durable","Adjectifs"],
["微妙","wēi miào","Subtil / Délicat","Adjectifs"],["根本","gēn běn","Fondamental","Adjectifs"],
["关联","guān lián","Corrélé / Lié","Adjectifs"],["复合","fù hé","Composite / Mixte","Adjectifs"],
["显然","xiǎn rán","Évident / Manifeste","Adjectifs"],["系统","xì tǒng","Systématique","Adjectifs"],
["诚然","chéng rán","Certes / Il est vrai","Connecteurs"],["固然","gù rán","Certes / Sans doute","Connecteurs"],
["毕竟","bì jìng","Après tout","Connecteurs"],["况且","kuàng qiě","De plus / En outre","Connecteurs"],
["进而","jìn ér","En outre / Par là","Connecteurs"],["反之","fǎn zhī","À l'inverse","Connecteurs"],
["由此","yóu cǐ","De ce fait / Ainsi","Connecteurs"],["综上","zōng shàng","En résumé / Tout compte fait","Connecteurs"],
["换言之","huàn yán zhī","Autrement dit","Connecteurs"],["就此","jiù cǐ","À ce sujet / Là-dessus","Connecteurs"],
["前沿","qián yán","Avant-garde / Frontier","Concepts"],["边界","biān jiè","Frontière / Limite","Concepts"],
["层面","céng miàn","Dimension / Niveau","Concepts"],["维度","wéi dù","Dimension","Concepts"],
["脉络","mài luò","Fil conducteur / Contexte","Concepts"],
["推断","tuī duàn","Déduire / Inférer","Verbes"],["归纳","guī nà","Induire / Synthétiser","Verbes"],
["演绎","yǎn yì","Déduire / Déduction","Verbes"],
["具象","jù xiàng","Concrétiser","Verbes"],["解构","jiě gòu","Déconstruire","Verbes"],
["重塑","chóng sù","Remodeler","Verbes"],
["量化","liàng huà","Quantifier","Verbes"],["验证","yàn zhèng","Valider / Vérifier","Verbes"],
["权衡","quán héng","Peser / Arbitrer","Verbes"],["博弈","bó yì","Jouer un jeu stratégique","Verbes"],
["价值链","jià zhí liàn","Chaîne de valeur","Business"],["生命周期","shēng mìng zhōu qī","Cycle de vie","Business"],
["核心竞争力","hé xīn jìng zhēng lì","Compétence clé","Business"],["风险管理","fēng xiǎn guǎn lǐ","Gestion des risques","Business"],
["可行性","kě xíng xìng","Faisabilité","Business"],["协同","xié tóng","Synergie / Collaborer","Business"],
["迭代","dié dài","Itérer / Itération","Sciences"],["涌现","yǒng xiàn","Émergence","Sciences"],
["熵","shāng","Entropie","Sciences"],["临界","lín jiè","Critique / Seuil","Sciences"],
["非线性","fēi xiàn xìng","Non-linéaire","Sciences"],["复杂性","fù zá xìng","Complexité","Sciences"],
["叙事学","xù shì xué","Narratologie","Littérature"],["互文性","hù wén xìng","Intertextualité","Littérature"],
["解构主义","jiě gòu zhǔ yì","Déconstructivisme","Littérature"],["后现代","hòu xiàn dài","Postmoderne","Littérature"],
["能指","néng zhǐ","Signifiant","Littérature"],["所指","suǒ zhǐ","Signifié","Littérature"],
["话语权","huà yǔ quán","Pouvoir discursif","Politique"],["合法性","hé fǎ xìng","Légitimité","Politique"],
["话语体系","huà yǔ tǐ xì","Système discursif","Politique"],["治理","zhì lǐ","Gouvernance","Politique"],
["秩序","zhì xù","Ordre","Politique"],["博弈论","bó yì lùn","Théorie des jeux","Sciences"],
["社会契约","shè huì qì yuē","Contrat social","Politique"],["公民社会","gōng mín shè huì","Société civile","Politique"],
["思维","sī wéi","Pensée / Mode de pensée","Pensée"],["直觉","zhí jué","Intuition","Pensée"],
["理论","lǐ lùn","Théorie","Pensée"],["观念","guān niàn","Conception / Notion","Pensée"],
["意识","yì shí","Conscience","Pensée"],["智慧","zhì huì","Sagesse","Pensée"],
["灵感","líng gǎn","Inspiration","Pensée"],["反思","fǎn sī","Réflexion critique","Pensée"],
["人格","rén gé","Personnalité","Psychologie"],["心态","xīn tài","État d'esprit","Psychologie"],
["成就感","chéng jiù gǎn","Sentiment d'accomplissement","Psychologie"],["归属感","guī shǔ gǎn","Sentiment d'appartenance","Psychologie"],
["自尊","zì zūn","Estime de soi","Psychologie"],["韧性","rèn xìng","Résilience","Psychologie"],
["外交","wài jiāo","Diplomatie","Politique"],["联盟","lián méng","Alliance","Politique"],
["制裁","zhì cái","Sanctions","Politique"],["谈判","tán pàn","Négociation","Politique"],
["协议","xié yì","Accord","Politique"],["政党","zhèng dǎng","Parti politique","Politique"],
["议会","yì huì","Parlement","Politique"],
["股票","gǔ piào","Actions (bourse)","Économie"],["债务","zhài wù","Dette","Économie"],
["利率","lì lǜ","Taux d'intérêt","Économie"],["失业率","shī yè lǜ","Taux de chômage","Économie"],
["补贴","bǔ tiē","Subvention","Économie"],["关税","guān shuì","Droits de douane","Économie"],
["产业","chǎn yè","Industrie / Secteur","Économie"],["创业","chuàng yè","Entreprendre","Économie"],
["卫星","wèi xīng","Satellite","Sciences"],["航天","háng tiān","Astronautique","Sciences"],
["疫苗","yì miáo","Vaccin","Sciences"],["病毒","bìng dú","Virus","Sciences"],
["细胞","xì bāo","Cellule","Sciences"],["分子","fēn zǐ","Molécule","Sciences"],
["原子","yuán zǐ","Atome","Sciences"],["引力","yǐn lì","Gravité","Sciences"],
["概率","gài lǜ","Probabilité","Sciences"],["统计","tǒng jì","Statistiques","Sciences"],
["变量","biàn liàng","Variable","Sciences"],["相对论","xiāng duì lùn","Relativité","Sciences"],
["散文","sǎn wén","Prose / Essai","Littérature"],["戏剧","xì jù","Théâtre","Littérature"],
["悲剧","bēi jù","Tragédie","Littérature"],["喜剧","xǐ jù","Comédie","Littérature"],
["主题","zhǔ tí","Thème","Littérature"],["情节","qíng jié","Intrigue","Littérature"],
["人物","rén wù","Personnage","Littérature"],["意境","yì jìng","Atmosphère poétique","Littérature"],
["温室效应","wēn shì xiào yìng","Effet de serre","Environnement"],["排放","pái fàng","Émissions","Environnement"],
["回收","huí shōu","Recyclage","Environnement"],["栖息地","qī xī dì","Habitat","Environnement"],
["濒危","bīn wēi","En voie de disparition","Environnement"],["洪水","hóng shuǐ","Inondation","Environnement"],
["干旱","gān hàn","Sécheresse","Environnement"],
["老龄化","lǎo líng huà","Vieillissement démographique","Sociologie"],["阶层","jiē céng","Classe sociale","Sociologie"],
["认同","rèn tóng","Identité / Adhésion","Sociologie"],["边缘化","biān yuán huà","Marginalisation","Sociologie"],
["福利","fú lì","Protection sociale","Sociologie"],["志愿者","zhì yuàn zhě","Bénévole","Sociologie"],
["慈善","cí shàn","Charité / Philanthropie","Sociologie"],
["并购","bìng gòu","Fusion-acquisition","Business"],["股东","gǔ dōng","Actionnaire","Business"],
["融资","róng zī","Levée de fonds","Business"],["估值","gū zhí","Valorisation","Business"],
["战略","zhàn lüè","Stratégie","Business"],["转型","zhuǎn xíng","Transformation","Business"],
["洞察","dòng chá","Discerner / Percevoir","Verbes"],["剖析","pōu xī","Analyser en profondeur","Verbes"],
["协商","xié shāng","Négocier / Se concerter","Verbes"],["倡导","chàng dǎo","Prôner / Promouvoir","Verbes"],
["遏制","è zhì","Endiguer / Contenir","Verbes"],["缓解","huǎn jiě","Atténuer / Soulager","Verbes"],
["激发","jī fā","Stimuler / Susciter","Verbes"],["塑造","sù zào","Façonner","Verbes"],
["衍生","yǎn shēng","Dériver","Verbes"],["凝聚","níng jù","Fédérer / Rassembler","Verbes"],
["借鉴","jiè jiàn","S'inspirer de","Verbes"],["落实","luò shí","Mettre en œuvre","Verbes"],
["张力","zhāng lì","Tension","Concepts"],["语境","yǔ jìng","Contexte","Concepts"],
["内涵","nèi hán","Connotation","Concepts"],["外延","wài yán","Dénotation / Extension","Concepts"],
["主体","zhǔ tǐ","Sujet / Acteur","Concepts"],["变革","biàn gé","Mutation / Transformation","Concepts"],
["惯性","guàn xìng","Inertie","Concepts"],["阈值","yù zhí","Seuil","Concepts"],
["基准","jī zhǔn","Référence / Étalon","Concepts"],
["潜在","qián zài","Potentiel / Latent","Adjectifs"],["隐性","yǐn xìng","Implicite","Adjectifs"],
["显性","xiǎn xìng","Explicite","Adjectifs"],["内在","nèi zài","Intrinsèque","Adjectifs"],
["外在","wài zài","Extrinsèque","Adjectifs"],["宏观","hóng guān","Macroscopique","Adjectifs"],
["微观","wēi guān","Microscopique","Adjectifs"],["辩证","biàn zhèng","Dialectique","Adjectifs"],
["空前","kōng qián","Sans précédent","Adjectifs"],["多维","duō wéi","Multidimensionnel","Adjectifs"],
["鉴于","jiàn yú","Étant donné","Connecteurs"],["倘若","tǎng ruò","Si jamais","Connecteurs"],
["与其","yǔ qí","Plutôt que","Connecteurs"],["宁可","nìng kě","Préférer plutôt","Connecteurs"],
["以免","yǐ miǎn","De peur que","Connecteurs"],["从而","cóng ér","De ce fait","Connecteurs"],
["即便","jí biàn","Même si","Connecteurs"],["无论","wú lùn","Quel que soit","Connecteurs"],
["观察","guān chá","Observer","Verbes"],["探索","tàn suǒ","Explorer","Verbes"],
["探讨","tàn tǎo","Examiner / Débattre de","Verbes"],["构建","gòu jiàn","Construire / Élaborer","Verbes"],
["界定","jiè dìng","Délimiter / Définir","Verbes"],["概括","gài kuò","Généraliser / Résumer","Verbes"],
["提炼","tí liàn","Distiller / Extraire","Verbes"],["辨析","biàn xī","Distinguer / Discriminer","Verbes"],
["妥协","tuǒ xié","Transiger / Compromis","Verbes"],["传承","chuán chéng","Transmettre (héritage)","Verbes"],
["弘扬","hóng yáng","Faire rayonner","Verbes"],["汲取","jí qǔ","Puiser / Tirer","Verbes"],
["摒弃","bìng qì","Rejeter / Écarter","Verbes"],["秉持","bǐng chí","Adhérer à / Tenir à","Verbes"],
["斟酌","zhēn zhuó","Peser soigneusement","Verbes"],["迁移","qiān yí","Migrer / Transférer","Verbes"],
["蔓延","màn yán","Se propager","Verbes"],["波及","bō jí","Affecter / Toucher","Verbes"],
["催化","cuī huà","Catalyser","Verbes"],["引领","yǐn lǐng","Guider / Mener","Verbes"],
["孕育","yùn yù","Engendrer / Nourrir","Verbes"],["见证","jiàn zhèng","Témoigner de","Verbes"],
["命题","mìng tí","Proposition / Thèse","Concepts"],["范畴","fàn chóu","Catégorie / Domaine","Concepts"],
["蓝图","lán tú","Feuille de route / Plan","Concepts"],["愿景","yuàn jǐng","Vision (d'avenir)","Concepts"],
["使命","shǐ mìng","Mission","Concepts"],["格局","gé jú","Configuration / Envergure","Concepts"],
["杠杆","gàng gǎn","Levier","Concepts"],["红利","hóng lì","Dividende / Bonus","Concepts"],
["瓶颈","píng jǐng","Goulot d'étranglement","Concepts"],["拐点","guǎi diǎn","Point d'inflexion","Concepts"],
["隐患","yǐn huàn","Danger latent","Concepts"],["契机","qì jī","Occasion / Déclic","Concepts"],
["症结","zhēng jié","Nœud du problème","Concepts"],["雏形","chú xíng","Embryon / Prototype","Concepts"],
["联合国","lián hé guó","ONU","Politique"],["峰会","fēng huì","Sommet (réunion)","Politique"],
["决议","jué yì","Résolution","Politique"],["否决","fǒu jué","Rejeter / Veto","Politique"],
["游说","yóu shuì","Lobbying / Persuader","Politique"],["公投","gōng tóu","Référendum","Politique"],
["难民","nàn mín","Réfugié","Politique"],["人权","rén quán","Droits de l'homme","Politique"],
["泡沫","pào mò","Bulle (économique)","Économie"],["衰退","shuāi tuì","Récession","Économie"],
["复苏","fù sū","Reprise / Redressement","Économie"],["萧条","xiāo tiáo","Dépression (économique)","Économie"],
["顺差","shùn chā","Excédent commercial","Économie"],["逆差","nì chā","Déficit commercial","Économie"],
["央行","yāng háng","Banque centrale","Économie"],["股市","gǔ shì","Bourse / Marché boursier","Économie"],
["基因","jī yīn","Gène","Sciences"],["染色体","rǎn sè tǐ","Chromosome","Sciences"],
["抗体","kàng tǐ","Anticorps","Sciences"],["免疫","miǎn yì","Immunité","Sciences"],
["星系","xīng xì","Galaxie","Sciences"],["黑洞","hēi dòng","Trou noir","Sciences"],
["宇宙","yǔ zhòu","Univers","Sciences"],["进化","jìn huà","Évolution (biologique)","Sciences"],
["突变","tū biàn","Mutation","Sciences"],["辐射","fú shè","Radiation","Sciences"],
["悬念","xuán niàn","Suspense","Littérature"],["伏笔","fú bǐ","Indice précurseur","Littérature"],
["基调","jī diào","Tonalité","Littérature"],["韵律","yùn lǜ","Rythme / Métrique","Littérature"],
["典故","diǎn gù","Allusion classique","Littérature"],["寓言","yù yán","Fable","Littérature"],
["史诗","shǐ shī","Épopée","Littérature"],["文本","wén běn","Texte","Littérature"],
["冰川","bīng chuān","Glacier","Environnement"],["融化","róng huà","Fondre","Environnement"],
["臭氧层","chòu yǎng céng","Couche d'ozone","Environnement"],["酸雨","suān yǔ","Pluies acides","Environnement"],
["灭绝","miè jué","Extinction","Environnement"],["净化","jìng huà","Purifier / Purification","Environnement"],
["代沟","dài gōu","Fossé générationnel","Sociologie"],["性别","xìng bié","Genre / Sexe","Sociologie"],
["融入","róng rù","S'intégrer","Sociologie"],["排斥","pái chì","Exclure / Rejeter","Sociologie"],
["偏见","piān jiàn","Préjugé","Sociologie"],["刻板印象","kè bǎn yìn xiàng","Stéréotype","Sociologie"],
["门槛","mén kǎn","Barrière à l'entrée","Business"],["壁垒","bì lěi","Barrière / Rempart","Business"],
["布局","bù jú","Déploiement / Positionnement","Business"],["赋能","fù néng","Autonomiser / Renforcer","Business"],
["口碑","kǒu bēi","Réputation / Bouche-à-oreille","Business"],["溢价","yì jià","Prime / Surcote","Business"],
["严峻","yán jùn","Grave / Sévère","Adjectifs"],["迫切","pò qiè","Pressant / Urgent","Adjectifs"],
["深邃","shēn suì","Profond / Insondable","Adjectifs"],["前瞻","qián zhān","Prospectif","Adjectifs"],
["务实","wù shí","Pragmatique","Adjectifs"],["精准","jīng zhǔn","Précis / Pointu","Adjectifs"],
["透彻","tòu chè","Pénétrant / Limpide","Adjectifs"],["中立","zhōng lì","Neutre","Adjectifs"],
["单一","dān yī","Unique / Uniforme","Adjectifs"],["多元","duō yuán","Pluriel / Diversifié","Adjectifs"],
["不妨","bù fáng","Autant / Rien n'empêche de","Connecteurs"],["纵然","zòng rán","Quand bien même","Connecteurs"],
["譬如","pì rú","Par exemple","Connecteurs"],["乃至","nǎi zhì","Voire / Jusqu'à","Connecteurs"],
["唯有","wéi yǒu","Seul / Il n'y a que","Connecteurs"],["一旦","yī dàn","Une fois que","Connecteurs"],
["以便","yǐ biàn","Afin de / Pour que","Connecteurs"],["除非","chú fēi","À moins que","Connecteurs"],
["承诺","chéng nuò","Promettre / Engagement","Verbes"],["履行","lǚ xíng","Honorer / Exécuter","Verbes"],
["延续","yán xù","Perpétuer / Prolonger","Verbes"],["延伸","yán shēn","Étendre / S'étendre","Verbes"],
["拓展","tuò zhǎn","Élargir / Développer","Verbes"],["挖掘","wā jué","Creuser / Exploiter","Verbes"],
["积累","jī lěi","Accumuler","Verbes"],["沉淀","chén diàn","Décanter / Mûrir","Verbes"],
["沉浸","chén jìn","S'immerger","Verbes"],["凸显","tū xiǎn","Mettre en relief","Verbes"],
["彰显","zhāng xiǎn","Manifester / Illustrer","Verbes"],["折射","zhé shè","Refléter / Réfracter","Verbes"],
["诠释","quán shì","Interpréter","Verbes"],["解读","jiě dú","Décrypter","Verbes"],
["审视","shěn shì","Examiner / Scruter","Verbes"],["审查","shěn chá","Contrôler / Inspecter","Verbes"],
["评估","píng gū","Évaluer / Estimer","Verbes"],["衡量","héng liáng","Mesurer / Jauger","Verbes"],
["兼顾","jiān gù","Concilier","Verbes"],["统筹","tǒng chóu","Coordonner globalement","Verbes"],
["部署","bù shǔ","Déployer","Verbes"],["实施","shí shī","Mettre en œuvre","Verbes"],
["颁布","bān bù","Promulguer","Verbes"],["废除","fèi chú","Abolir","Verbes"],
["修订","xiū dìng","Réviser (texte)","Verbes"],["起草","qǐ cǎo","Rédiger un projet","Verbes"],
["审议","shěn yì","Délibérer","Verbes"],["表决","biǎo jué","Voter (assemblée)","Verbes"],
["弹劾","tán hé","Destituer","Verbes"],["瓦解","wǎ jiě","Désagréger","Verbes"],
["崩溃","bēng kuì","S'effondrer","Verbes"],["动摇","dòng yáo","Ébranler","Verbes"],
["巩固","gǒng gù","Consolider","Verbes"],["维系","wéi xì","Maintenir / Entretenir","Verbes"],
["捍卫","hàn wèi","Défendre","Verbes"],["抵御","dǐ yù","Résister à","Verbes"],
["抵制","dǐ zhì","Boycotter / S'opposer à","Verbes"],["对抗","duì kàng","Affronter","Verbes"],
["调解","tiáo jiě","Concilier / Arbitrer","Verbes"],["仲裁","zhòng cái","Arbitrer (litige)","Verbes"],
["申诉","shēn sù","Faire appel / Réclamer","Verbes"],["起诉","qǐ sù","Poursuivre en justice","Verbes"],
["辩护","biàn hù","Plaider / Défendre","Verbes"],["判决","pàn jué","Rendre un jugement","Verbes"],
["激励","jī lì","Motiver / Stimuler","Verbes"],["约束","yuē shù","Contraindre / Discipliner","Verbes"],
["规范","guī fàn","Normaliser / Norme","Verbes"],["杜绝","dù jué","Éradiquer","Verbes"],
["呈现","chéng xiàn","Présenter / Se manifester","Verbes"],["蕴含","yùn hán","Receler / Contenir","Verbes"],
["贯穿","guàn chuān","Traverser / Parcourir","Verbes"],["贯彻","guàn chè","Appliquer à fond","Verbes"],
["浓缩","nóng suō","Condenser","Verbes"],["攀升","pān shēng","Grimper / Monter","Verbes"],
["下滑","xià huá","Décliner / Glisser","Verbes"],["反弹","fǎn tán","Rebondir","Verbes"],
["波动","bō dòng","Fluctuer","Verbes"],["传播","chuán bō","Diffuser / Propager","Verbes"],
["扩散","kuò sàn","Se répandre","Verbes"],["掩盖","yǎn gài","Dissimuler","Verbes"],
["揭示","jiē shì","Révéler","Verbes"],["揭露","jiē lù","Dénoncer / Exposer","Verbes"],
["曝光","bào guāng","Exposer publiquement","Verbes"],["炒作","chǎo zuò","Faire du battage","Verbes"],
["操纵","cāo zòng","Manipuler","Verbes"],["误导","wù dǎo","Induire en erreur","Verbes"],
["筛选","shāi xuǎn","Filtrer / Sélectionner","Verbes"],["淘汰","táo tài","Éliminer","Verbes"],
["崛起","jué qǐ","Émerger / S'élever","Verbes"],["繁衍","fán yǎn","Se reproduire / Proliférer","Verbes"],
["酝酿","yùn niàng","Mûrir / Couver","Verbes"],
["理念","lǐ niàn","Concept / Philosophie","Pensée"],["思路","sī lù","Fil de pensée","Pensée"],
["视角","shì jiǎo","Angle de vue","Pensée"],["视野","shì yě","Horizon / Champ de vision","Pensée"],
["见解","jiàn jiě","Point de vue / Analyse","Pensée"],
["主张","zhǔ zhāng","Position / Prôner","Concepts"],["立场","lì chǎng","Position / Posture","Concepts"],
["起源","qǐ yuán","Origine","Concepts"],["内幕","nèi mù","Dessous / Coulisses","Concepts"],
["弊端","bì duān","Travers / Défaut","Concepts"],["利弊","lì bì","Avantages et inconvénients","Concepts"],
["成果","chéng guǒ","Fruit / Résultat","Concepts"],["底蕴","dǐ yùn","Substance / Profondeur","Concepts"],
["精髓","jīng suǐ","Quintessence","Concepts"],["基石","jī shí","Pierre angulaire","Concepts"],
["支柱","zhī zhù","Pilier","Concepts"],["枢纽","shū niǔ","Plaque tournante","Concepts"],
["纽带","niǔ dài","Lien / Trait d'union","Concepts"],["桥梁","qiáo liáng","Pont / Passerelle","Concepts"],
["源泉","yuán quán","Source","Concepts"],["势头","shì tóu","Élan / Dynamique","Concepts"],
["轨迹","guǐ jì","Trajectoire","Concepts"],["曲线","qū xiàn","Courbe","Concepts"],
["峰值","fēng zhí","Pic / Valeur maximale","Concepts"],["样本","yàng běn","Échantillon","Concepts"],
["案例","àn lì","Cas / Étude de cas","Concepts"],["误差","wù chā","Marge d'erreur","Concepts"],
["偏差","piān chā","Écart / Biais","Concepts"],
["司法","sī fǎ","Justice / Judiciaire","Politique"],["行政","xíng zhèng","Administratif","Politique"],
["政权","zhèng quán","Régime / Pouvoir politique","Politique"],["民意","mín yì","Opinion du peuple","Politique"],
["独裁","dú cái","Dictature","Politique"],["霸权","bà quán","Hégémonie","Politique"],
["殖民","zhí mín","Colonisation","Politique"],["革命","gé mìng","Révolution","Politique"],
["政变","zhèng biàn","Coup d'État","Politique"],["停火","tíng huǒ","Cessez-le-feu","Politique"],
["条约","tiáo yuē","Traité","Politique"],["法规","fǎ guī","Réglementation","Politique"],
["条款","tiáo kuǎn","Clause","Politique"],["诉讼","sù sòng","Procès / Contentieux","Politique"],
["罪犯","zuì fàn","Criminel","Politique"],["刑罚","xíng fá","Peine / Sanction pénale","Politique"],
["监狱","jiān yù","Prison","Politique"],["证据","zhèng jù","Preuve","Politique"],
["证人","zhèng rén","Témoin","Politique"],
["资产","zī chǎn","Actifs / Patrimoine","Économie"],["资本","zī běn","Capital","Économie"],
["破产","pò chǎn","Faillite","Économie"],["物价","wù jià","Niveau des prix","Économie"],
["财政","cái zhèng","Finances publiques","Économie"],["财富","cái fù","Richesse / Fortune","Économie"],
["资金","zī jīn","Fonds / Capitaux","Économie"],["盈利","yíng lì","Rentabilité / Profit","Économie"],
["亏损","kuī sǔn","Pertes / Déficit","Économie"],["交易","jiāo yì","Transaction","Économie"],
["股份","gǔ fèn","Parts / Actions","Business"],["招标","zhāo biāo","Appel d'offres","Business"],
["产能","chǎn néng","Capacité de production","Business"],["库存","kù cún","Stock","Business"],
["物流","wù liú","Logistique","Business"],["电商","diàn shāng","E-commerce","Business"],
["零售","líng shòu","Vente au détail","Business"],["批发","pī fā","Vente en gros","Business"],
["薪酬","xīn chóu","Rémunération","Business"],["绩效","jì xiào","Performance","Business"],
["市值","shì zhí","Capitalisation boursière","Business"],["份额","fèn é","Part de marché","Business"],
["望远镜","wàng yuǎn jìng","Télescope","Sciences"],["显微镜","xiǎn wēi jìng","Microscope","Sciences"],
["实验室","shí yàn shì","Laboratoire","Sciences"],["芯片","xīn piàn","Puce (électronique)","Sciences"],
["半导体","bàn dǎo tǐ","Semi-conducteur","Sciences"],["传感器","chuán gǎn qì","Capteur","Sciences"],
["无人机","wú rén jī","Drone","Sciences"],["自动化","zì dòng huà","Automatisation","Sciences"],
["云计算","yún jì suàn","Cloud computing","Sciences"],["大数据","dà shù jù","Big data","Sciences"],
["物联网","wù lián wǎng","Internet des objets","Sciences"],["隐私","yǐn sī","Vie privée","Sciences"],
["漏洞","lòu dòng","Faille","Sciences"],["黑客","hēi kè","Hacker","Sciences"],
["加密","jiā mì","Chiffrer / Crypter","Sciences"],["频率","pín lǜ","Fréquence","Sciences"],
["能量","néng liàng","Énergie (physique)","Sciences"],["物质","wù zhì","Matière","Sciences"],
["元素","yuán sù","Élément","Sciences"],["反应","fǎn yìng","Réaction","Sciences"],
["克隆","kè lóng","Cloner / Clonage","Sciences"],["神经","shén jīng","Nerf / Nerveux","Sciences"],
["大脑","dà nǎo","Cerveau","Sciences"],["器官","qì guān","Organe","Sciences"],
["移植","yí zhí","Greffer / Transplanter","Sciences"],["手术","shǒu shù","Opération chirurgicale","Sciences"],
["诊断","zhěn duàn","Diagnostiquer","Sciences"],["治疗","zhì liáo","Soigner / Traitement","Sciences"],
["康复","kāng fù","Guérison / Rééducation","Sciences"],["症状","zhèng zhuàng","Symptôme","Sciences"],
["疫情","yì qíng","Épidémie / Situation sanitaire","Sciences"],
["遗产","yí chǎn","Patrimoine / Héritage","Littérature"],["文物","wén wù","Objets du patrimoine","Littérature"],
["考古","kǎo gǔ","Archéologie","Littérature"],["文献","wén xiàn","Documents / Sources","Littérature"],
["手稿","shǒu gǎo","Manuscrit","Littérature"],["版权","bǎn quán","Droits d'auteur","Littérature"],
["书法","shū fǎ","Calligraphie","Littérature"],["雕塑","diāo sù","Sculpture","Littérature"],
["展览","zhǎn lǎn","Exposition","Littérature"],["灵魂","líng hún","Âme","Littérature"],
["信仰","xìn yǎng","Foi / Croyance","Littérature"],["神话","shén huà","Mythe","Littérature"],
["传说","chuán shuō","Légende","Littérature"],["遗迹","yí jì","Vestiges","Littérature"],
["身份","shēn fèn","Identité / Statut","Sociologie"],["角色","jué sè","Rôle","Sociologie"],
["群体","qún tǐ","Groupe / Collectivité","Sociologie"],["个体","gè tǐ","Individu","Sociologie"],
["公众","gōng zhòng","Public / Opinion publique","Sociologie"],["就业","jiù yè","Emploi","Sociologie"],
["养老","yǎng lǎo","Retraite / Soins aux aînés","Sociologie"],["保障","bǎo zhàng","Garantie / Protection","Sociologie"],
["从众","cóng zhòng","Conformisme","Sociologie"],["孤立","gū lì","Isoler / Isolé","Sociologie"],
["共鸣","gòng míng","Résonance / Écho","Psychologie"],["潜能","qián néng","Potentiel (humain)","Psychologie"],
["天赋","tiān fù","Don / Talent","Psychologie"],["挫折","cuò zhé","Revers / Frustration","Psychologie"],
["创伤","chuāng shāng","Traumatisme","Psychologie"],
["节能","jié néng","Économie d'énergie","Environnement"],["减排","jiǎn pái","Réduction des émissions","Environnement"],
["风能","fēng néng","Énergie éolienne","Environnement"],["太阳能","tài yáng néng","Énergie solaire","Environnement"],
["核能","hé néng","Énergie nucléaire","Environnement"],["植被","zhí bèi","Végétation","Environnement"],
["土壤","tǔ rǎng","Sol / Terre","Environnement"],["湿地","shī dì","Zone humide","Environnement"],
["繁荣","fán róng","Prospère / Prospérité","Adjectifs"],["卓越","zhuó yuè","Excellent / Éminent","Adjectifs"],
["平庸","píng yōng","Médiocre","Adjectifs"],["荒谬","huāng miù","Absurde","Adjectifs"],
["含蓄","hán xù","Implicite / Réservé","Adjectifs"],["直观","zhí guān","Intuitif / Visuel","Adjectifs"],
["笼统","lǒng tǒng","Vague / Trop général","Adjectifs"],["严谨","yán jǐn","Rigoureux","Adjectifs"],
["浮躁","fú zào","Impatient / Superficiel","Adjectifs"],["盲目","máng mù","Aveugle / Irréfléchi","Adjectifs"],
["片面","piàn miàn","Partial / Unilatéral","Adjectifs"],["中肯","zhòng kěn","Pertinent / Juste","Adjectifs"],
["透明","tòu míng","Transparent","Adjectifs"],["脆弱","cuì ruò","Fragile","Adjectifs"],
["坚韧","jiān rèn","Tenace / Résistant","Adjectifs"],["剧烈","jù liè","Violent / Brutal","Adjectifs"],
["显著","xiǎn zhù","Notable / Significatif","Adjectifs"],["悬殊","xuán shū","Disproportionné","Adjectifs"],
["均衡","jūn héng","Équilibré","Adjectifs"],["过度","guò dù","Excessif","Adjectifs"],
["适度","shì dù","Modéré","Adjectifs"],["永恒","yǒng héng","Éternel","Adjectifs"],
["短暂","duǎn zàn","Éphémère / Bref","Adjectifs"],["漫长","màn cháng","Interminable / Très long","Adjectifs"],
["冷漠","lěng mò","Indifférent / Froid","Adjectifs"],["默契","mò qì","Complicité / Tacite","Adjectifs"],
["何况","hé kuàng","À plus forte raison","Connecteurs"],["反而","fǎn ér","Au contraire","Connecteurs"],
["依然","yī rán","Toujours / Comme avant","Connecteurs"],["索性","suǒ xìng","Carrément / Autant","Connecteurs"],
["未免","wèi miǎn","Vraiment trop / Un peu trop","Connecteurs"],["不禁","bù jīn","Ne pas pouvoir s'empêcher","Connecteurs"],
["日益","rì yì","De jour en jour","Connecteurs"],["一味","yī wèi","Obstinément","Connecteurs"],
["相应","xiāng yìng","En conséquence / Correspondant","Connecteurs"],["势必","shì bì","Inévitablement","Connecteurs"],
["未必","wèi bì","Pas forcément","Connecteurs"],
["践行","jiàn xíng","Mettre en pratique","Verbes"],["奠定","diàn dìng","Poser (les bases)","Verbes"],
["涵盖","hán gài","Englober","Verbes"],["支撑","zhī chēng","Soutenir / Étayer","Verbes"],
["牵制","qiān zhì","Entraver / Immobiliser","Verbes"],["推行","tuī xíng","Mettre en œuvre","Verbes"],
["恪守","kè shǒu","Observer scrupuleusement","Verbes"],["深化","shēn huà","Approfondir","Verbes"],
["强化","qiáng huà","Renforcer","Verbes"],["淡化","dàn huà","Atténuer / Minimiser","Verbes"],
["激化","jī huà","Exacerber","Verbes"],["恶化","è huà","Se détériorer","Verbes"],
["转化","zhuǎn huà","Transformer / Convertir","Verbes"],["催生","cuī shēng","Faire naître / Susciter","Verbes"],
["滋生","zī shēng","Proliférer","Verbes"],["萌发","méng fā","Germer / Naître","Verbes"],
["契合","qì hé","S'accorder / Correspondre","Verbes"],["吻合","wěn hé","Coïncider","Verbes"],
["偏离","piān lí","S'écarter de","Verbes"],["违背","wéi bèi","Enfreindre / Trahir","Verbes"],
["遵循","zūn xún","Se conformer à","Verbes"],["沿袭","yán xí","Perpétuer (usage)","Verbes"],
["承载","chéng zài","Porter / Supporter","Verbes"],["支配","zhī pèi","Dominer / Régir","Verbes"],
["主导","zhǔ dǎo","Diriger / Dominer","Verbes"],["制衡","zhì héng","Contrebalancer","Verbes"],
["甄别","zhēn bié","Discerner / Trier","Verbes"],["佐证","zuǒ zhèng","Corroborer","Verbes"],
["充实","chōng shí","Enrichir / Étoffer","Verbes"],["创立","chuàng lì","Fonder","Verbes"],
["勘察","kān chá","Prospecter / Inspecter","Verbes"],["勾勒","gōu lè","Esquisser","Verbes"],
["印证","yìn zhèng","Confirmer / Attester","Verbes"],["奠基","diàn jī","Poser la première pierre","Verbes"],
["开创","kāi chuàng","Inaugurer / Ouvrir","Verbes"],["开拓","kāi tuò","Défricher / Explorer","Verbes"],
["承袭","chéng xí","Hériter / Perpétuer","Verbes"],["排查","pái chá","Passer au crible","Verbes"],
["描绘","miáo huì","Dépeindre","Verbes"],["攫取","jué qǔ","S'emparer de","Verbes"],
["效仿","xiào fǎng","Imiter / Suivre l'exemple","Verbes"],["昭示","zhāo shì","Annoncer / Révéler","Verbes"],
["梳理","shū lǐ","Démêler / Organiser","Verbes"],["沿用","yán yòng","Continuer d'utiliser","Verbes"],
["洞悉","dòng xī","Saisir pleinement","Verbes"],["渲染","xuàn rǎn","Exagérer / Mettre en relief","Verbes"],
["烘托","hōng tuō","Faire ressortir","Verbes"],["研判","yán pàn","Analyser et juger","Verbes"],
["筑牢","zhù láo","Consolider / Renforcer","Verbes"],["筛查","shāi chá","Dépister / Filtrer","Verbes"],
["筹划","chóu huà","Planifier","Verbes"],["筹建","chóu jiàn","Organiser la construction","Verbes"],
["缔造","dì zào","Fonder / Créer","Verbes"],["考量","kǎo liáng","Considérer / Peser","Verbes"],
["谋划","móu huà","Planifier / Manigancer","Verbes"],["铺垫","pū diàn","Préparer le terrain","Verbes"],
["阐明","chǎn míng","Élucider","Verbes"],["阐释","chǎn shì","Expliciter","Verbes"],
["预判","yù pàn","Anticiper / Pronostiquer","Verbes"],["延展","yán zhǎn","Étirer / Étendre","Verbes"],
["崇高","chóng gāo","Sublime / Noble","Adjectifs"],["庄严","zhuāng yán","Solennel","Adjectifs"],
["宏伟","hóng wěi","Grandiose","Adjectifs"],["壮观","zhuàng guān","Spectaculaire","Adjectifs"],
["辉煌","huī huáng","Glorieux / Éclatant","Adjectifs"],["灿烂","càn làn","Radieux / Brillant","Adjectifs"],
["崭新","zhǎn xīn","Tout neuf","Adjectifs"],["崎岖","qí qū","Accidenté / Escarpé","Adjectifs"],
["陡峭","dǒu qiào","Abrupt","Adjectifs"],["辽阔","liáo kuò","Vaste / Immense","Adjectifs"],
["广阔","guǎng kuò","Étendu","Adjectifs"],["狭隘","xiá ài","Étroit (d'esprit)","Adjectifs"],
["密集","mì jí","Dense / Concentré","Adjectifs"],["稀疏","xī shū","Clairsemé","Adjectifs"],
["匮乏","kuì fá","En pénurie / Manque","Adjectifs"],["充沛","chōng pèi","Abondant (énergie)","Adjectifs"],
["充裕","chōng yù","Ample / Suffisant","Adjectifs"],["贫瘠","pín jí","Stérile (terre)","Adjectifs"],
["富饶","fù ráo","Fertile / Riche","Adjectifs"],["昂贵","áng guì","Onéreux","Adjectifs"],
["廉价","lián jià","Bon marché","Adjectifs"],["精湛","jīng zhàn","Consommé (art)","Adjectifs"],
["娴熟","xián shú","Habile / Rodé","Adjectifs"],["笨拙","bèn zhuō","Maladroit","Adjectifs"],
["敏捷","mǐn jié","Agile / Vif","Adjectifs"],["迟钝","chí dùn","Lent / Obtus","Adjectifs"],
["机智","jī zhì","Astucieux","Adjectifs"],["睿智","ruì zhì","Sage / Perspicace","Adjectifs"],
["果断","guǒ duàn","Résolu / Décidé","Adjectifs"],["犹豫","yóu yù","Hésitant","Adjectifs"],
["鲁莽","lǔ mǎng","Téméraire / Imprudent","Adjectifs"],["稳重","wěn zhòng","Posé / Pondéré","Adjectifs"],
["轻率","qīng shuài","À la légère / Hâtif","Adjectifs"],["圆满","yuán mǎn","Parfait / Réussi","Adjectifs"],
["残缺","cán quē","Incomplet / Mutilé","Adjectifs"],["完备","wán bèi","Complet / Bien établi","Adjectifs"],
["简陋","jiǎn lòu","Rudimentaire / Sommaire","Adjectifs"],["奢侈","shē chǐ","Luxueux / Somptueux","Adjectifs"],
["精致","jīng zhì","Raffiné / Délicat","Adjectifs"],["粗糙","cū cāo","Grossier / Rugueux","Adjectifs"],
["报道","bào dào","Reportage / Rapporter","Médias"],["采访","cǎi fǎng","Interviewer","Médias"],
["访谈","fǎng tán","Entretien / Interview","Médias"],["专栏","zhuān lán","Rubrique / Chronique","Médias"],
["头条","tóu tiáo","Une (à la une)","Médias"],["栏目","lán mù","Rubrique / Programme","Médias"],
["频道","pín dào","Chaîne (TV)","Médias"],["直播","zhí bō","Diffusion en direct","Médias"],
["播报","bō bào","Diffuser (info)","Médias"],["转载","zhuǎn zǎi","Reproduire (article)","Médias"],
["爆料","bào liào","Révéler (une info)","Médias"],["辟谣","pì yáo","Démentir une rumeur","Médias"],
["谣言","yáo yán","Rumeur","Médias"],["舆情","yú qíng","État de l'opinion","Médias"],
["传媒","chuán méi","Médias","Médias"],["资讯","zī xùn","Information / Actualité","Médias"],
["社论","shè lùn","Éditorial","Médias"],["版面","bǎn miàn","Mise en page / Pages","Médias"],
["署名","shǔ míng","Signer (un article)","Médias"],["稿件","gǎo jiàn","Article soumis","Médias"],
["纪实","jì shí","Reportage-vérité","Médias"],["纪录片","jì lù piàn","Documentaire","Médias"],
["报刊","bào kān","Presse (journaux et revues)","Médias"],["刊登","kān dēng","Publier (dans un journal)","Médias"],
["连载","lián zǎi","Feuilleton / En série","Médias"],
["基础设施","jī chǔ shè shī","Infrastructures","Urbanisme"],["城镇","chéng zhèn","Ville et bourg","Urbanisme"],
["郊区","jiāo qū","Banlieue","Urbanisme"],["市区","shì qū","Zone urbaine / Centre-ville","Urbanisme"],
["街区","jiē qū","Pâté de maisons / Quartier","Urbanisme"],["地标","dì biāo","Point de repère","Urbanisme"],
["住宅","zhù zhái","Habitation / Résidence","Urbanisme"],["楼盘","lóu pán","Programme immobilier","Urbanisme"],
["房价","fáng jià","Prix de l'immobilier","Urbanisme"],["拆迁","chāi qiān","Démolition-relogement","Urbanisme"],
["绿化","lǜ huà","Végétalisation","Urbanisme"],["通勤","tōng qín","Trajet domicile-travail","Urbanisme"],
["拥堵","yōng dǔ","Embouteillage","Urbanisme"],["高架","gāo jià","Voie surélevée","Urbanisme"],
["路段","lù duàn","Tronçon de route","Urbanisme"],["人行道","rén xíng dào","Trottoir","Urbanisme"],
["市政","shì zhèng","Affaires municipales","Urbanisme"],["配套","pèi tào","Équipements associés","Urbanisme"],
["宜居","yí jū","Agréable à vivre","Urbanisme"],["密度","mì dù","Densité","Urbanisme"],
["公寓","gōng yù","Appartement","Urbanisme"],["立交桥","lì jiāo qiáo","Échangeur","Urbanisme"],
["迁徙","qiān xǐ","Migration / Déplacement","Urbanisme"],["落户","luò hù","S'établir (obtenir le hukou)","Urbanisme"],
["安置","ān zhì","Reloger / Installer","Urbanisme"],
["王朝","wáng cháo","Dynastie","Histoire"],["皇帝","huáng dì","Empereur","Histoire"],
["皇宫","huáng gōng","Palais impérial","Histoire"],["帝国","dì guó","Empire","Histoire"],
["起义","qǐ yì","Soulèvement / Insurrection","Histoire"],["统治","tǒng zhì","Gouverner / Régner","Histoire"],
["征服","zhēng fú","Conquérir","Histoire"],["侵略","qīn lüè","Envahir / Agression","Histoire"],
["战役","zhàn yì","Bataille","Histoire"],["盟约","méng yuē","Alliance / Pacte","Histoire"],
["诸侯","zhū hóu","Seigneurs féodaux","Histoire"],["封建","fēng jiàn","Féodal","Histoire"],
["奴隶","nú lì","Esclave","Histoire"],["贵族","guì zú","Noblesse / Aristocrate","Histoire"],
["平民","píng mín","Roturier / Plèbe","Histoire"],["遗址","yí zhǐ","Site / Vestige","Histoire"],
["史料","shǐ liào","Sources historiques","Histoire"],["兴衰","xīng shuāi","Essor et déclin","Histoire"],
["沦陷","lún xiàn","Tomber (à l'ennemi)","Histoire"],["衰落","shuāi luò","Déclin / Décadence","Histoire"],
["覆灭","fù miè","Anéantissement / Chute","Histoire"],["年代","nián dài","Époque / Décennie","Histoire"],
["朝代","cháo dài","Dynastie / Époque","Histoire"],["君主","jūn zhǔ","Monarque / Souverain","Histoire"],
["战乱","zhàn luàn","Troubles de la guerre","Histoire"],
["哲理","zhé lǐ","Vérité philosophique","Philosophie"],["思辨","sī biàn","Pensée spéculative","Philosophie"],
["感性","gǎn xìng","Sensibilité / Émotif","Philosophie"],["真理","zhēn lǐ","Vérité","Philosophie"],
["谬误","miù wù","Erreur / Sophisme","Philosophie"],["思潮","sī cháo","Courant de pensée","Philosophie"],
["学说","xué shuō","Doctrine / Théorie","Philosophie"],["唯物","wéi wù","Matérialiste","Philosophie"],
["唯心","wéi xīn","Idéaliste","Philosophie"],["论断","lùn duàn","Jugement / Conclusion","Philosophie"],
["世界观","shì jiè guān","Vision du monde","Philosophie"],["人生观","rén shēng guān","Conception de la vie","Philosophie"],
["伦理","lún lǐ","Éthique / Morale","Philosophie"],["良知","liáng zhī","Conscience morale","Philosophie"],
["自省","zì xǐng","Introspection","Philosophie"],["领悟","lǐng wù","Saisir profondément","Philosophie"],
["顿悟","dùn wù","Illumination soudaine","Philosophie"],["超脱","chāo tuō","Détaché (des choses)","Philosophie"],
["境界","jìng jiè","Niveau / État spirituel","Philosophie"],["觉悟","jué wù","Prise de conscience / Éveil","Philosophie"],
["思索","sī suǒ","Méditer / Réfléchir","Philosophie"],["道义","dào yì","Morale / Justice","Philosophie"],
["画蛇添足","huà shé tiān zú","En faire trop (superflu)","Chengyu"],["一举两得","yì jǔ liǎng dé","D'une pierre deux coups","Chengyu"],
["半途而废","bàn tú ér fèi","Abandonner à mi-chemin","Chengyu"],["自相矛盾","zì xiāng máo dùn","Se contredire","Chengyu"],
["守株待兔","shǒu zhū dài tù","Attendre passivement la chance","Chengyu"],["亡羊补牢","wáng yáng bǔ láo","Réparer après coup","Chengyu"],
["对牛弹琴","duì niú tán qín","Prêcher dans le désert","Chengyu"],["入乡随俗","rù xiāng suí sú","Faire comme les gens du pays","Chengyu"],
["熟能生巧","shú néng shēng qiǎo","C'est en forgeant qu'on devient forgeron","Chengyu"],["胸有成竹","xiōng yǒu chéng zhú","Avoir un plan bien arrêté","Chengyu"],
["画龙点睛","huà lóng diǎn jīng","La touche finale décisive","Chengyu"],["井底之蛙","jǐng dǐ zhī wā","Esprit borné (grenouille au puits)","Chengyu"],
["掩耳盗铃","yǎn ěr dào líng","Se voiler la face","Chengyu"],["拔苗助长","bá miáo zhù zhǎng","Vouloir aller trop vite (nuit)","Chengyu"],
["滥竽充数","làn yú chōng shù","Faire nombre sans compétence","Chengyu"],["纸上谈兵","zhǐ shàng tán bīng","Théoriser sans pratique","Chengyu"],
["一鸣惊人","yì míng jīng rén","Se révéler d'un coup","Chengyu"],["名副其实","míng fù qí shí","Mériter sa réputation","Chengyu"],
["锦上添花","jǐn shàng tiān huā","Ajouter du beau au beau","Chengyu"],["雪中送炭","xuě zhōng sòng tàn","Aider au bon moment","Chengyu"],
["一丝不苟","yì sī bù gǒu","Méticuleux","Chengyu"],["全力以赴","quán lì yǐ fù","Se donner à fond","Chengyu"],
["锲而不舍","qiè ér bù shě","Persévérer sans relâche","Chengyu"],["持之以恒","chí zhī yǐ héng","Persévérer avec constance","Chengyu"],
["精益求精","jīng yì qiú jīng","Viser toujours mieux","Chengyu"],["脚踏实地","jiǎo tà shí dì","Avoir les pieds sur terre","Chengyu"],
["实事求是","shí shì qiú shì","S'en tenir aux faits","Chengyu"],["循序渐进","xún xù jiàn jìn","Progresser par étapes","Chengyu"],
["举一反三","jǔ yī fǎn sān","Généraliser à partir d'un exemple","Chengyu"],["融会贯通","róng huì guàn tōng","Assimiler et maîtriser","Chengyu"],
["遗传","yí chuán","Hérédité / Héréditaire","Sciences"],["重力","zhòng lì","Gravité","Sciences"],
["磁场","cí chǎng","Champ magnétique","Sciences"],["电流","diàn liú","Courant électrique","Sciences"],
["电压","diàn yā","Tension / Voltage","Sciences"],["波长","bō cháng","Longueur d'onde","Sciences"],
["光谱","guāng pǔ","Spectre lumineux","Sciences"],["粒子","lì zǐ","Particule","Sciences"],
["量子","liàng zǐ","Quantique","Sciences"],["数据库","shù jù kù","Base de données","Sciences"],
["服务器","fú wù qì","Serveur","Sciences"],["带宽","dài kuān","Bande passante","Sciences"],
["纳米","nà mǐ","Nanomètre / Nano","Sciences"],["质子","zhì zǐ","Proton","Sciences"],
["中子","zhōng zǐ","Neutron","Sciences"],["真空","zhēn kōng","Vide","Sciences"],
["通胀","tōng zhàng","Inflation","Économie"],["贬值","biǎn zhí","Se déprécier / Dévaluer","Économie"],
["升值","shēng zhí","S'apprécier","Économie"],["产业链","chǎn yè liàn","Chaîne industrielle","Économie"],
["盈余","yíng yú","Excédent","Économie"],["信贷","xìn dài","Crédit","Économie"],
["投机","tóu jī","Spéculation","Économie"],["产值","chǎn zhí","Valeur de production","Économie"],
["产权","chǎn quán","Droits de propriété","Économie"],["增值","zēng zhí","Plus-value / Valorisation","Économie"],
["外汇","wài huì","Devises","Économie"],["景气","jǐng qì","Conjoncture (favorable)","Économie"],
["外债","wài zhài","Dette extérieure","Économie"],["分红","fēn hóng","Distribuer des dividendes","Économie"],
["流通","liú tōng","Circulation","Économie"],
["条例","tiáo lì","Règlement / Décret","Politique"],["执政","zhí zhèng","Exercer le pouvoir","Politique"],
["体制","tǐ zhì","Système / Régime","Politique"],["反腐","fǎn fǔ","Anticorruption","Politique"],
["特权","tè quán","Privilège","Politique"],["选民","xuǎn mín","Électeur","Politique"],
["共和","gòng hé","République","Politique"],["官员","guān yuán","Fonctionnaire / Officiel","Politique"],
["执法","zhí fǎ","Appliquer la loi","Politique"],["政体","zhèng tǐ","Régime politique","Politique"],
["施政","shī zhèng","Politique gouvernementale","Politique"],["法治","fǎ zhì","État de droit","Politique"],
["联邦","lián bāng","Fédéral / Fédération","Politique"],["自治","zì zhì","Autonomie","Politique"],
["议案","yì àn","Projet de loi / Motion","Politique"],
["阶级","jiē jí","Classe (sociale)","Sociologie"],["贫富","pín fù","Riches et pauvres","Sociologie"],
["流动","liú dòng","Mobilité / Circuler","Sociologie"],["边缘","biān yuán","Marge / Périphérie","Sociologie"],
["弱势","ruò shì","Défavorisé / Vulnérable","Sociologie"],["公益","gōng yì","Intérêt public / Caritatif","Sociologie"],
["互助","hù zhù","Entraide","Sociologie"],["凝聚力","níng jù lì","Cohésion","Sociologie"],
["风俗","fēng sú","Coutume / Mœurs","Sociologie"],["主流","zhǔ liú","Courant dominant","Sociologie"],
["民众","mín zhòng","Le peuple / Population","Sociologie"],["潮流","cháo liú","Tendance / Courant","Sociologie"],
["群众","qún zhòng","Masses / Le peuple","Sociologie"],["邻里","lín lǐ","Voisinage","Sociologie"],
["隔阂","gé hé","Barrière / Incompréhension","Sociologie"]
]}
};
Object.keys(data).forEach(function(k){
  data[k].words=data[k].words.map(function(a){return{h:a[0],p:a[1],fr:a[2],c:a[3]};});
});

// ════════════════════════════════════════════════
// SENTENCE DATA
// ════════════════════════════════════════════════
var sentences={
yct1:[
["我___苹果。","吃","Je mange une pomme."],
["___是我的老师。","他","Il est mon professeur."],
["这是我的___。","书","C'est mon livre."],
["今天我___学校。","去","Aujourd'hui je vais à l'école."],
["我___一只猫。","有","J'ai un chat."],
["你叫___名字？","什么","Tu t'appelles comment ?"],
["他是我的好___。","朋友","Il est mon bon ami."],
["我___水。","喝","Je bois de l'eau."],
["我的___很漂亮。","妈妈","Ma maman est très belle."],
["这只___很大。","狗","Ce chien est grand."]
],
yct2:[
["我很___中国音乐。","喜欢","J'aime beaucoup la musique chinoise."],
["他___看电影。","想","Il veut regarder un film."],
["今天___很好，很暖和。","天气","Aujourd'hui le temps est beau, il fait chaud."],
["她每天在___工作。","医院","Elle travaille à l'hôpital tous les jours."],
["我们一起___歌吧！","唱","Chantons ensemble !"],
["我每天早上喝___。","牛奶","Je bois du lait chaque matin."],
["这件衣服很___，我买不起。","贵","Ce vêtement est très cher, je ne peux pas me le permettre."],
["他骑___去学校。","自行车","Il va à l'école en vélo."],
["我的朋友___喜欢足球。","也","Mon ami aime aussi le football."],
["我们___去学校。","一起","Nous allons ensemble à l'école."]
],
yct3:[
["他___了，需要吃药。","生病","Il est tombé malade, il doit prendre ses médicaments."],
["我们___一起去旅行。","决定","Nous avons décidé de voyager ensemble."],
["___他很累，他还是完成了工作。","虽然","Bien qu'il soit fatigué, il a quand même terminé le travail."],
["旅行前要先办好___。","护照","Avant de voyager, il faut obtenir son passeport."],
["飞机___的时间是早上八点。","出发","L'heure de départ de l'avion est huit heures du matin."],
["这个___非常美丽，很多人来旅游。","城市","Cette ville est très belle, beaucoup de gens viennent y voyager."],
["___你努力学习，就会进步。","如果","Si tu étudies sérieusement, tu progresseras."],
["我想更多___中国文化。","了解","Je veux en savoir plus sur la culture chinoise."],
["为了___，我们应该多运动。","健康","Pour être en bonne santé, nous devrions faire plus d'exercice."],
["今年___天气很热，我们去游泳吧。","夏天","Cet été le temps est très chaud, allons nager."]
],
yct4:[
["他在台上做了精彩的___。","演讲","Il a fait un discours brillant sur scène."],
["保护___是我们共同的责任。","环境","Protéger l'environnement est notre responsabilité commune."],
["___是人类追求的重要目标。","和平","La paix est un objectif important que l'humanité poursuit."],
["他用___的态度面对生活中的困难。","乐观","Il fait face aux difficultés de la vie avec une attitude optimiste."],
["___是社会进步的重要基础。","平等","L'égalité est une base importante du progrès social."],
["他花了很多时间___这个问题。","研究","Il a passé beaucoup de temps à étudier ce problème."],
["___正在改变我们的生活方式。","人工智能","L'intelligence artificielle est en train de changer nos modes de vie."],
["只有___，才能实现目标。","坚持","Ce n'est qu'en persévérant qu'on peut atteindre ses objectifs."],
["每个人都有___表达自己想法的权利。","自由","Chacun a le droit de s'exprimer librement."],
["做好这份工作需要___和细心。","耐心","Bien faire ce travail nécessite de la patience et de la minutie."]
],
yct5:[
["哲学家们试图探寻事物的___。","本质","Les philosophes cherchent à sonder l'essence des choses."],
["___是将感情投射到他人处境的能力。","共情","L'empathie est la capacité de se mettre à la place d'autrui."],
["维护___对于民主社会至关重要。","透明度","Maintenir la transparence est essentiel dans une société démocratiques."],
["保护___是应对气候变化的核心目标。","生物多样性","Protéger la biodiversité est l'objectif central pour faire face aux changements climatiques."],
["___将彻底革新信息安全领域。","量子计算","L'informatique quantique va révolutionner le domaine de la sécurité informatique."],
["他总是能控制自己的___，保持冷静。","情绪","Il arrive toujours à contrôler ses émotions et à rester calme."],
["___技术让人们足不出户体验世界。","虚拟现实","La technologie de réalité virtuelle permet aux gens de découvrir le monde sans quitter leur domicile."],
["___是通过间接比较表达深层含义的修辞手法。","隐喻","La métaphore est une figure de style qui exprime un sens profond par comparaison indirecte."],
["应对___需要全球合作与可持续发展。","沙漠化","Faire face à la désertification nécessite une coopération mondiale et un développement durable."],
["经济___加剧了社会矛盾与不稳定。","不平等","Les inégalités économiques aggravent les contradictions sociales et l'instabilité."]
]
};
